[[resultsets]]
== Working with result sets

When a SELECT statement is executed, the results of the query processing
are returned through the implementation of the `java.sql.ResultSet`
interface.

=== ResultSet properties

==== ResultSet Types

JDBC 3.0 specification defines three types of result sets

* `TYPE_FORWARD_ONLY` – the result set is not scrollable, cursor can
move only forward. When the `TRANSACTION_READ_COMMITTED` isolation level
is used, the result set will return all rows that are satisfying the
search condition at the moment of the `ResultSet.next()` call. In other
cases result set will return only rows that were visible at the moment
of the transaction start.
* `TYPE_SCROLL_INSENSITIVE` – the result set is scrollable, the cursor
can move back and forth, can be positioned on the specified row. Only
rows satisfying the condition at the time of query execution are
visible.
* `TYPE_SCROLL_SENSITIVE`, is not supported by Firebird and Jaybird.
Driver allows application to ask for this type of result set, however
according to the JDBC specification, the type is "downgraded" to the
previous type and corresponding warning is added to the connection
object.

****
_Due to a missing support of scrollable cursors in Firebird, their
support (`TYPE_SCROLL_INSENSITIVE` result set type) is implemented by
fetching the complete result set to the client. Scrolling happens in the
memory on the client. This can have adverse effect on the system memory
usage and performance when the result set is large._
****

==== ResultSet Concurrency

Result set concurrency specifies whether the result set object can be
updated directly or a separate SQL request should be used to update the
row. Result sets that allow direct modification using the
ResultSet.updateXXX methods are usually used in GUI applications which
allow in-place editing of the underlying result set.

Type of result set concurrency is specified during statement creation
and cannot be changed later. Jaybird supports two types of result set
concurrency:

* `CONCUR_READ_ONLY` is available for all types of result sets. It tells
the driver that direct update of the result set is not possible and all
`ResultSet.updateXXX` methods should throw an exception.
* `CONCUR_UPDATABLE` is supported only under certain conditions that are
needed for the driver to correctly construct a DML request that will
modify exactly one row. These conditions are:
** the SELECT statement that generated the result set references only
one table;
** all columns that are not referenced by the SELECT statement allow
`NULL` values, otherwise it won't be possible to insert new rows;
** the SELECT statement does not contain `DISTINCT` predicate, aggregate
functions, joined tables or stored procedures;
** the SELECT statement references all columns from the table primary
key definition or the `RDB$DB_KEY` column.

==== ResultSet Holdability

Result set holdability tells driver whether result sets should be kept
open across commits. `ResultSet.HOLD_CURSORS_OVER_COMMIT` tells the
driver to keep the result set object open, while
`ResultSet.CLOSE_CURSORS_AT_COMMIT` tells driver to close them on
commit. This property is available only in JDBC 3.0 specification.

When application calls `Connection.commit()`, the Firebird server closes
all open result sets. It is not possible to tell the server to keep
result set open over commit unless "commit retaining" mode is used. This
mode is global for the complete connection and is not suitable for
holdability control on the statement level. Also this mode is believed
to have an undesired side-effect for read-write transactions as it
inhibits garbage collection. Because of these two reasons "commit
retaining" is not used in Jaybird during normal execution. Applications
are able to commit the transaction keeping the result sets open by
executing a `"COMMIT RETAIN"` SQL statement.

=== ResultSet manipulation

`ResultSet` objects are created when either
`Statement.executeQuery(String)` or `Statement.getResultSet()` methods
are called. The latter is used in combination with the
`Statement.execute(String)` method and can be called only once per
result set (see the following two examples).

****
_Note, current implementation does not allow to call `getResultSet()`
method after using the `executeQuery(String)` method of the `Statement`
class. The JDBC 3.0 specification is unclear on this topic and JDBC
drivers of different vendors treat it differently._
****

[source,java]
.Using Statement.executeQuery(String) method
----
Statement stmt = connection.createStatement();
ResultSet rs = stmt.executeQuery("SELECT * FROM myTable");
----

[source,java]
.Using Statement.getResultSet() method
----
Statement stmt = connection.createStatement();
boolean hasResultSet = stmt.execute("SELECT * FROM myTable");
if (hasResultSet) {
    ResultSet rs = stmt.getResultSet();
    ...
}
----

==== Accessing the values in the result set

Depending on the type of the result set it is possible to move the cursor either forward only (link:#using-forward-only[next example]) or using absolute and relative positioning (link:#using-scrollable-updatable[second example below]).

Values of the result set are obtained by calling the corresponding
getter method depending on the type of column. For example the
`ResultSet.getInt(1)` method returns the value of the first column as an
`int` value. If value of the column is not integer, driver tries to
convert it according to the "Data Type Conversion Table" specified in
<<Data Type Conversion Table>>. If conversion is not possible, an exception is thrown.

There are two possibilities to obtain data from the result set columns:
by column name or by column position. Position of the first column is 1.
Names supplied to getter methods are case-insensitive. The search first
happens in the column aliases, and if no match found, driver checks the
original column names. If there is more then one column matching the
specified name (even if the original names were quoted), the first match
is taken.

When getters for primitive types are used and original value in the
result set is NULL, driver returns a default value for that type. For
example `getInt()` method will return 0. In order to know whether the
value is really 0 or NULL, you have to call `ResultSet.wasNull(...)`
method.

Getters that return object values (`getString`, `getDate`, `getObject`,
etc.) will correctly report a `null` value for the columns containing
NULL.

[[using-forward-only]]
[source,java]
.Example of using forward-only result sets
----
Statement forwardStatement = connection.createStatement();
ResultSet rs = forwardStatement.executeQuery(
    "SELECT id, name, price FROM myTable");

while(rs.next()) {
    int id = rs.getInt(1);
    String name = rs.getString("name");
    double price = rs.getDouble(3);
}
----

==== Updating records in the result set

Scrollable cursors are especially useful when result of some query is
displayed by the application which also allows the user to directly edit
the data and post the changes to the database.

[[using-scrollable-updatable]]
[source,java]
.Example of using scrollable and updatable result sets
----
Statement scrollStatement = connection.createStatement(
    ResultSet.TYPE_SCROLL_INSENSITIVE,
    ResultSet.CONCUR_UPDATABLE);
    
ResultSet rs = scrollStatement.executeQuery(
    "SELECT id, name, price FROM myTable");
    
rs.absolute(1);                  // move to the first row 
rs.updateString(2, anotherName); // update the name
rs.updateRow();                  // post changes to the db

rs.moveToInsertRow();
rs.updateInt(1, newId);
rs.updateString(2, newName);
rs.updateDouble(3, newPrice);
rs.insertRow();
rs.moveToCurrentRow();

rs.relative(-2);
----

The code example above shows how to update first row, insert new one and
after that move two records backwards.

Also an application can update the current row using so called
"positioned updates" on named cursors. This technique can be used only
with forward-only cursors, since application can update only the row to
which the server-side cursor points to. In case of scrollable cursors
the complete result set is fetched to the client and then the
server-side cursor is closed. link:#using-positioned-updates[The example below] shows how to use positioned updates. First of all application has to specify the name of
the cursor and the list of the columns that will be updated before the
query is executed. This name is later used in the UPDATE statement as
showed on the example.

[[using-positioned-updates]]
[source,java]
.Example of using the positioned updates
----
Statement selectStmt = connection.createStatement();
selectStmt.setCursorName("someCursor");

Statement updateStmt = connection.createStatement();
ResultSet rs = selectStmt.executeQuery(
    "SELECT id, name, price FROM myTable " +
    "FOR UPDATE OF myColumn");
    
while(rs.next()) {
    ...
    if (someCondition) {
        updateStmt.executeUpdate("UPDATE myTable " +
            "SET myColumn = myColumn + 1 " +
            "WHERE CURRENT OF " + rs.getCursorName());
    }
}
----

==== Closing the result set

A result set is closed by calling the `ResultSet.close()` method. This
releases the associated server resources and makes the `ResultSet`
object available for garbage collection. It is strongly recommended to
explicitly close result sets in auto-commit mode or
`ResultSet.TYPE_SCROLL_INSENSITIVE` result sets, because this releases
memory used for the cached data.

The result set object is also closed automatically, when the statement
that created it is closed or re-executed. In auto-commit mode, the
result set is closed automatically if any statement is executed over the
same connection.

