[[ref-binary]]
=== Binary types BINARY/VARBINARY

The JDBC (and SQL standard) types `BINARY` and `VARBINARY` are called `CHAR(n) CHARACTER SET OCTETS` and `VARCHAR(n) CHARACTER SET OCTETS` in Firebird.

([.since]_Firebird 4.0_) Firebird 4.0 introduces the names `BINARY` and `VARBINARY`/`BINARY VARYING` as aliases for `(VAR)CHAR(n) CHARACTER SET OCTETS`.

In Java, binary and varbinary are usually handled with byte arrays and `InputStream`/`OutputStream`.

[[ref-binary-always]]
==== Always BINARY/VARBINARY

Jaybird always handles `(VAR)CHAR(n) CHARACTER SET OCTETS` as JDBC types as `BINARY`/`VARBINARY`.

Jaybird will report the JDBC `BINARY`/`VARBINARY` type information in all metadata (`DatabaseMetaData`, `ResultSetMetaData`, `ParameterMetaData`) for columns and parameters of type `(VAR)CHAR(n) CHARACTER SET OCTETS`, and `getObject(int/String)` will always return `byte[]`.

The getters (on result set/callable statement), setters (prepared/callable statement), and update methods (result set) for columns of this type are restricted to:

* `get/set/updateNull`
* `get/set/updateBytes`
* `get/set/updateBinaryStream`
* `get/set/updateAsciiStream`
* `get/set/updateString` (using the default encoding or connection encoding)
* `get/set/updateCharacterStream` (using the default encoding or connection encoding)
* `get/set/updateObject` (with `String`, `byte[]`, `InputStream`, `Reader`)
* `get/setObject` with a `java.sql.RowId`
* `get/setRowId`

Other getters/setters/updaters or object types supported for 'normal' `(VAR)CHAR` fields are not available.
