[[ref-decimal]]
=== Exact numeric types DECIMAL/NUMERIC

The JDBC types `DECIMAL` and `NUMERIC` are supported by Firebird and Jaybird and map to `java.math.BigDecimal`.

NOTE: Behaviour in Firebird of `NUMERIC` is closer to the SQL standard `DECIMAL` behaviour than the SQL standard `NUMERIC` behaviour.
The precision specified is the minimum precision, not the exact precision.

[[ref-decimal-precision-range]]
==== Precision and range

In Firebird 3.0 and earlier, the maximum precision and scale of `DECIMAL` and `NUMERIC` is 18.footnote:[In practice, values with precision 19 are possible up to the maximum value of the `BIGINT` backing the value.]

In Firebird 4.0 and higher, the maximum precision and scale of `DECIMAL` and `NUMERIC` is 38.
Any `NUMERIC` or `DECIMAL` with a precision between 19 and 38 will allow storage up to a precision of 38.footnote:[In practice, values with precision 39 are possible up to the maximum value of the `INT128` backing the value.]

In the implementation in Firebird, this extended precision is backed by an `INT128`.

Values set on a field or parameter will be rounded to the target scale of the field using `RoundingMode.HALF_EVEN`.
Values exceeding a precision of 38 after rounding will be rejected with a `TypeConversionException`.
