[[ref-auth-plugins]]
=== Authentication plugins

[.since]_Jaybird 3_ +
[.since]_Firebird 3_

Firebird 3 introduced authentication plugins together with a new authentication model.
By default, Firebird 3 uses the authentication plugin `Srp` (_Secure remote password_).
It also includes plugins `Legacy_Auth` that supports the pre-Firebird-3 authentication mechanism, and - [.since]_Firebird 3.0.4_ - `Srp256`.
Firebird 4 introduced the plugins `Srp224`, `Srp384` and `Srp512`.

The original `Srp` plugin uses SHA-1, the new Srp-variants use SHA-224, SHA-256, SHA-384 and SHA-512 respectively.footnote:[Internally `SrpNNN` continues to uses SHA-1, only the client-proof applies the SHA-NNN hash. See also https://github.com/FirebirdSQL/firebird/issues/6051[firebird#6051^]).]

[NOTE]
====
Support for these plugins depends on support of these hash algorithms in the JVM.
For example, SHA-224 is not supported in Oracle Java 7 by default and may require additional JCE libraries.
====

[[ref-auth-plugins-default]]
==== Default authentication plugins

[[ref-auth-plugins-default-jb5]]
===== Jaybird 5

The default plugins applied by Jaybird 5 are -- in order -- `Srp256` and `Srp`.
This applies only for the pure Java protocol and only when connecting to Firebird 3 or higher.
The native implementation will use its own default or the value configured through its `firebird.conf`.

When connecting to Firebird 3 or higher, the pure Java protocol in Jaybird 4 and higher will no longer try the `Legacy_Auth` plugin by default as it is an unsafe authentication mechanism.
We strongly suggest to use SRP users only, but if you really need to use legacy authentication, you can specify connection property `authPlugins=Legacy_Auth`, see <<ref-auth-plugins-config>> for details.

When connecting to Firebird 3 versions earlier than 3.0.4, or if `Srp256` has been removed from the `AuthServer` setting in Firebird, this might result in slightly slower authentication because more roundtrips to the server are needed.
After an attempt to use `Srp256` fails, authentication continues with `Srp`.

To avoid this, consider explicitly configuring the authentication plugins to use, see <<ref-auth-plugins-config>> for details.

Firebird 2.5 and earlier will always use legacy authentication.

[[ref-auth-plugins-default-jb4]]
===== Jaybird 4

The default plugins applied by Jaybird 4 are -- in order -- `Srp256` and `Srp`.

See section on <<ref-auth-plugins-default-jb5>> for further details.

[[ref-auth-plugins-default-jb3]]
===== Jaybird 3

Jaybird 3 will try - in order - `Srp` and `Legacy_Auth`, or - [.since]_Jaybird 3.0.5_ - `Srp256`, `Srp` and `Legacy_Auth`.
It is not possible to specify a different configuration in Jaybird 3.

Firebird 2.5 and earlier will always use legacy authentication.

[[ref-auth-plugins-config]]
==== Configure authentication plugins

[.since]_Jaybird 4_

Jaybird 4 introduces the connection property `authPlugins` (alias `auth_plugin_list`) to specify the authentication plugins to try when connecting.
The value of this property is a comma-separated list with the plugin names.

[NOTE]
====
The `authPlugins` values can be separated by comma, space, tab, or semi-colon.
We recommend using comma as the separator.
The semi-colon should not be used in a JDBC URL as there the semi-colon is a separator between connection properties.
====

Unknown or unsupported plugins will be logged and skipped. 
When no known plugins are specified, Jaybird will throw an exception with:

* For pure Java
+
_Cannot authenticate. No known authentication plugins, requested plugins: [&lt;plugin-names&gt;] [SQLState:28000, ISC error code:337248287]_
* For native
+
_Error occurred during login, please check server firebird.log for details [SQLState:08006, ISC error code:335545106]_

The `authPlugins` property only affects connecting to Firebird 3 or later.
It will be ignored when connecting to Firebird 2.5 or earlier.
The setting will also be ignored for native connections when using a fbclient library of version 2.5 or earlier.

Examples:

* JDBC URL to connect using `Srp256` only:
+
----
jdbc:firebirdsql://localhost/employee?authPlugins=Srp256
----
* JDBC URL to connect using `Legacy_Auth` only (this is unsafe!)
+
----
jdbc:firebirdsql://localhost/employee?authPlugins=Legacy_Auth
----
* JDBC URL to try `Legacy_Auth` before `Srp512` (this order is unsafe!)
+
----
jdbc:firebirdsql://localhost/employee?authPlugins=Legacy_Auth,Srp512
----
        
The property is also supported by the data sources, service managers and event manager.

[[ref-auth-plugins-external]]
==== External authentication plugin support (experimental)

[.since]_Jaybird 4_

If you develop your own Firebird authentication plugin (or use a third-party authentication plugin), it is possible - for pure Java only - to add your own authentication plugin by implementing the interfaces 
 
* `org.firebirdsql.gds.ng.wire.auth.AuthenticationPluginSpi`
* `org.firebirdsql.gds.ng.wire.auth.AuthenticationPlugin`

The SPI implementation needs to be listed in `META-INF/services/org.firebirdsql.gds.ng.wire.auth.AuthenticationPluginSpi` in your jar.

This support is experimental and comes with a number of caveats:

* We haven't tested this extensively (except for loading Jaybird's own plugins internally)
* The authentication plugin (and provider) interfaces should be considered unstable; 
they may change with point-releases (although we will try to avoid that) 
* For now it will be necessary for the jar containing the authentication plugin to be loaded by the same class loader as Jaybird itself

If you implement a custom authentication plugin and run into problems, contact us on the Firebird-Java mailing list.

If you use a native connection, check the Firebird documentation how to add third-party authentication plugins to fbclient.
