[#ref-create-database-if-not-exist]
=== Create database if it does not exist

[.since]_Jaybird 6_

The Boolean connection property `createDatabaseIfNotExist` instructs Jaybird to attempt to create the database if it does not exist yet.
This property can be used in the JDBC URL, in the `Properties` object passed to `DriverManager`, and can be set on data sources.

Jaybird also allows you to create databases using `org.firebirdsql.management.FBManager`, but this is not always accessible, for example in tools or libraries that only expose or use the JDBC API.
This property provides an alternative to create databases in those cases.

Jaybird also allows you to set or override connection properties specifically for creating the database by suffixing the property name with `@create` (case-sensitive).
This can be used to set configuration properties that are only relevant for creating the database, or -- for example -- to use a different user or role for creating the database than used for normal connections.

As an example:

[listing,java]
----
String jdbcUrl = "jdbc:firebird://localhost/exampledb" +
    "?createDatabaseIfNotExist=true&" +
    "user@create=sysdba&password@create=masterkey";
try (Connection connection = DriverManager.getConnection(
    jdbcUrl, "normaluser", "password")) {
  // ...
}
----

If the database already exists, the connection will be made with user `normaluser`, but if the database does not exist, the database will be created with user `sysdba`.

[IMPORTANT]
====
The errors Firebird returns do not make it possible to determine definitively if the database does not exist, or if there is another reason that the connection failed.
Jaybird applies some simple rules to exclude some classes of errors, and not attempt to create a database in those cases.

If you find cases where you think Jaybird should not (or on the contrary should) attempt to create a database, please report them on https://github.com/FirebirdSQL/jaybird/issues[^].
====

For more information, see also https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2024-02-create-database-through-jdbc-url.adoc[jdp-2024-02: Create database through JDBC URL^].
