[[ref-dbcrypt]]
=== Database encryption support

Jaybird 3.0.4 added support for Firebird 3.0 database encryption callbacks in the pure Java implementation of the version 13 protocol.

The current implementation is simple and only supports replying with a static value from a connection property. 
Be aware that a static value response for database encryption is not very secure as it can easily lead to replay attacks or unintended key exposure. 

Future versions of Jaybird may introduce plugin support for database encryption plugins that require a more complex callback.

The static response value of the encryption callback can be set through the `dbCryptConfig` connection property. 
Data sources and `ServiceManager` implementations have an equivalent property with the same name. 
This property can be set as follows:

* Absent or empty value -- empty response to callback (depending on the database encryption plugin this may just work or yield an error later).
* Strings prefixed with `base64:` -- rest of the string is decoded as _base64_ to bytes.
The `=` padding characters are optional, but when present they must be valid (that is: if you use padding, you must use the right number of padding characters for the length).
* Strings prefixed with `base64url:` -- rest of the string is decoded as _base64url_ to bytes (using "`Base 64 URL and Filename safe`" alphabet).
As with `base64:`, the `=` padding characters are optional
* Plain string value -- string is encoded to bytes using UTF-8, and these bytes are used as the response.
    
Because of the limitation of connection URL parsing, avoid plain string values with `&` or `;`.
Likewise, avoid `:` so that we can support other prefixes similar to `base64:` and `base64url:` in the future.
If you need these characters, consider using a base64 encoded value instead.

Jaybird expects keys and values in the JDBC URL to be URL encoded.
We recommend using _base64url_, and *not* _base64_, as _base64_ encoded values can contain `{plus}`, which must be escaped as `%2B` in the JDBC URL, otherwise it is decoded to a space and decoding will fail.

For service operations, as implemented in the `org.firebirdsql.management` package, Firebird requires the `KeyHolderPlugin` configuration to be globally defined in `firebird.conf`. 
Database-specific configuration in `databases.conf` will be ignored for service operations. 
Be aware that some service operations on encrypted databases are not supported by Firebird 3.0 (e.g. `gstat` equivalents other than `gstat -h` or `gstat -e`).

[WARNING]
====
Other warnings and limitations

* Database encryption callback support is only available in the pure Java implementation. 
Support for native and embedded connections may be added in a future version.
* The database encryption callback does not require an encrypted connection, so the key can be exchanged unencrypted if wire protocol encryption has been disabled client-side or server-side, or if legacy authentication is used.
Consider setting connection property `wireCrypt=REQUIRED` to force encryption (caveat: see the next point).
* Firebird may ask for the database encryption key before the connection has been encrypted (for example if the encrypted database itself is used as the security database).
* We cannot guarantee that the `dbCryptConfig` value cannot be obtained by someone with access to your application or the machine hosting your application (although that in itself would already imply a severe security breach).
====
