[[ref-dbcrypt]]
=== Database encryption support

[.since]_Jaybird 3.0.4_ +
[.since]_Firebird 3.0_

Jaybird 3.0.4 added support for Firebird 3.0 database encryption callbacks in the pure Java implementation of the version 13 protocol.

The current implementation is simple and only supports replying with a static value from a connection property. 
Be aware that a static value response for database encryption is not very secure as it can easily lead to replay attacks or unintended key exposure. 

Future versions of Jaybird (likely 4, maybe 5) will introduce plugin support for database encryption plugins that require a more complex callback.

The static response value of the encryption callback can be set through the `dbCryptConfig` connection property. 
Data sources and `ServiceManager` implementations have an equivalent property with the same name. 
This property can be set as follows:

* Absent or empty value: empty response to callback (depending on the database encryption plugin this may just work or yield an error later).
* Strings prefixed with `base64:`: rest of the string is decoded as _base64_ to bytes.
The `=` padding characters are optional, but when present they must be valid (that is: if you use padding, you must use the right number of padding characters for the length).
* [.since]_Jaybird 5_ Strings prefixed with `base64url:`: rest of the string is decoded as _base64url_ to bytes (using "`Base 64 URL and Filename safe`" alphabet).
As `base64:`, the `=` padding characters are optional
* Plain string value: string is encoded to bytes using UTF-8, and these bytes are used as the response.
    
Because of the limitation of connection URL parsing, we strongly suggest to avoid plain string values with `&` or `;`. 
Likewise, avoid `:` so that we can support other prefixes similar to `base64:` and `base64url:` in the future.
If you need these characters, consider using a base64 encoded value instead.

[.since]_Jaybird 3.0.9_ Jaybird 3.0.9 and higher expects keys and values in the JDBC URL to be URL encoded. 
When the _base64_ encoded value contains `{plus}`, it must be escaped as `%2B` in the JDBC URL, otherwise it is decoded to a space and decoding will fail.
Jaybird 5 introduced _base64url_, an alternative to _base64_, which doesn't use `{plus}`, thus avoiding the need to escape.

For service operations, as implemented in the `org.firebirdsql.management` package, Firebird requires the `KeyHolderPlugin` configuration to be globally defined in `firebird.conf`. 
Database-specific configuration in `databases.conf` will be ignored for service operations. 
Be aware that some service operations on encrypted databases are not supported by Firebird 3.0 (e.g. `gstat` equivalents other than `gstat -h` or `gstat -e`).

[WARNING]
====
Other warnings and limitations

* Database encryption callback support is only available in the pure Java implementation. 
Support for native and embedded connections will be added in a future version.
* The database encryption callback does not require an encrypted connection, so the key can be exchanged unencrypted if wire protocol encryption has been disabled client-side or server-side, or if legacy authentication is used.
Consider setting connection property `wireCrypt=REQUIRED` to force encryption (caveat: see the next point).
* Firebird may ask for the database encryption key before the connection has been encrypted (for example if the encrypted database itself is used as the security database). 
_This applies to v15 protocol support, which is not yet available._
* The improvements of the versions 14 and 15 wire protocol are not implemented, and as a result encrypted security databases (external or security database hosted in the database itself) will not work unless the encryption plugin does not require a callback. 
Support for the version 15 wire protocol will be added in a future version.
* We cannot guarantee that the `dbCryptConfig` value cannot be obtained by someone with access to your application or the machine hosting your application (although that in itself would already imply a severe security breach).
====
