[[ref-firebirdautocommit]]
=== Firebird auto commit mode (experimental)

[CAUTION]
====
This functionality is experimental, and will remain so unless Firebird changes how its auto-commit mode works.
**Do not use this unless you really know what you're doing.**

Incorrect use of this functionality can result in excessive growth of the database due to increases in back-version chains of records, which can also cause performance degradation.
Additionally, when used with an isolation level other than READ COMMITTED, the connection will only see changes committed at the time the initial transaction was started;
the auto-commit barrier will not make new committed changes visible to the current transaction.
====

This option is enabled by specifying the connection property `useFirebirdAutocommit=true`.

With this option, a connection in auto-commit mode will configure the transaction to use `isc_tpb_autocommit`.
This means that Firebird server will internally commit the transaction after each statement completion using "`__commit retain__`".
Jaybird itself will not commit until connection close (or disabling auto-commit).
The exception is if the statement was of type `isc_info_sql_stmt_ddl`, in that case Jaybird will commit on statement success and rollback on statement failure (just like it does for all statements in normal auto-commit mode).
The reason is that Firebird for some DDL commands only executes at a real commit boundary and relying on the Firebird auto-commit is insufficient.

On statement completion (as specified in JDBC), result sets will still close unless they are holdable over commit. 
The result set is only closed client-side, which means that the cursor remains open server-side to prevent roundtrips.
This may lead to additional resource usage server-side unless explicitly closed in the code.
Note that any open blobs will be closed client- and server-side (until this is improved with https://github.com/FirebirdSQL/jaybird/issues/442[jaybird#442^]).

A connection can be interrogated using `FirebirdConnection.isUseFirebirdAutocommit()` if it uses `isc_tpb_autocommit`.

If you manually add `isc_tpb_autocommit` to the transaction parameter buffer, and you enable this option, the `isc_tpb_autocommit` will be removed from the TPB on `setAutoCommit(false)`.

Artificial testing with repeated inserts (using a prepared statement) against a Firebird server on localhost shows that this leads to a reduction of execution time of +/- 7%.

Support for this option is experimental, and should only be enabled if you 1) know what you're doing, and 2) really need this feature. 
Internally `isc_tpb_autocommit` uses `commit_retaining`, which means that using this feature may increase the transaction gap with associated sweep and garbage collection impact.
