[[ref-wirecrypt]]
=== Wire encryption support

[.since]_Firebird 3.0_

Firebird 3.0 and higher have support for encrypting the data sent over the network.
This _wire encryption_ is configured using the connection property `wireCrypt`, with the following (case-insensitive) values:

 `DEFAULT`:: default (value used when `wireCrypt` is not specified; you'd normally not specify `DEFAULT` explicitly)
 `ENABLED`:: enable, but not require, wire encryption
 `REQUIRED`:: require wire encryption (only if Firebird version is 3.0 or higher)
 `DISABLED`:: disable wire encryption 
 
The default value acts as `ENABLED` for pure Java connections, for JNA (native) connections this wil use the fbclient default (either `Enabled` or the configured value of `WireCrypt` from a `firebird.conf` read by the native library).

Connection property `wireCrypt=REQUIRED` will **not** reject unencrypted connections when connecting to Firebird 2.5 or lower. 
This behavior matches the Firebird 3.0 client library behavior.
The value will also be ignored when using native connections with a Firebird 2.5 client library.

Using `wireCrypt=DISABLED` when Firebird 3.0 or higher uses setting `WireCrypt = Required` (or vice versa) will yield error _"Incompatible wire encryption levels requested on client and server"_ (error: _isc_wirecrypt_incompatible / 335545064_).

The same error is raised when connecting to Firebird 3.0 and higher with a legacy authentication user with connection property `wireCrypt=REQUIRED`.

Alternative wire encryption plugins are currently not supported, although we made some preparations to support this. 
If you want to develop such a plugin, contact us on the https://groups.google.com/g/firebird-java[firebird-java Google Group^], so we can work out the details of adding plugin support.

[WARNING]
====
The implementation comes with a number of caveats:
 
* we cannot guarantee that the session key cannot be obtained by someone with access to your application or the machine hosting your application (although that in itself would already imply a severe security breach)
* the ARC4 encryption -- the default provided by Firebird -- is considered to be a weak (maybe even broken) cipher these days
* the encryption cipher uses ARCFOUR with a 160 bits key, this means that the unlimited Cryptographic Jurisdiction Policy needs to be used (or at minimum a custom policy that allows ARCFOUR with 160 bits keys). See also FAQ entry https://www.firebirdsql.org/file/documentation/drivers_documentation/java/faq.html#encryption-key-did-not-meet-algorithm-requirements-of-symmetricarc4-337248282[Encryption key did not meet algorithm requirements of Symmetric/Arc4 (337248282)^]  
====
