[[jb3]]
=== Jaybird 3

[NOTE]
====
Jaybird 3 is end-of-life and will not receive further updates.
We recommend upgrading to <<jb5,Jaybird 5>>.
====

[[jb3-java]]
==== Java support

Jaybird 3 supports Java 7 (JDBC 4.1), Java 8 (JDBC 4.2), and Java 9 - 11 (JDBC 4.3). 

There are no Java 9+ specific builds, the Java 8 builds have the same source and all JDBC 4.3 related functionality.

Given the limited support period for Java 9 and higher versions, we may limit support on those versions to the most recent LTS version and the latest release.

Jaybird 3.0 is not modularized, but since Jaybird 3.0.3, it declares the automatic module name `org.firebirdsql.jaybird`.

[[jb3-firebird]]
==== Firebird support

Jaybird 3 supports Firebird 2.0 and higher, but is only tested with Firebird 2.5, 3.0 and 4.0. 

Formal support for Firebird 1.x has been dropped (although in general we expect the driver to work). 
The Type 2 and embedded server JDBC drivers use JNA to access the Firebird client or embedded library.

[[jb3-firebird3]]
===== Notes on Firebird 3 support

Jaybird 3.0.4 added support for wire protocol encryption and database encryption.

Jaybird 3 does not support the Firebird 3.0 zlib compression.

[[jb3-firebird4]]
===== Notes on Firebird 4 support

Jaybird 3 can connect and query Firebird 4.0.
Longer object names are supported. 

The new data types introduced in Firebird 4.0 are not supported.
Support for data types like `DECFLOAT` and `NUMERIC`/`DECIMAL` with precision higher than 18 will be introduced in Jaybird 4.

The Srp256 authentication plugin is supported ([.since]_Jaybird 3.0.5_), but the other SrpNNN plugins are not.

Jaybird 3 does not support the Firebird 4.0 zlib compression.

[[jb3-spec]]
==== Supported Specifications

Jaybird supports the following specifications:

[width="100%",cols="1,3",options="header",]
|=======================================================================
|Specification |Details
|JDBC 4.3 
|Jaybird supports most of JDBC 4.3, inasfar the features are required or supported by Firebird. 
It is not officially JDBC compliant, because we currently don't have access to the TCK.

|JCA 1.5 
|Jaybird provides an implementation of `javax.resource.spi.ManagedConnectionFactory` and related 
interfaces. CCI interfaces are not supported.

|JTA
|The driver provides an implementation of the `javax.transaction.xa.XAResource` interface via the JCA 
framework and a `javax.sql.XADataSource` implementation.

|=======================================================================

[[jb3-distribution]]
==== Distribution

The Jaybird driver has compile-time and run-time dependencies to JCA 1.5. 
Additionally, if the antlr-runtime classes are found in the class path, it is possible to use generated key retrieval.

[[jb3-distribution-package]]
===== Distribution package

The latest version of Jaybird can be downloaded from https://firebirdsql.org/en/jdbc-driver/

The following files can be found in the distribution package:

[cols="2,5",options="header",]
|=======================================================================
|File name |Description
| `jaybird-{jaybird3-full-version}.jar` 
| An archive containing the JDBC driver, the JCA connection manager, the Services API and event 
management classes.

| `jaybird-full-{jaybird3-full-version}.jar` 
| Same as above, but including the JCA 1.5 dependency.

| `lib/antlr-runtime-4.7.jar`
| Optional dependency, required if you want to use `getGeneratedKeys` support

| `lib/connector-api-1.5.jar`
| Required dependency;
part of `jaybird-full`, not necessary when deploying to a Java EE or Jakarta EE 8 or lower application server

| `lib/jna-4.4.0.jar`
| Optional dependency, required if you want to use Type 2 native, local or embedded protocols

|=======================================================================

[[jb3-distribution-maven]]
===== Maven

Alternatively, you can use maven to automatically download Jaybird and its dependencies.

Jaybird 3 is available from Maven central:

[horizontal]
groupId:: `org.firebirdsql.jdbc`
artifactId:: `jaybird-jdkXX` (where `XX` is `17` (Java 7) or `18` (Java 8))
version:: `{jaybird3-full-version}`

For example:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>jaybird-jdk18</artifactId>
  <version>{jaybird3-full-version}</version>
</dependency>
----

The Maven definition of Jaybird depends on antlr-runtime by default.

If your application is deployed to a Java EE or Jakarta EE 8 or lower application server, you will need to exclude the `javax.resource:connector-api` dependency, and add it as a provided dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>jaybird-jdk18</artifactId>
  <version>{jaybird3-full-version}</version>
  <exclusions>
    <exclusion>
      <groupId>javax.resource</groupId>
      <artifactId>connector-api</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>javax.resource</groupId>
  <artifactId>connector-api</artifactId>
  <version>1.5</version>
  <scope>provided</scope>
</dependency>
----

If you want to use Type 2 support (native, local or embedded), you need to 
explicitly include JNA as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>net.java.dev.jna</groupId>
  <artifactId>jna</artifactId>
  <version>4.4.0</version>
</dependency>
----

For native and local you can use the `org.firebirdsql.jdbc:fbclient` dependency to provide the client library.
See <<driver-native-maven>> for details.
