[[jb4]]
=== Jaybird 4

[[jb4-java]]
==== Java support

Jaybird 4 supports Java 7 (JDBC 4.1), Java 8 (JDBC 4.2), and Java 9 and higher (JDBC 4.3).

Given the limited support period for Java 9 and higher versions, we will limit support on those versions to the most recent LTS version and the latest release.
Currently that means we support Java 11 and Java 12.

Jaybird 4 provides libraries for Java 7, Java 8 and Java 11.
The Java 8 builds have the same source and all JDBC 4.3 related functionality and can be used on Java 9 and higher as well.

Jaybird 4 is not modularized, but all versions declare the automatic module name `org.firebirdsql.jaybird`.

[[jb4-firebird]]
==== Firebird support

Jaybird 4 supports Firebird 2.5 and higher.

Formal support for Firebird 2.0 and 2.1 has been dropped (although in general we expect the driver to work).
The Type 2 and embedded server JDBC drivers use JNA to access the Firebird client or embedded library.

[[jb4-firebird3]]
===== Notes on Firebird 3 support

Jaybird 4 does not (yet) support the Firebird 3 zlib compression.

[[jb4-firebird4]]
===== Notes on Firebird 4 support

Jaybird 4 does not support the protocol improvements of Firebird 4 like statement and session timeouts.
Nor does it implement the new batch protocol.

Jaybird time zone support uses functionality added after Firebird 4 beta 1 (4.0.0.1436), you will need version 4.0.0.1481 or later for the `timeZoneBind` connection property.

[[jb4-spec]]
==== Supported Specifications

Jaybird supports the following specifications:

[width="100%",cols="1,3",options="header",]
|=======================================================================
|Specification |Details
|JDBC 4.3 
|Jaybird supports most of JDBC 4.3, inasfar the features are required or supported by Firebird. 
It is not officially JDBC compliant, because we currently don't have access to the TCK.

|JCA 1.5 
|Jaybird provides an implementation of `javax.resource.spi.ManagedConnectionFactory` and related 
interfaces. CCI interfaces are not supported.

|JTA
|The driver provides an implementation of the `javax.transaction.xa.XAResource` interface via the JCA 
framework and a `javax.sql.XADataSource` implementation.

|=======================================================================

[[jb4-distribution]]
==== Distribution

The Jaybird driver has compile-time and run-time dependencies to JCA 1.5. 
Additionally, if the antlr-runtime classes are found in the class path, it is possible to use generated key retrieval.

[[jb4-distribution-package]]
===== Distribution package

The latest version of Jaybird can be downloaded from https://firebirdsql.org/en/jdbc-driver/

The following files can be found in the distribution package:

[cols="2,5",options="header",]
|=======================================================================
|File name |Description
| `jaybird-{jaybird4-full-version}.jar` 
| An archive containing the JDBC driver, the JCA connection manager, the Services API and event 
management classes.

| `jaybird-full-{jaybird4-full-version}.jar` 
| Same as above, but including the JCA 1.5 dependency.

| `lib/antlr-runtime-4.7.2.jar`
| Optional dependency, required if you want to use `getGeneratedKeys` support

| `lib/connector-api-1.5.jar`
| Required dependency; part of `jaybird-full`, not necessary when deploying to a Java EE application server

| `lib/jna-5.3.0.jar`
| Optional dependency, required if you want to use Type 2 native, local or embedded protocols

|=======================================================================

[[jb4-distribution-maven]]
===== Maven

Alternatively, you can use maven to automatically download Jaybird and its dependencies.

Jaybird 4 is available from Maven central:

Groupid: `org.firebirdsql.jdbc`, +
Artifactid: `jaybird-XX` (where `XX` is `jdk17`, `jdk18` or `java11`). +
Version: `{jaybird4-full-version}`

For example:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>jaybird-jdk18</artifactId>
  <version>{jaybird4-full-version}</version>
</dependency>
----

The Maven definition of Jaybird depends on antlr-runtime by default.

If your application is deployed to a Java EE application server, you will need to exclude the `javax.resource:connector-api` dependency, and add it as a provided dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>jaybird-jdk18</artifactId>
  <version>{jaybird4-full-version}</version>
  <exclusions>
    <exclusion>
      <groupId>javax.resource</groupId>
      <artifactId>connector-api</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>javax.resource</groupId>
  <artifactId>connector-api</artifactId>
  <version>1.5</version>
  <scope>provided</scope>
</dependency>
----

If you want to use Type 2 support (native, local or embedded), you need to explicitly include JNA as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>net.java.dev.jna</groupId>
  <artifactId>jna</artifactId>
  <version>5.3.0</version>
</dependency>
----

For native and local you can use the `org.firebirdsql.jdbc:fbclient` dependency to provide the client library.
See <<driver-native-maven>> for details.
