[[jb5]]
=== Jaybird 5

[[jb5-java]]
==== Java support

Jaybird 5 supports Java 8 (JDBC 4.2), and Java 9 and higher (JDBC 4.3 - 4.5).

Given the limited support period for Java 9 and higher versions, we limit support to Java 8, 11, 17 and the LTS versions after Java 17 and the latest Java release.
Currently, that means we support Java 8, Java 11, Java 17, Java 21, Java 25, and Java 26.

[NOTE]
====
Jaybird 5 will be the last version to support Java 8 and 11.
Jaybird 6 will use Java 17 as the baseline (minimum) version.
We highly recommend upgrading to Java 17 or higher.

Jaybird 5 will serve as a "`long-term support`" version for Java 8 and 11, with maintenance releases at least until the release of Jaybird 7.

It is possible future maintenance releases of Jaybird 5 stop expanding Java support to include newly released Java versions.
A reason can be -- but is not limited to -- if adding support for a newer Java version results in breaking support for Java 8 or Java 11, or JDBC 4.2 or JDBC 4.3, or require changes that would limit testability on those versions.
We may also simply stop expanding Java support to limit the number of versions we need to test.
====

Jaybird 5 provides libraries for Java 8 and Java 11.
The Java 8 builds have all JDBC 4.3 related functionality and can be used on Java 9 and higher as well, but the Java 11 version has additional features, like the ChaCha wire encryption.

Jaybird 5 is not modularized, but all versions declare the automatic module name `org.firebirdsql.jaybird`.

[[jb5-firebird]]
==== Firebird support

Jaybird 5 supports Firebird 2.5, Firebird 3.0, Firebird 4.0, and Firebird 5.0.

.No promises on Firebird 6.0 support
[WARNING]
====
Firebird 6.0 is still in development, and includes changes -- like schema support -- that impact Jaybird.

As a result -- at this time -- we make no promises on the support for Firebird 6.0 by Jaybird 5.
We may delay support for Firebird 6.0 until Jaybird 7, or we may improve support during maintenance releases of Jaybird 5 and/or Jaybird 6.
====

Jaybird 5 is the last version to support Firebird 2.5.

Formal support for Firebird 2.0 and 2.1 has been dropped, and some things may no longer work (especially `DatabaseMetaData` methods), if features of Firebird 2.5 have been used.
The Type 2 and embedded server JDBC drivers use JNA to access the Firebird client or embedded library.

[[jb5-firebird3]]
===== Notes on Firebird 3.0 support

Jaybird 5 supports the Firebird 3.0 and higher zlib compression.

[[jb5-firebird4]]
===== Notes on Firebird 4.0 support

Jaybird 5 supports the protocol improvements of Firebird 4.0 for statement timeouts and server-side batch execution.
Jaybird 5 does not support sending blobs as part of batch execution.

Jaybird 5 only supports the ChaCha wire encryption plugin using the Java 11 version of the driver.
Jaybird 5 does not support the ChaCha64 wire encryption plugin.
Support for ChaCha64 will be added in Jaybird 6.

See also <<jb5-firebird3>>

[[jb5-firebird5]]
===== Notes on Firebird 5.0 support

Jaybird 5 supports Firebird 5.0 server-side scrollable cursors and multi-row `RETURNING`.

See also <<jb5-firebird4>>

[[jb5-spec]]
==== Supported Specifications

Jaybird 5 supports the following specifications:

[width="100%",cols="1,3",options="header",]
|===
|Specification |Details

|JDBC 4.5
|All JDBC 4.5 methods for features supported by Firebird, except arrays.

|JDBC 4.4
|If a security manager is available, the driver still performs `SQLPermission` checks.

|JDBC 4.3 
|All JDBC 4.3 methods for features supported by Firebird, except arrays.

|JDBC 4.2
|All JDBC 4.2 methods for features supported by Firebird, except arrays.

|JTA
|The driver provides an implementation of the `javax.transaction.xa.XAResource` interface via a `javax.sql.XADataSource` implementation.

|===

As we don't have access to the JDBC TCKs, Jaybird is not officially JDBC compliant.

[[jb5-distribution]]
==== Distribution

Jaybird has no required runtime dependencies.
For native or embedded connections, JNA {jaybird5-jna-version} needs to be on the class path.

[[jb5-distribution-package]]
===== Distribution package

The latest version of Jaybird can be downloaded from https://firebirdsql.org/en/jdbc-driver/

The following files can be found in the distribution package:

[cols="2,5",options="header",]
|===
|File name |Description
| `jaybird-{jaybird5-template-version}.jar`
| An archive containing the JDBC driver, the Services API and event management classes.
Where `<java>` is either `java11` or `java8`.

| `lib/jna-{jaybird5-jna-version}.jar`
| Optional dependency, required if you want to use Type 2 native, or embedded protocols

|===

[[jb5-distribution-maven]]
===== Maven

Alternatively, you can use maven to automatically download Jaybird and its dependencies.

Jaybird 5 is available from Maven central:

[horizontal]
groupId:: `org.firebirdsql.jdbc`
artifactId:: `jaybird`
version:: `{jaybird5-template-version}` (where `<java>` is either `java11` or `java8`)

For example:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>jaybird</artifactId>
  <version>{jaybird5-example-version}</version>
</dependency>
----

If you want to use Type 2 support (native or embedded), you need to explicitly include JNA as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>net.java.dev.jna</groupId>
  <artifactId>jna</artifactId>
  <version>{jaybird5-jna-version}</version>
</dependency>
----

For native connections you can use the `org.firebirdsql.jdbc:fbclient` dependency to provide the client library.
See <<driver-native-maven>> for details.
