[[jb6]]
=== Jaybird 6

[[jb6-java]]
==== Java support

Jaybird 6 supports Java 17 and higher (JDBC 4.3).

Given the limited support period for non-LTS Java versions, we limit support to Java 17 and the most recent LTS version after Java 17, and the latest Java release.
Currently, that means we support Java 17, Java 21, and Java 24.

Jaybird 6 provides libraries compiled against Java 17, which also work on higher Java versions.

Jaybird 6 is modularized, and provides the following modules:

`org.firebirdsql.jaybird`::
main Jaybird driver (artifact `org.firebirdsql.jdbc:jaybird`)

`org.firebirdsql.jaybird.chacha64`::
ChaCha64 wire encryption implementation (artifact `org.firebirdsql.jdbc:chacha64-plugin`)

`org.firebirdsql.jna`::
native and embedded protocol implementation using JNA (artifact `org.firebirdsql.jdbc:jaybird-native`)

[[jb6-firebird]]
==== Firebird support

Jaybird 6 supports Firebird 3.0, Firebird 4.0, and Firebird 5.0.

Jaybird 6 will -- by default -- not connect to Firebird 2.5 or older.
To connect to earlier versions, unsupported protocols have to be enabled explicitly, see <<ref-enable-protocol>> for details.

Formal support for Firebird 2.5 has been dropped, and some things may no longer work (especially `DatabaseMetaData` methods), if features of Firebird 3.0 have been used.
The Type 2 and embedded server JDBC drivers require a separate artifact, `jaybird-native`, and JNA to access the Firebird client or embedded library.

[[jb6-firebird3]]
===== Notes on Firebird 3.0 support

Jaybird 6 supports the Firebird 3.0 and higher zlib compression.

Jaybird 6 supports the Arc4 wire encryption plugin out-of-the-box.

[[jb6-firebird4]]
===== Notes on Firebird 4.0 support

Jaybird 6 supports the protocol improvements of Firebird 4.0 for statement timeouts and server-side batch execution.
Jaybird 6 does not support sending blobs as part of batch execution.

Jaybird 6 supports the Arc4 and ChaCha wire encryption plugin out-of-the-box.
To support the ChaCha64 wire encryption plugin, the artifact `org.firebirdsql.jdbc:chacha64-plugin` has to be added to the classpath.

See also <<jb6-firebird3>>

[[jb6-firebird5]]
===== Notes on Firebird 5.0 support

Jaybird 6 supports Firebird 5.0 server-side scrollable cursors and multi-row `RETURNING`.

See also <<jb6-firebird4>>

[[jb6-spec]]
==== Supported Specifications

Jaybird 6 supports the following specifications:

[width="100%",cols="1,3",options="header",]
|===
|Specification |Details

|JDBC 4.4
|If a security manager is available, the driver still performs `SQLPermission` checks.

|JDBC 4.3 
|Jaybird supports most of JDBC 4.3, in as far the features are required or supported by Firebird.
It is not officially JDBC compliant, because we currently don't have access to the TCK.

|JTA
|The driver provides an implementation of the `javax.transaction.xa.XAResource` interface via a `javax.sql.XADataSource` implementation.

|===

[[jb6-distribution]]
==== Distribution

Jaybird has no required runtime dependencies.

For native or embedded connections, the `jaybird-native` artifact and `jna-jpms` {jaybird6-jna-version} need to be on the classpath.

For ChaCha64 wire encryption, the `chacha64-plugin` artifact and `bcprov-jdk18on` {jaybird6-bc-version} (Bouncy Castle JCE provider) need to be on the classpath.

[[jb6-distribution-package]]
===== Distribution package

The latest version of Jaybird can be downloaded from https://firebirdsql.org/en/jdbc-driver/

The following files can be found in the distribution package:

[cols="2,5",options="header",]
|===
|File name |Description
|`jaybird-{jaybird6-full-version}.jar`
|The main JDBC driver, the Services API and event management classes.
Provides only pure Java connections.

|`chacha64-plugin-{jaybird6-full-version}.jar`
|Optional dependency, support for the ChaCha64 wire encryption for pure Java connections.

|`lib/bcprov-jdk18on-{jaybird6-bc-version}.jar`
|Optional dependency, required for the ChaCha64 support (with `chacha64-plugin`)

|`jaybird-native-{jaybird6-full-version}.jar`
|Options dependency, support for native and embedded connections.
Requires `lib/jna-jpms-{jaybird6-jna-version}.jar`.

|`lib/jna-jpms-{jaybird6-jna-version}.jar`
|Optional dependency, required if you want to use Type 2 native, or embedded protocols (with `jaybird-native`)

|===

[[jb6-distribution-maven]]
===== Maven

Alternatively, you can use Maven to automatically download Jaybird and its dependencies.

Jaybird 6 is available from Maven central:

[horizontal]
groupId:: `org.firebirdsql.jdbc`
artifactId:: `jaybird`
version:: `{jaybird6-full-version}`

For example:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>jaybird</artifactId>
  <version>{jaybird6-full-version}</version>
</dependency>
----

If you want to use ChaCha64 wire encryption, you need to explicitly include `chacha64-plugin` as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>chacha64-plugin</artifactId>
  <version>{jaybird6-full-version}</version>
</dependency>
----

If you want to use Type 2 support (native or embedded), you need to explicitly include `jaybird-native` as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>jaybird-native</artifactId>
  <version>{jaybird6-full-version}</version>
</dependency>
----

In addition, for native connections you can use the `org.firebirdsql.jdbc:fbclient` dependency to provide the client library (`fbclient.dll`/`libfbclient.so`) on Windows and Linux.
See <<driver-native-maven>> for details.
