[[connectionproperties]]
[appendix]
== Extended connection properties

Jaybird has a number of connection properties that can be used to configure a connection.

This appendix provides a list of most connection properties and a short explanation to each of them.
The properties listed below are usable as JDBC connection properties.

The properties marked as _boolean property_ can be included in the JDBC URL with values `true`, but also without a value, or with an empty value.
For readability, we suggest that you only specify these properties explicitly when you want to enable them, and if you do, to use explicit values like `true`.

In Jaybird 4 and earlier, the default for all _boolean_ properties is `false`. +
In Jaybird 5 and higher, the default of _boolean_ properties varies (but unless explicitly mentioned, the default is `false`).

A subset of these properties is also exposed in the `javax.sql.DataSource` implementations in Jaybird.
When using data sources, unexposed properties can be set using `setNonStandardProperty`.

[[connectionproperties-auth]]
=== Authentication and security properties

[cols="1,2",options="header",]
|===
|Connection property (+ aliases) 
|Explanation

a|`user` +
`userName`, `user_name`, `isc_dpb_user_name`
|Name of the user for the connection.

a|`password` +
`isc_dpb_password`
|Password corresponding to the specified user.

a|`roleName` +
`sqlRole`, `sql_role_name`, `isc_dpb_sql_role_name`
|Name of the SQL role for the specified connection.

a|`authPlugins` +
`auth_plugin_list`
|Jaybird specific property ([.since]_Jaybird 4_).
The comma-separated list of authentication plugins to try.
See <<ref-auth-plugins>> for more information. +
Default: `Srp256,Srp`

a|`wireCrypt`
a|Jaybird specific property ([.since]_Jaybird 3.0.4_).
Allowed values: `DEFAULT`, `ENABLED`, `REQUIRED`, `DISABLED` (case insensitive).
Configures Firebird 3.0 wire encryption behaviour.
See <<ref-wirecrypt>> for more information. +
Default: `DEFAULT`.

a|`dbCryptConfig`
|Jaybird specific property ([.since]_Jaybird 3.0.4_).
Configures Firebird 3.0 database encryption support.
See <<ref-dbcrypt>> for more information.

a|`processId` +
`process_id`, `isc_dpb_process_id`
|Specifies the process id reported to Firebird.
See <<ref-processinfo>> for more information.

a|`processName` +
`process_name`, `isc_dpb_process_name`, `ApplicationName` ([.since]_Jaybird 6_), `applicationName` ([.since]_Jaybird 6_)
|Specifies the process name reported to Firebird.
See <<ref-processinfo>> for more information.
|===

[[connectionproperties-other]]
=== Other properties

[cols="1,2",options="header",]
|===
|Connection property (+ aliases) 
|Explanation

a|`encoding` +
`lc_ctype`, `isc_dpb_lc_ctype`
a|Character encoding for the connection using the Firebird character set name.
This property tells the database server the encoding in which it expects character content.
For a list of the available encodings see <<Available Encodings>>. +
Default: `NONE` (unless `charSet` is specified).

a|`charSet` +
`localEncoding`
|Jaybird specific property.
Character set for the connection using Java character set name.
Similar to the previous property, however instead of Firebird-specific name allows using a Java character set name.

a|`sqlDialect` +
`dialect`, `sql_dialect`, `isc_dpb_sql_dialect`
a|SQL dialect, can be 1, 2 and 3. +
Default: 3

a|`defaultHoldable` +
`defaultResultSetHoldable`
|Jaybird specific property.
Boolean property.
Set result sets to be holdable by default.
A workaround for applications with incorrect assumptions on result sets in auto-commit mode.
See <<ref-defaultholdable>> for more information.

a|`useFirebirdAutocommit`
|Jaybird specific property.
Boolean property.
Enable experimental feature to use Firebird auto-commit for JDBC auto-commit mode.
See <<ref-firebirdautocommit>> for more information.

a|`generatedKeysEnabled`
|Jaybird specific property ([.since]_Jaybird 4_).
Configure generated keys support behaviour.
See <<ref-generatedkeys-config>> for more information.

a|`isolation` +
`defaultIsolation`
a|Jaybird specific property.
Specify the default transaction isolation level.
Accepted values are: `TRANSACTION_NONE`, `TRANSACTION_READ_UNCOMMITTED`, `TRANSACTION_READ_COMMITTED`, `TRANSACTION_REPEATABLE_READ`, `TRANSACTION_SERIALIZABLE` (case sensitive). 
Although `TRANSACTION_NONE` and `TRANSACTION_READ_UNCOMMITTED` are allowed values, these behave the same as `TRANSACTION_READ_COMMITTED`. +
Default: `TRANSACTION_READ_COMMITTED`

a|`socketBufferSize` +
`socket_buffer_size`
|Jaybird specific property. 
Tells Jaybird Type 4 driver the size of the socket buffer.
Should be used on the systems where default socket buffer provided by JVM is not correct.

a|`blobBufferSize` +
`blob_buffer_size`
|Jaybird specific property. 
Tells the driver the size of the buffer that is used to transfer BLOB content.
It is recommended to keep the value equal to `n * <database page size>` (and preferably also socket buffer size).

a|`soTimeout`
|Jaybird specific property.
Socket blocking timeout in milliseconds.
Only has effect on Type 4 (pure Java) connections.

a|`connectTimeout` +
`connect_timeout`, `isc_dpb_connect_timeout`
|Connect timeout in seconds.
For the Java wire protocol the connect timeout will detect unreachable hosts. 
In the JNI/JNA implementation (native protocol) the connect timeout works as the DPB item `isc_dpb_connect_timeout` which only works after connecting to the server for the `op_accept` phase of the protocol. 
This means that -- for the native protocol -- the connect timeout will not detect unreachable hosts within the timeout.

a|`wireCompression`
|Jaybird specific property ([.since]_Jaybird 4_ [.since]_Firebird 3.0_).
Boolean property.
Set property to `true` to enable zlib wire compression.
See <<ref-wirecompression>> for more information.

a|`columnLabelForName`
|Jaybird specific property.
Boolean property.
Set property to `true` for backwards compatible behaviour (`getColumnName()` returns the column label). 
Don't set the property or set it to `false` for JDBC-compliant behaviour (recommended).

a|`useStreamBlobs` +
`use_stream_blobs`
a|Jaybird specific property.
Boolean property.
Tells the driver to create stream BLOBs. +
Default: Jaybird 5 and higher: `true` (stream BLOBS) +
Jaybird 4 and earlier: `false` (segmented BLOBs)

a|`ignoreProcedureType`
|Jaybird specific property ([.since]_Jaybird 3.0.6_).
Boolean property.
Set property to `true` to disable usage of procedure type metadata to decide to use `SELECT` for selectable procedure instead of `EXECUTE PROCEDURE`.
See <<ref-callable-ignore-proctype>> for more information.

a|`scrollableCursor`
a|Jaybird specific property ([.since]_Jaybird 5_ [.since]_Firebird 5.0_).
Allowed values: `EMULATED`, `SERVER` (case-insensitive)
Configures use of server-side scrollable cursors (Firebird 5.0 and higher, pure Java connections only).
See <<ref-scrollable-cursor>> for more information. +
Default: `EMULATED`

a|`useServerBatch`
a|Jaybird specific property ([.since]_Jaybird 5_ [.since]_Firebird 4.0_).
Boolean property.
Value `true` enable server-side batch if available (Firebird 4.0 and higher, pure Java connection only).
Set to `false` to always use emulated batch updates.
See <<ref-batch-use-server-batch>> for more information. +
Default value: `true`

a|`serverBatchBufferSize`
a|Jaybird specific property ([.since]_Jaybird 5_ [.since]_Firebird 4.0_).
Size in bytes of the server-side batch buffer.
Value `< 0` -- server-side default, `0` -- server-side maximum, `> 0` -- size (capped at server-side maximum)
See <<ref-batch-server-batch-buffer-size>> for more information. +
Default value: `0`

a|`dataTypeBind` +
`set_bind`
|Defines data type bind from one type to a different type. ([.since]_Jaybird 3.0.9_ [.since]_Firebird 4.0_)
Multiple bind definitions are separated by semicolons.
When used in a JDBC url, the semicolon must be escaped using `%3B`.
See <<ref-datatypebind>> for more information.

a|`sessionTimeZone`
| Configures the session time zone. ([.since]_Jaybird 3.0.6_)
In Jaybird 3, only configures the Firebird 4 server-side session time zone.
In Jaybird 4, also configures the time zone used for legacy datetime conversion on all Firebird versions.
See <<ref-datetime-sessiontimezone>> for more information. +
Default: not set (Jaybird 3 and earlier), or the JVM default time zone ([.since]_Jaybird 4_)

a|`decfloatRound` +
`decfloat_round`
|Defines server-side rounding behaviour for `DECFLOAT` data types ([.since]_Jaybird 4_ [.since]_Firebird 4.0_)
Possible values: `ceiling`, `up`, `half_up` (default), `half_even`, `half_down`, `down`, `floor`, `reround`
See <<ref-decfloat-traps-round>> for more information.

a|`decfloatTraps` +
`decfloat_traps`
|Defines server-side error behaviour for `DECFLOAT` data types ([.since]_Jaybird 4_ [.since]_Firebird 4.0_)
Comma-separated list with options: `Division_by_zero` (default), `Inexact`, `Invalid_operation` (default), `Overflow` (default), `Underflow`
See <<ref-decfloat-traps-round>> for more information.

a|`useStandarUdf` +
`use_standard_udf`
|Jaybird specific property ([.until]_Jaybird 5_).
Boolean property. 
Tells the JDBC driver to assume that standard UDF library is registered in the database when converting escaped function calls. 
With recent versions of Firebird, it is advisable to not specify this property and rely on the built-in functions instead.
See <<jdbcescape>> for more information.

a|`timestampUsesLocalTimezone` 
|Jaybird specific property ([.until]_Jaybird 6_).
Boolean property.
Changes how `getTime`/`getTimestamp` methods accepting a `java.util.Calendar` apply the calendar offset in calculations.

a|`num_buffers` +
`isc_dpb_num_buffers`
|Number of database pages that will be cached.
Overrides server or database default for this specific connection.
Use with care to avoid using an excessive amount of memory.

a|`set_db_readonly` +
`isc_dpb_set_db_readonly`
|Boolean property.
Set the database into read-only state.

a|`set_db_sql_dialect` +
 `isc_dpb_set_db_sql_dialect`
|Set the SQL dialect of the database.

a|`set_db_charset` +
`isc_dpb_set_db_charset`
|Set the default character set of the database.

a|`noResultSetTracking`
|Jaybird specific property. ([.until]_Jaybird 4_)
Boolean property.
Unused since at least Jaybird 2.2, removed in Jaybird 4.

a|`useTranslation` +
`mapping_path`
|Jaybird specific property ([.until]_Jaybird 4_).
Deprecated, removed in Jaybird 4.
This allows mapping of characters to be overridden (see `translation/hpux.properties` in Jaybird jar for example).
Value is the path to a mapping properties file.

a|`enableProtocol`
|Jaybird specific property ([.since]_Jaybird 6_).
Enable unsupported protocol versions, if available.
Comma-separated list of protocol versions to enable in addition to the supported protocol versions.
The value `"*"` will enable all available protocol versions.
See <<ref-enable-protocol>> for more information.

a|`parallelWorkers` +
`parallel_workers`, `isc_dpb_parallel_workers`
|The number of parallel workers to use ([.since]_Jaybird 5.0.2_ [.since]_Firebird 5.0_)

a|`nativeLibraryPath`
a|Jaybird specific property ([.since]_Jaybird 6_).

Specifies a directory to try and load the client library for native (`fbclient`) or embedded (`fbembed` or `fbclient`) connections.
If a file name is specified instead of a directory name, the parent directory will be used.

[CAUTION]
====
This property only works for the *first* native or embedded connection (to a database or service) created inside a JVM.
Any subsequent connection uses the library that was loaded by the first connection.
====

a|`useCatalogAsPackage`
a|Jaybird specific property ([.since]_Jaybird 6_ [.since]_Firebird 3.0_).
Boolean property.
Enables support for reporting database metadata information on packages, and functions and stored procedures in packages.
See <<ref-catalog-as-package>> for more information.

|===

In addition, Jaybird allows using arbitrary Database Parameters Block entries as connection properties (provided they are defined in Jaybird's `DpbItems` and `SpbItems` ([.since]_Jaybird 5_), or `ISCConstants` ([.until]_Jaybird 5_)).
The current Firebird API has over 100 DPB parameters, however only few of them are interesting for regular users.
If a DPB item called `isc_dpb_XXX` exists, then Jaybird allows these to be specified as `isc_dpb_XXX` and `XXX`. 
By default properties are mapped as string DPB items. 
If a DPB item requires another type, it will need to be explicitly defined in Jaybird.

[[connectionproperties-isolation-levels]]
=== Transaction isolation levels

It is possible to redefine the transaction isolation levels through connection properties.

[cols="1,2",options="header",]
|===
|Connection property
|Explanation

a|`TRANSACTION_READ_COMMITTED`
a|Specify the definition of transaction isolation level `READ_COMMITTED`. +
Default: `isc_tpb_read_committed,isc_tpb_rec_version,isc_tpb_write,isc_tpb_wait`

a|`TRANSACTION_REPEATABLE_READ`
|Specify the definition of transaction isolation level `REPEATABLE_READ`. +
Default: `isc_tpb_concurrency,isc_tpb_write,isc_tpb_wait`

a|`TRANSACTION_SERIALIZABLE`
|Specify the definition of transaction isolation level `TRANSACTION_SERIALIZABLE`. +
Default: `isc_tpb_consistency,isc_tpb_write,isc_tpb_wait`
|===

For data sources, this feature is exposed using a definition properties file and the `setTpbMapping` property.
See <<transactions-isolation-levels>> for more information.
