[[connectionproperties]]
[appendix]
== Extended connection properties

Jaybird has a number of connection properties that can be used to configure a connection.

This appendix provides a list of most connection properties and a short explanation to each of them.
The properties listed below are usable as JDBC connection properties.

The properties marked as _boolean property_ can be included in the JDBC URL with values `true`, but also without a value, or with an empty value.
The default for these properties is always `false`.
For readability we suggest that you only specify these properties explicitly when you want to enable them, and if you do, to use explicit value `true`.

A subset of these properties is also exposed in the `javax.sql.DataSource` implementations in Jaybird.
When using data sources, unexposed properties can be set using `setNonStandardProperty`.

[[connectionproperties-auth]]
=== Authentication and security properties

[cols="1,2",options="header",]
|=======================================================================
|Connection property (+ aliases) 
|Explanation

a|`user` +
`userName`, `user_name`, `isc_dpb_user_name`
|Name of the user for the connection.

a|`password` +
`isc_dpb_password`
|Password corresponding to the specified user.

a|`roleName` +
`sqlRole`, `sql_role_name`, `isc_dpb_sql_role_name`
|Name of the SQL role for the specified connection.

a|`authPlugins` +
`auth_plugin_list`
|Jaybird specific property ([.since]_Jaybird 4_).
Specifies the list of authentication plugins to try.
**TODO** Improve documentation (define reference section based on Jaybird 4 release notes)

a|`wireCrypt`
a|Jaybird specific property ([.since]_Jaybird 3.0.4_).
Allowed values: `DEFAULT`, `ENABLED`, `REQUIRED`, `DISABLED` (case insensitive).
Configures Firebird 3 wire encryption behaviour.
See <<ref-wirecrypt>> for more information. +
Default: `DEFAULT`.

a|`dbCryptConfig`
|Jaybird specific property ([.since]_Jaybird 3.0.4_).
Configures Firebird 3 database encryption support.
See <<ref-dbcrypt>> for more information.

a|`process_id` +
`processId` ([.since]_Jaybird 3_), `isc_dpb_process_id`
|Specifies the process id reported to Firebird.
See <<ref-processinfo>> for more information.

a|`process_name` +
`processName` ([.since]_Jaybird 3_), `isc_dpb_process_name`
|Specifies the process name reported to Firebird.
See <<ref-processinfo>> for more information.
|=======================================================================

[[connectionproperties-other]]
=== Other properties

[cols="1,2",options="header",]
|=======================================================================
|Connection property (+ aliases) 
|Explanation

a|`encoding` +
`lc_ctype`, `isc_dpb_lc_ctype`
a|Character encoding for the connection using the Firebird character set name.
This property tells the database server the encoding in which it expects character content.
For a list of the available encodings see <<Available Encodings>>. +
Default: `NONE` (unless `charSet` is specified).

a|`charSet` +
`localEncoding`
|Jaybird specific property.
Character set for the connection using Java character set name.
Similar to the previous property, however instead of Firebird-specific name allows using a Java character set name.

a|`sqlDialect` +
`dialect` ([.since]_Jaybird 3_), `sql_dialect`, `isc_dpb_sql_dialect`
a|SQL dialect, can be 1, 2 and 3. +
Default: 3 (in Jaybird 2.2 and earlier the default is a combination of dialect 3 and the actual database dialect)

a|`defaultHoldable` +
`defaultResultSetHoldable`
|Jaybird specific property.
Boolean property.
Set result sets to be holdable by default.
A workaround for applications with incorrect assumptions on result sets in auto-commit mode.
See <<ref-defaultholdable>> for more information.

a|`useFirebirdAutocommit`
|Jaybird specific property ([.since]_Jaybird 2.2.9_).
Boolean property.
Enable experimental feature to use Firebird auto-commit for JDBC auto-commit mode.
See <<ref-firebirdautocommit>> for more information.

a|`generatedKeysEnabled`
|Jaybird specific property ([.since]_Jaybird 4_).
Configure generated keys support behaviour.
**TODO** Improve documentation (define reference section based on Jaybird 4 release notes)

a|`isolation` +
`defaultIsolation`
a|Jaybird specific property.
Specify the default transaction isolation level.
Accepted values are: `TRANSACTION_NONE`, `TRANSACTION_READ_UNCOMMITTED`, `TRANSACTION_READ_COMMITTED`, `TRANSACTION_REPEATABLE_READ`, `TRANSACTION_SERIALIZABLE` (case sensitive). 
Although `TRANSACTION_NONE` and `TRANSACTION_READ_UNCOMMITTED` are allowed values, these behave the same as `TRANSACTION_READ_COMMITTED`. +
Default: `TRANSACTION_READ_COMMITTED`

a|`socketBufferSize` +
`socket_buffer_size`
|Jaybird specific property. 
Tells Jaybird Type 4 driver the size of the socket buffer.
Should be used on the systems where default socket buffer provided by JVM is not correct.

a|`blobBufferSize` +
`blob_buffer_size`
|Jaybird specific property. 
Tells the driver the size of the buffer that is used to transfer BLOB content.
It is recommended to keep the value equal to `n * <database page size>` (and preferably also socket buffer size).

a|`soTimeout`
|Jaybird specific property.
Socket blocking timeout in milliseconds.
Only has effect on Type 4 (pure Java) connections.

a|`connectTimeout` +
`connect_timeout`, `isc_dpb_connect_timeout`
|Connect timeout in seconds ([.since]_Jaybird 2.2.2_).
For the Java wire protocol the connect timeout will detect unreachable hosts. 
In the JNI/JNA implementation (native protocol) the connect timeout works as the DPB item `isc_dpb_connect_timeout` which only works after connecting to the server for the `op_accept` phase of the protocol. 
This means that – for the native protocol – the connect timeout will not detect unreachable hosts within the timeout.

a|`columnLabelForName`
|Jaybird specific property ([.since]_Jaybird 2.2.1_).
Boolean property.
Set property to `true` for backwards compatible behaviour (`getColumnName()` returns the column label). 
Don't set the property or set it to `false` for JDBC-compliant behaviour (recommended).

a|`useStreamBlobs` +
`use_stream_blobs`
|Jaybird specific property. 
Boolean property.
Tells the driver to create stream BLOBs. 
By default segmented BLOBs are created.

a|`ignoreProcedureType`
|Jaybird specific property ([.since]_Jaybird 3.0.6_).
Boolean property.
Set property to `true` to disable usage of procedure type metadata to decide to use `SELECT` for selectable procedure instead of `EXECUTE PROCEDURE`.
**TODO** Improve documentation (define reference section based on Jaybird 3.0.6 release notes)

a|`octetsAsBytes`
|Jaybird specific property. ([.since]_Jaybird 2.1.1_ [.until]_Jaybird 3_)
Boolean property.
Unused since Jaybird 3, will be removed in Jaybird 4.
Makes `ResultSet.getObject` for `(VAR)CHAR CHARACTER SET OCTETS` return `byte[]` instead of `String`.
Since Jaybird 3, this is the default behaviour (with further enhancements to identify these columns as JDBC `(VAR)BINARY`).
See <<ref-binary>> for more information.

a|`decfloatBind`
|Instructs Firebird to convert columns and parameters of type `DECFLOAT` to a different type. ([.since]_Jaybird 3.0.6_ [.since]_Firebird 4_)
Accepted values are: `native`, `char` or `character`, `double precision`, `bigint, n` where `n` is the target scale to convert to a `NUMERIC(18,n)`.
See <<ref-decfloat-prop-decfloat-bind>> for more information.

a|`useStandarUdf` +
`use_standard_udf`
|Jaybird specific property.
Boolean property. 
Tells the JDBC driver to assume that standard UDF library is registered in the database when converting escaped function calls. 
With recent versions of Firebird, it is advisable to not specify this property and rely on the built-in functions instead.
See <<jdbcescape>> for more information.

a|`timestampUsesLocalTimezone` 
|Jaybird specific property.
Boolean property.
Changes how `getTime`/`getTimestamp` methods accepting a `java.util.Calendar` apply the calendar offset in calculations. 
**TODO**: Improve documentation on exact effect

a|`num_buffers` +
`isc_dpb_num_buffers`
|Number of database pages that will be cached.
Overrides server or database default for this specific connection.
Use with care to avoid using an excessive amount of memory.

a|`set_db_readonly` +
`isc_dpb_set_db_readonly`
|Boolean property.
Set the database into read-only state.

a|`set_db_sql_dialect` +
 `isc_dpb_set_db_sql_dialect`
|Set the SQL dialect of the database.

a|`set_db_charset` +
`isc_dpb_set_db_charset`
|Set the default character set of the database.

a|`paranoia_mode` +
`isc_dpb_paranoia_mode`
|Jaybird specific property. 
Boolean property.
Unused since Jaybird 2.2.
Tells the driver to throw exception in situations not covered by the specification.

a|`noResultSetTracking`
|Jaybird specific property.
Boolean property.
Unused since at least Jaybird 2.2, will be removed in Jaybird 4.

a|`useTranslation` +
`mapping_path`
|Jaybird specific property.
Deprecated, will be removed in Jaybird 4.
This allows mapping of characters to be overridden (see `translation/hpux.properties` in Jaybird jar for example).
Value is the path to a mapping properties file.
|=======================================================================

In addition, Jaybird allows using arbitrary Database Parameters Block entries as connection properties (provided they are defined in Jaybird's `org.firebirdsql.gds.ISCConstants`).
The current Firebird API has almost 90 DPB parameters, however only few of them are interesting for regular users.
If a DPB item called `isc_dpb_XXX` exists, then Jaybird allows these to be specified as `isc_dpb_XXX` and `XXX`. 
By default properties are mapped as string DPB items. 
If a DPB item requires another type, it will need to be explicitly defined in Jaybird.

[[connectionproperties-isolation-levels]]
=== Transaction isolation levels

It is possible to redefine the transaction isolation levels through connection properties.

[cols="1,2",options="header",]
|=======================================================================
|Connection property
|Explanation

a|`TRANSACTION_READ_COMMITTED`
a|Specify the definition of transaction isolation level `READ_COMMITTED`. +
Default: `isc_tpb_read_committed,isc_tpb_rec_version,isc_tpb_write,isc_tpb_wait`

a|`TRANSACTION_REPEATABLE_READ`
|Specify the definition of transaction isolation level `REPEATABLE_READ`. +
Default: `isc_tpb_concurrency,isc_tpb_write,isc_tpb_wait`

a|`TRANSACTION_SERIALIZABLE`
|Specify the definition of transaction isolation level `TRANSACTION_SERIALIZABLE`. +
Default: `isc_tpb_consistency,isc_tpb_write,isc_tpb_wait`
|=======================================================================

For data sources, this feature is exposed using a definition properties file and the `setTpbMapping` property.
See <<transactions-isolation-levels>> for more information.
