[[ref-generatedkeys]]
=== Generated keys retrieval

Jaybird provides support for the `getGeneratedKeys()` JDBC feature for `Statement` and `PreparedStatement`.
This feature can be used to retrieve the generated ids (and other columns) from DML statements.

This feature is available for `Connection.prepareStatement`, and `Statement.execute`, `Statement.executeUpdate` and `Statement.executeLargeUpdate` ([.since]_Java 8/JDBC 4.2_)

There are four distinct use-cases:

. Methods accepting an `int` parameter with values of `Statement.NO_GENERATED_KEYS` and `Statement.RETURN_GENERATED_KEYS`, see <<ref-generatedkeys-RETURN-GENERATED-KEYS>>,
. Methods accepting an `int[]` parameter with column indexes, see <<ref-generatedkeys-column-index>>.
. Methods accepting a `String[]` parameter with column names, see <<ref-generatedkeys-column-name>>.
. Providing a query already containing a `RETURNING` clause to any of these methods.
+
In this case all the previous cases are ignored and the query is executed as is.
It is possible to retrieve the result set using `getGeneratedKeys()`.

.ANTLR Runtime required in Jaybird 4.0.7 and earlier
****
For Jaybird 4.0.7 and earlier, the generated keys functionality will only be available if the ANTLR runtime classes are on the classpath.
Except for calling methods with `NO_GENERATED_KEYS`, absence of the ANTLR runtime will throw `FBDriverNotCapableException`.

TIP: The required ANTLR runtime version depends on the Jaybird version, check the release notes of your version for details.

Since Jaybird 4.0.8, Jaybird uses a custom parser and no longer requires ANTLR for the generated keys feature.
If you previously relied on absence of ANTLR to disable generated keys support, the generated keys feature can be disabled by setting <<ref-generatedkeys-config,connection property `generatedKeysEnabled`>> to `disabled`.
****

This functionality is available for `INSERT`, `UPDATE`, `UPDATE OR INSERT` and `DELETE`, and for `MERGE` ([.since]_Firebird 3.0_).

[NOTE] 
====
Generated keys retrieval modifies the statement to add a `RETURNING`-clause.
Firebird 4.0 and earlier only support `RETURNING` for DML operations that affect a single row.
Attempting to use generated keys retrieval with a statement that affects multiple rows will yield the error _"multiple rows in singleton select"_.

[.since]_Jaybird 5/Firebird 5.0_ Support for multi-row `RETURNING` is introduced in Firebird 5.0.
Support for multi-row `RETURNING` is available in Jaybird 5.
====

The examples in this section use the following (Firebird 3.0) table:

[source,sql]
.Example person table
----
create table PERSON (
  ID integer generated by default as identity constraint pk_employee primary key,
  FIRSTNAME varchar(20),
  LASTNAME varchar(20),
  BIRTHDATE date,
  "age" integer generated always as (datediff(year, birthdate, current_date))
)
----

[[ref-generatedkeys-RETURN-GENERATED-KEYS]]
==== Basic generated keys retrieval

This form of generated keys execution involves the following methods:

* `Connection.prepareStatement(String sql, int autoGeneratedKeys)`
* `Statement.execute(String sql, int autoGeneratedKeys)`
* `Statement.executeUpdate(String sql, int autoGeneratedKeys)`
* `Statement.executeLargeUpdate(String sql, int autoGeneratedKeys)` ([.since]_JDBC 4.2_)

When `NO_GENERATED_KEYS` is passed, the query will be executed as a normal query.

When `RETURN_GENERATED_KEYS` is passed, the driver will return _all_ columns of the table as generated keys.
The columns are ordered by ordinal position (as reported in the JDBC metadata of the table).
It is advisable to retrieve the values from the `getGeneratedKeys()` result set by column name.

We opted to include all columns as it is next to impossible to decide which columns are populated by a trigger or otherwise.
Only returning the primary key will be too restrictive (consider computed columns, default values, etc).

Passing `NO_GENERATED_KEYS` hardcoded should normally not be done.
It would be better to use the equivalent `prepareStatement` or `executeXXX` method that only accepts a `String`.
Use of the value `NO_GENERATED_KEYS` only makes sense in code that dynamically decides between `NO_GENERATED_KEYS` and `RETURN_GENERATED_KEYS`.

[[ref-generatedkeys-examples-RETURN-GENERATED-KEYS]]
===== Example using RETURN_GENERATED_KEYS

The following will insert a person using a `Statement` and retrieve the generated id using `Statement.RETURN_GENERATED_KEYS`:

[source,java]
.Statement generated keys retrieval
----
Connection connection = ...;
try (Statement statement = connection.createStatement()) {
  statement.executeUpdate(
      "insert into person(firstname, lastname, birthdate) "
          + "values ('Mark', 'Rotteveel', date'1979-01-12')",
      Statement.RETURN_GENERATED_KEYS);                 // <1>

  try (ResultSet keys = statement.getGeneratedKeys()) { // <2>
    if (keys.next()) {                                  // <3>
      int generatedId = keys.getInt("id");              // <4>
      int age = keys.getInt("age");                     // <5>
      String firstName = keys.getString("firstname");   // <6>

      System.out.printf("Inserted: %s, Id: %d, Age: %d%n", 
          firstName, generatedId, age);
    }
  }
}
----
<1> Use of `Statement.RETURN_GENERATED_KEYS` instructs Jaybird to parse the statement and add a `RETURNING` clause with all columns of the `PERSON` table
<2> Get the generated keys result set from the statement
<3> Just like a normal result set, it is positioned before the first row, so you need to call `next()`
<4> The generated value of the `ID` column
<5> The calculated value of the `AGE` column
<6> The generated keys result set also contains the normal columns like `FIRSTNAME`

The equivalent using `PreparedStatement` is:

[source,java]
.Prepared statement generated keys retrieval
----
try (PreparedStatement statement = connection.prepareStatement(
         "insert into person(firstname, lastname, birthdate) values (?, ?, ?)",
         Statement.RETURN_GENERATED_KEYS)) {            // <1>
  statement.setString(1, "Mark");
  statement.setString(2, "Rotteveel");
  statement.setObject(3, LocalDate.of(1979, 1, 12));

  statement.executeUpdate();
  try (ResultSet keys = statement.getGeneratedKeys()) { // <2>
    if (keys.next()) {                                  // <3>
      int generatedId = keys.getInt("id");              // <4>
      int age = keys.getInt("age");                     // <5>
      String firstName = keys.getString("firstname");

      System.out.printf("Inserted: %s, Id: %d, Age: %d%n",
          firstName, generatedId, age);
    }
  }
}
----
<1> Besides use of parameters, the only real difference is that use of `Statement.RETURN_GENERATED_KEYS` moved from execution to prepare.
This makes sense if you consider that once prepared, the statement can be reused.

[[ref-generatedkeys-column-index]]
==== Generated keys by column index

This form of generated keys execution involves the following methods:

* `Connection.prepareStatement(String sql, int[] columnIndexes)`
* `Statement.execute(String sql, int[] columnIndexes)`
* `Statement.executeUpdate(String sql, int[] columnIndexes)`
* `Statement.executeLargeUpdate(String sql, int[] columnIndexes)` ([.since]_JDBC 4.2_)

The values in the `int[]` parameter are the ordinal positions of the columns as specified in the (JDBC) metadata of the table.

[WARNING]
====
In Jaybird 3 and earlier, a null or empty array was silently ignored and the statement was executed normally (not producing generated keys).
In Jaybird 4, this behaviour has changed and instead will throw an exception with message _"Generated keys array columnIndexes was empty or null. A non-empty array is required."_

In Jaybird 3 and earlier, invalid ordinal positions are ignored and silently dropped: passing `new int[] { 1, 5, 6 }` will work, even though we don't have sixth column.
In Jaybird 4, this behavior has changed and instead will throw an exception with message _"Generated keys column position <position> does not exist for table <tablename>. Check DatabaseMetaData.getColumns (column ORDINAL_POSITION) for valid values."_
====

[[ref-generatedkeys-examples-column-index]]
===== Example using column indexes

Retrieval by column index uses the ordinal position as reported in `DatabaseMetaData.getColumns`, column `ORDINAL_POSITION`. 
In practice this is the value of `RDB$RELATION_FIELDS.RDB$FIELD_POSITION + 1` of that column.

In our example, the columns are

1. `ID`
2. `FIRSTNAME`
3. `LASTNAME`
4. `BIRTHDATE`
5. `age`

[source,java]
.Prepared statement generated keys retrieval by index
----
try (PreparedStatement statement = connection.prepareStatement(
         "insert into person(firstname, lastname, birthdate) values (?, ?, ?)",
         new int[] { 1, 5 })) {                         // <1>
  statement.setString(1, "Mark");
  statement.setString(2, "Rotteveel");
  statement.setObject(3, LocalDate.of(1979, 1, 12));

  statement.executeUpdate();
  try (ResultSet keys = statement.getGeneratedKeys()) { 
    if (keys.next()) {                                  
      int generatedId = keys.getInt("id");              // <2>
      int age = keys.getInt(2);                         // <3>

      System.out.printf("Id: %d, Age: %d%n",
          generatedId, age);
    }
  }
}
----
<1> Instead of `Statement.RETURN_GENERATED_KEYS`, the column indices are passed in an array, in this case `1` for `ID` and `5` for `age`.
<2> Retrieval of the first column, `ID`, by name
<3> Retrieval of the second column, `age`, by id.
Notice that the index used for retrieval does not match the position (5) passed in the prepare. 
As this is the second column, it is retrieved from the result set by `2`.

[WARNING]
====
In Jaybird 3 and earlier, the array of indices is sorted in ascending order before use: passing `new int[] { 4, 1, 3 }` will yield columns in order `ID`, `LASTNAME`, `BIRTHDATE`.
In Jaybird 4, this sort is no longer applied, so columns will be in the order specified by the array: `BIRTHDATE`, `ID`, `LASTNAME`.
To avoid issues, we recommend specifying the columns in ascending order, or always retrieve them by name.
====

[[ref-generatedkeys-column-name]]
==== Generated keys by column name

This form of generated keys execution involves the following methods:

* `Connection.prepareStatement(String sql, String[] columnNames)`
* `Statement.execute(String sql, String[] columnNames)`
* `Statement.executeUpdate(String sql, String[] columnNames)`
* `Statement.executeLargeUpdate(String sql, String[] columnNames)` ([.since]_JDBC 4.2_)

The values in the `String[]` are the column names to be returned. 
The column names provided are processed as is and are not checked for validity or the need of quoting.
Providing non-existent or incorrectly (un)quoted columns will result in an exception when the statement is processed by Firebird (be aware: the JDBC specification is not entirely clear if this is valid behavior, so this might change in the future).
This method is the fastest as it does not retrieve metadata from the server.

[WARNING]
====
In Jaybird 3 and earlier, a null or empty array was silently ignored and the statement was executed normally (not producing generated keys).
In Jaybird 4, this behaviour has changed and instead will throw an exception with message _"Generated keys array columnNames was empty or null. A non-empty array is required."_
====

[[ref-generatedkeys-examples-column-name]]
===== Example using column names

[source,java]
.Prepared statement generated keys retrieval by name
----
try (PreparedStatement statement = connection.prepareStatement(
         "insert into person(firstname, lastname, birthdate) values (?, ?, ?)",
         new String[] { "id", "\"age\"" })) {           // <1>
  statement.setString(1, "Mark");
  statement.setString(2, "Rotteveel");
  statement.setObject(3, LocalDate.of(1979, 1, 12));

  statement.executeUpdate();
  try (ResultSet keys = statement.getGeneratedKeys()) { 
    if (keys.next()) {                                  
      int generatedId = keys.getInt("id");
      int age = keys.getInt("age");

      System.out.printf("Id: %d, Age: %d%n",
          generatedId, age);
    }
  }
}
----
<1> The column names are passed as is, this means that correct quoting is required for case sensitive columns (and other names that require quoting).

[WARNING]
====
The requirement to pass column names correctly quoted is not specified in the JDBC standard. 
It may change in future Jaybird versions to conform with column names as returned from `DatabaseMetaData.getColumn`.
That is, unquoted exactly as stored in `RDB$RELATION_FIELDS.RDB$FIELD_NAME`.
Quoting the column names would then be done by Jaybird.

When this changes, a connection property for backwards compatibility will be provided.
====

[[ref-generatedkeys-config]]
==== Configuring generated keys support

[.since]_Jaybird 4_

The connection property `generatedKeysEnabled` (alias `generated_keys_enabled`) allows the behaviour of generated keys support to be configured.
This property is also available on data sources.

This property supports the following values (case insensitive):

* `default`: default behaviour to enable generated keys for statement types with `RETURNING` clause in the connected Firebird version.
Absence of this property, `null` or empty string implies `default`.
* `disabled`: disable support.
Attempts to use generated keys methods other than using `Statement.NO_GENERATED_KEYS` will throw a `SQLFeatureNotSupportedException`.
* `ignored`: ignore generated keys support.
Attempts to use generated keys methods will not attempt to detect generated keys support and execute as if the statement generates no keys.
The `Statement.getGeneratedKeys()` method will always return an empty result set.
This behaviour is equivalent to using the non-generated keys methods.
* A comma-separated list of statement types to enable.

For `disabled` and `ignored`, `DatabaseMetaData.supportsGetGeneratedKeys` will report `false`.

Because of the behaviour specified in the next section, typos in property values will behave as `ignored` (eg using `generatedKeysEnabled=disable` instead of `disabled` will behave as `ignored`).

[[ref-generatedkeys-config-stmt-types]]
===== Selectively enable statement types

This last option allows you to selectively enable support for generated keys.
For example, `generatedKeysEnabled=insert` will only enable it for `insert` while ignoring it for all other statement types.
Statement types that are not enabled will behave as if they generate no keys and will execute normally.
For these statement types, `Statement.getGeneratedKeys()` will return an empty result set.

Possible statement type values (case insensitive) are:

* `insert`
* `update`
* `delete`
* `update_or_insert`
* `merge`

Invalid values will be ignored.
If none of he specified statement types are supported by Firebird, it will behave as `ignored`.footnote:[This is not the case for the unsupported Firebird 1.0 and 1.5 versions. There this will behave similar to `disabled`, and you will need to explicitly specify `ignored` instead to get this behaviour.]

Some examples:

* `jdbc:firebird://localhost/testdb?generatedKeysEnabled=insert` will only enable insert support
* `jdbc:firebird://localhost/testdb?generatedKeysEnabled=merge` will only enable merge support.
But only on Firebird 3.0 and higher, for Firebird 2.5 this will behave as `ignored` given the lack of `RETURNING` support for merge.
* `jdbc:firebird://localhost/testdb?generatedKeysEnabled=insert,update` will only enable insert and update support

This feature can be used to circumvent issues with frameworks or tools that always use generated keys methods for prepare or execution.
For example with `UPDATE` statements that touch multiple records and -- given the Firebird 4.0 and earlier limitations for `RETURNING` -- produce the error _"multiple rows in singleton select"_.
