[[poolproperties]]
[appendix]
== Connection Pool Properties

This chapter contains the list of properties of the
`ConnectionPoolDataSource`, `DataSource` and `XADataSource` interface
implementations.

[NOTE]
====
The documentation in this section is only valid for Jaybird 2.2 and earlier.

Connection pooling was removed from Jaybird 3.0. 
Either use the connection pool provided by your application server, or use a third-party connection pool like https://www.mchange.com/projects/c3p0/[c3p0^], https://commons.apache.org/proper/commons-dbcp/[Apache DBCP^] or https://brettwooldridge.github.io/HikariCP/[HikariCP^].
====

=== Standard JDBC Properties

This group contains properties defined in the JDBC specification and
should be standard to all connection pools.

[cols="1,2",options="header",]
|=======================================================================
|Property |Description

|`maxIdleTime`
|Maximum time in milliseconds after which an idle connection in the pool is closed.

|`maxPoolSize` 
|Maximum number of open physical connections.

|`minPoolSize` 
|Minimum number of open physical connections.
If value is greater than 0, corresponding number of connections will be opened when first connection is obtained.

|`maxStatements` 
|Maximum size of the prepared statement pool. 
If zero, statement pooling is switched off. 
When the application requests more statements than can be kept in the pool, Jaybird will allow creating those statements, however closing them would not return them back to the pool, but rather immediately release the resources.
|=======================================================================

=== Pool Properties

This group of properties are specific to the Jaybird implementation of
the connection pooling classes.

[cols="1,2",options="header",]
|=======================================================================
|Property |Description

|`blockingTimeout` 
|Maximum time in milliseconds during which application can be blocked waiting for a connection from the pool.
If no free connection can be obtained, an exception is thrown.

|`retryInterval`
|Period in which the pool will try to obtain a new connection while blocking the application.

|`pooling` 
|Allows to switch connection pooling off.

|`statementPooling` 
|Allows to switch statement pooling off.

|`pingStatement` 
|Statement that will be used to "ping" the JDBC connection, in other words, to check if it is still alive.
This statement must always succeed. 
he default SQL statement for the Firebird database is `"SELECT CAST(1 AS INTEGER) FROM rdb$database"`.

|`pingInterval` 
|Time during which connection is believed to be valid in any case.
The pool "pings" the connection before giving it to the application only if more than specified amount of time passed since last "ping".

|`isolation` 
a|Default transaction isolation level. 
All connections returned from the pool will have this isolation level. 
One of:

* `TRANSACTION_READ_COMMITTED`
* `TRANSACTION_REPEATABLE_READ`
* `TRANSACTION_SERIALIZABLE`

|`transactionIsolationLevel` 
|Integer value from `java.sql.Connection` interface corresponding to the transaction isolation level specified in isolation property.
|=======================================================================

=== Runtime Pool Properties

This group contains read-only properties that provide information about the state of the pool.

[cols="1,2",options="header",]
|=======================================================================
|Property |Description

|`freeSize` 
|Tells how many free connections are in the pool. 
Value is between 0 and `totalSize`.

|`workingSize` 
|Tells how many connections were taken from the pool and are currently used in the application.

|`totalSize` 
|Total size of open connection. 
At the pool creation – 0, after obtaining first connection – between `minPoolSize` and `maxPoolSize`.
|=======================================================================

=== Firebird-specific Properties

This group contains properties that specify parameters of the
connections that are obtained from this data source. Commonly used
parameters have the corresponding getter and setter methods, rest of the
Database Parameters Block parameters can be set using
`setNonStandardProperty` setter method.

[cols="1,2",options="header",]
|=======================================================================
|Property |Description

|`database` 
|Path to the database in the format `[host/port:]/path/to/database.fdb`

|`type` 
a|Type of the driver to use. Possible values are:

* `PURE_JAVA` or `TYPE4` for type 4 JDBC driver
* `NATIVE` or `TYPE2` for type 2 JDBC driver
* `EMBEDDED` for using embedded version of the Firebird
* `ORACLE` for accessing Oracle-mode Firebird

|`blobBufferSize` 
|Size of the buffer used to transfer BLOB content.
Maximum value is 64k-1.

|`socketBufferSize` 
|Size of the socket buffer. 
Needed on some Linux machines to fix performance degradation.

|`charSet` 
|Character set for the connection. 
Similar to `encoding` property, but accepts Java names instead of Firebird ones.

|`encoding` 
|Character encoding for the connection. 
See Firebird documentation for more information.

|`userName`
|Name of the user that will be used by default.

|`password` 
|Corresponding password.

|`roleName` 
|SQL role to use.

|`tpbMapping` 
|TPB mapping for different transaction isolation modes.
|=======================================================================

=== Non-standard parameters

Many of the above mentioned Firebird parameters have have a
corresponding DPB entry. However, not every DPB entry has a
corresponding getter/setter. This was done intentionally, Firebird
provides almost 70 DPB parameters, but for most of the applications only
few are needed. The remaining parameters are used by specialized
applications (usually server or database management software) for
setting some default values of the database, controlling the cache
buffers on the server, etc. Creating a corresponding getter/setter for
each of them simply does not make sense.

For those Java applications that still need non-standard connectivity
parameters, `DataSource` and `ConnectionPoolDataSource` implementations
provides a getter and two setters:

* `getNonStandardProperty(String name)` method returns a non-standard
property specified by `name` parameter. If this property was not
previously set, `null` is returned.
* `setNonStandardProperty(String name, String value)` method sets the
property specified by the first parameter to a value contained in the
second parameter.
* `setNonStandardProperty(String nameValuePair)` method provides a
possibility to set a DPB parameter using following syntax:
+
....
dataSource.setNonStandardProperty("isc_dpb_sql_dialect=3");
....

The parameter syntax of the last method is not very common in Java code,
it would be much more natural to use two-parameter setter. However, it
has a specialized use, because there's no possibility to use
two-parameter setter method in configuration files. Usually, when
setting a configuration parameter of a data source, web-containers use
the Java reflection API and consider only those setters that take one
parameter. For instance, in the Tomcat server the configuration
parameter would look like this:

[source,xml]
----
<parameter>
  <name>nonStandardProperty</name>
  <value>sql_dialect=3</value>
</parameter>
----

Syntax of the parameter is

....
<name>[<whitespace>][{=|:|<whitespace>}[<whitespace>]<value>]
....

where `<name>` is the name of the DPB parameter, and `<value>` is its
value. The two are separated by any combination of whitespace and either
whitespace or "=" (equal sign) or ":" (colon) characters. Considering
the aliases described in <<Extended connection properties>>. For example following values are equivalent:

....
isc_dpb_sql_dialect   3
isc_dpb_sql_dialect : 3
sql_dialect         : 3
sql_dialect=3
....

