[[services]]
== Working with Services

In addition to normal database connections, Firebird features server-wide connections.
These are used to perform various administrative tasks in Firebird, e.g. database backup, maintenance, statistics.
The set of API calls to perform such tasks are known under the name "`Services API`".
Additionally, client applications can use the Services API to get some limited information about the server environment and configuration.

The actual execution of the Services API calls can be viewed as a tasks triggered from the client application to be executed on server.
The parameters passed in the calls are internally used to construct the arguments similar to the ones that are passed to command-line tools.
Later these arguments are passed into the entry routines of the _gbak_, _gfix_, _gsec_ or _gstat_ utility.
The output of the utility, which in normal case is printed to standard out, is in this case transmitted over the network to the client application.

Jaybird attempts to hide the complexity of the original API by providing a set of interfaces and their implementations to perform the administrative tasks regardless of the usage mode (i.e. remote server and embedded engine, wire protocol and access via native client library).

This chapter describes the Java API for the administrative tasks.
All classes and interfaces described below are defined in the `org.firebirdsql.management` package.
Each management class works as a standalone object and does not require an open connection to the server.

[[servicemanager]]
=== ServiceManager[[_servicemanager]]

The `ServiceManager` interface and the `FBServiceManager` class are defined as the common superclasses providing setters and getters for common properties as well as some common routines.
The following properties can be specified:

[cols="2m,2m,4",options="header",]
|===
|Name |Type |Description

a|`host` +
`serverName`
|String
|Name or the IP address of the host to which we make the Service API request. _Required_.

a|`port` +
`portNumber`
|int
|Port to which we make the request, 3050 by default.

3+a|NOTE: [.since]_Jaybird 5_ `serverName` and `portNumber` are replacements for `host` and `port`, which have been deprecated for removal in Jaybird 6.

|database
|String
|Path to the database. 
The meaning of the property depends on the service being invoked and will be described in each of chapters below.

|user
|String
|Name of the user on behalf of which all Service API calls will be executed. _Required_.

|password
|String
|Password corresponding to the specified user. _Required_.

|roleName
|String
|Role name. _Optional_.

|expectedDb
|String
a|[.since]_Jaybird 5_ With Firebird 3.0 and higher, this is used to find the non-default security database to use when authenticating.
Value is a database path or alias the user can connect to. _Optional_.

|authPlugins
|String
a|Comma-separated list of authentication plugins to use (ignored for Firebird 2.5 or earlier).
Use `null` (the default) to use Jaybird defaults.

|processId
|int
a|[.since]_Jaybird 5_ Process id to report to the server.

|processName
|String
a|[.since]_Jaybird 5_ Process name to report to the server.

|socketBufferSize
|int
a|[.since]_Jaybird 5_ Socket buffer size in bytes

|soTimeout
|int
a|[.since]_Jaybird 5_ Socket blocking read timeout in milliseconds (`0` is OS default timeout)

|connectTimeout
|int
a|[.since]_Jaybird 5_ Socket connect timeout in milliseconds (`0` is OS default timeout)

|wireCrypt
a|`String` or `WireCrypt`
a|Wire encryption level (`DISABLED`, `ENABLED`, `REQUIRED`, `DEFAULT`).
In Jaybird 3.0.4+ and Jaybird 4, the property is type `WireCrypt`.
In Jaybird 5, the property is type `String`.

|wireCryptAsEnum
|WireCrypt
a|[.since]_Jaybird 5_ Alternative to `WireCrypt` to use `WireCrypt` enum.

|dbCryptConfig
|String
a|Database encryption config.
See <<ref-dbcrypt>> for details.

|wireCompression
|boolean
a|Enable wire compression (requires Firebird 3.0 or higher).
Default is `false`.

|logger
|java.io.OutputStream
|Stream into which the output of the remote service will be written to. _Optional_.
|===

The last parameter requires some explanation.
The calls to all Services API routines are asynchronous.
The client application can start the call, but there are no other means to find out whether execution of the service call is finished or not except reading the output of the service call -- EOF in this case means that execution is finished.

The `FBServiceManager` converts the asynchronous calls into a synchronous call by constantly polling the service output stream.
If the `logger` property is specified the received data is copied into the specified `OutputStream`, otherwise it is simply ignored and the EOF-marker is being watched.

This behavior can be changed by overriding the appropriate method in the `FBServiceManager` class and/or subclasses.
The only requirement is to detach from the service manager when it is no longer needed.

[[services-backup-and-restore]]
=== Backup and restore[[_backup_and_restore]]

Jaybird supports _gbak_, _gbak_ streaming, and _nbackup_ backup and restore.

[[services-backup-and-restore-gbak]]
==== Gbak backup and restore

The _gbak_ backup and restore routines are defined in the `BackupManager` interface and are implemented in the `FBBackupManager` class.
This class provides server-side _gbak_ backups.
For details on _gbak_ itself, consult the https://firebirdsqlsbak.html[Firebird Backup & Restore Utility^] documentation.

In addition to the setters and getters described in the previous section, the following methods are used to specify the backup and restore paths and properties:

[cols="2m,1m,4",options="header",]
|===
|Name |Type |Description

|database
|String
|For a backup operation, it specifies the path or alias of the database to back up.

For a restore operation, it specifies the path to the database into which the backup file will be restored.
In case when multi-file database should be created, use the `addRestorePath(String, int)` method instead.

|backupPath
|String
|Path to the backup file. 
For a backup operation, specifies the path and the file name of the newly created backup file.
If multi-file backup files are to be created, use the `addBackupPath(String, int)` method instead.
For a restore operation, it specifies the path to the single backup file.
If a database should be restored from a multi-file backup, use the `addBackupPath(String)` method instead.

|restorePageBufferCount
|int
|Number of pages that will be cached of this particular database. 
Should be used only for restore operation.
If not set, the page cache size recorded in the backup is used.

|restorePageSize
|int
|Size of the database page. 
Should be used only for restore operation. 
Valid values depend on the Firebird version, but should be one of the 1024, 2048, 4096, 8192, 16384 or 32768.
If not set, the page size recorded in the backup is used.

|restoreReadOnly
|boolean
|Set to `true` if the database should be restored in read-only mode.

|restoreReplace
|boolean
a|Set to `true` if restore should replace the existing database with the one from backup.

WARNING: It is easy to drop an existing database if the backup can't be restored, as the existing database is first deleted and only after that the restore process starts. 
To avoid such situation it is recommended to restore a database into some dummy file first and then use file system commands to replace the existing database with the newly created one.

|verbose
|boolean
|Be verbose when writing to the log. 

The service called on the server will produce lots of output that will be written to the output stream specified in logger property.
|===

In addition to the properties, the following methods are used to configure the paths to back up and database files when multi-file back up or restore operations are used.

[cols="3m,4",]
|===
|Method |Description

|addBackupPath(String)
|Add a path to a backup file from a multi-file backup. 
Should be used for restore operation only.

|addBackupPath(String, int)
|Add a path to the multi-file backup. 
The second parameter specifies the maximum size of the particular file in bytes. 
Should be used for backup operation only.

|addRestorePath(String, int)
|Add a path for the multi-file database.
The second parameter specifies the maximum size of the database file in pages (in other words, the maximum size in bytes can be obtained by multiplying this value by `restorePageSize` parameter)

|clearBackupPaths()
|Clear all the specified backup paths. 
This method also clears the path specified in `backupPath` property.

|clearRestorePaths()
|Clear all the specified restore paths. 
This method also clears the path specified in the database property.
|===

All paths specified are paths specifications on the remote server.
This has the following implications:

[loweralpha]
. it is not possible to back up to the local or network drive unless it is mounted on the remote server;
. it is not possible to restore from the local or network drive unless it is mounted on the remote server.

The `FBStreamingBackupManager` can be used to perform remote backup and restore, see <<services-backup-and-restore-gbak-streaming>>.

After specifying all the needed properties, the application developer can use `backupDatabase()`, `backupMetadata()` and `restoreDatabase()` methods to perform the backup and restore tasks.
These methods will block until the operation is finished.
If the `logger` property was set, the output of the service will be written into the specified output stream, otherwise it will be ignored.footnote:[The output of the service is always transferred over the network regardless whether the logger property is set or not.
In addition to providing a possibility to the user to track the service progress, it acts also as a signal of operation completion -- in this case the Java code will receive an EOF marker.]

[source,java]
.Example of backup and restore process
----
// backup the database
BackupManager backupManager = new FBBackupManager();

backupManager.setServerName("localhost");
backupManager.setPortNumber(3050);
backupManager.setUser("SYSDBA");
backupManager.setPassword("masterkey");
backupManager.setLogger(System.out);
backupManager.setVerbose(true);

backupManager.setDatabase("C:/database/employee.fdb");
backupManager.setBackupPath("C:/database/employee.fbk");

backupManager.backupDatabase();
...
// and restore it back
BackupManager restoreManager = new FBBackupManager();

restoreManager.setServerName("localhost");
restoreManager.setPortNumber(3050);
restoreManager.setUser("SYSDBA");
restoreManager.setPassword("masterkey");
restoreManager.setLogger(System.out);
restoreManager.setVerbose(true);

restoreManager.setRestoreReplace(true); // attention!!!

restoreManager.setDatabase("C:/database/employee.fdb");
restoreManager.setBackupPath("C:/database/employee.fbk");

backupManager.restoreDatabase();
----

The methods `backupDatabase(int)` and `restoreDatabase(int)` provide a possibility to specify additional backup and restore options that cannot be specified via the properties of this class.
The parameter value is bitwise combination of the following constants:

[cols="3m,4",options="header",]
|===
|Constant |Description

|BACKUP_CONVERT 
|Backup external files as tables.

By default, external tables are not backed up, only references to the external files with data are stored in the backup file.
When this option is used, the backup will store the external table as if they were regular tables. 
On restore the tables are created as regular tables.

|BACKUP_EXPAND 
|No data compression.

The _gbak_ utility uses RLE compression for the strings in backup file.
Using this option tells it to write strings in their full length, possibly fully consisting of empty characters, etc.

|BACKUP_IGNORE_CHECKSUMS 
|Ignore checksums.

The backup utility can't back up a database with page checksum errors.
Such database is considered corrupted and the completeness and correctness of the backup cannot be guaranteed.
However, in some cases such errors can be ignored, e.g. when the index page is corrupted.
In such cases the data in the database are OK and the error disappears when the database is restored and index is recreated.

Use this option only when checksum errors are detected and can't be corrected without full backup/restore cycle.
Ensure that the restored database contains correct data afterwards.

|BACKUP_IGNORE_LIMBO 
|Ignore in-limbo transactions.

The backup utility can't back up a database with in-limbo transactions.
When such situation appears, the backup has to wait until the decision about the outcome of the in-limbo transaction.
After a wait timeout, an exception is thrown and backup is aborted.
This option allows to work around this situation -- _gbak_ looks for the most recent committed version of the record and writes it into the backup.

|BACKUP_METADATA_ONLY 
|Backup metadata only.

When this option is specified, the backup utility creates a backup of only the metadata information (e.g. table an/or view structure, stored procedures, etc.), but no data are backed up.
This allows restoring a clean database from the backup.

|BACKUP_NO_GARBAGE_COLLECT 
|Do not collect garbage during backup.

The backup process reads all records in the tables one by one.
When cooperative garbage collection is enabledfootnote:[Cooperative garbage collection can be switched off in SuperServer architecture with configuration option "```GCPolicy```".
It can't be switched off in ClassicServer and SuperClassic architectures.]
the transaction that accesses the latest version of the record is also responsible for marking the previous versions as garbage.
This process is time-consuming and might be switched off when creating backup, where the most recent version will be read.

Later, an operator can restore the database from the backup.
In databases with many back-versions of the records, the backup-restore cycle can be faster than traditional garbage collection.

|BACKUP_NON_TRANSPORTABLE 
|Use non-transportable backup format.

By default, _gbak_ creates a so-called transportable backup where it does not make difference whether it is later restored on a big-endian or little-endian platform.
By using this option, a non-transportable format will be used which only allows restoring the database on the same architecture.

|BACKUP_OLD_DESCRIPTIONS 
|Save old style metadata descriptions.

Actually no real information exist for this option, by default it is switched off.

|RESTORE_DEACTIVATE_INDEX 
|Deactivate indexes during restore.

By default, indexes are created at the beginning of the restore process, and they are updated with each record being restored from the backup file.
For big tables, it is more efficient first to store data in the database and to update the index afterwards.
When this option is specified, the indexes will be restored in the inactive state.
The downside of this option is that the database administrator is required to activate indexes afterwards;
it won't happen automatically.

|RESTORE_NO_SHADOW 
|Do not restore shadow database.

If the shadow database is configured, an absolute path to the shadow is stored in the backup file.
If such backup file is restored on a different system where the path does not exist (e.g. moving a database from Windows to Linux or otherwise), the restore will fail.
Using this option allows to overcome such situations.

|RESTORE_NO_VALIDITY 
|Do not restore validity constraints.

This option is usually needed when the validity constraints (e.g. `NOT NULL` constraints) were added after the data were already in the database, but the database contains records that do not satisfy such constraintsfootnote:[All versions of Firebird upto 2.5 allow to define validity constraints despite the table(s) contain data that do not satisfy them.
 Only the new records will be validated, and it is responsibility of the database administrator to ensure the validity of existing ones.].

When this option is specified, the validity constraints won't be restored.
This allows to recover the data and perform cleanup tasks.
The application and/or database administrators are responsible for restoring the validity constrains afterwards.

|RESTORE_ONE_AT_A_TIME 
|Commit after completing restore of each table.

By default, all data is restored in one transaction.
If for some reason a complete restore is not possible, using this option will allow to restore at least some of the data.

|RESTORE_USE_ALL_SPACE
|Do not reserve 20% on each page for the future versions, useful for read-only databases.
|===

Example of using these options:

[source,java]
.Example of using extended options for restore
----
BackupManager restoreManager = new FBBackupManager();

restoreManager.setServerName("localhost");
restoreManager.setPortNumber(3050);
restoreManager.setUser("SYSDBA");
restoreManager.setPassword("masterkey");
restoreManager.setLogger(System.out);
restoreManager.setVerbose(true);

restoreManager.setRestoreReplace(true); // attention!!!

restoreManager.setDatabase("C:/database/employee.fdb");
restoreManager.setBackupPath("C:/database/employee.fbk");

// restore database with no indexes, 
// validity constraints and shadow database
backupManager.restoreDatabase(
    BackupManager.RESTORE_DEACTIVATE_INDEX |
    BackupManager.RESTORE_NO_VALIDITY |
    BackupManager.RESTORE_NO_SHADOW |
    BackupManager.RESTORE_ONE_AT_A_TIME);
----

[[services-backup-and-restore-gbak-streaming]]
==== Gbak streaming backup and restore

The `FBStreamingBackupManager` class is a sibling of `FBBackupManager`, providing streaming backup and restore.
Streaming backup and restore allows client-server backup and restore, by streaming the backup from the server to the client -- on backup, or from the client to the server -- on restore.

The class implements interface `BackupManager` -- just like `FBBackupManager`, but the methods to set backup files (`setBackupPath`, `addBackupPath`) are not supported and throw an `IllegalArgumentException`.
Verbose backups are not supported.

In addition, the class defines the following methods:

[cols="3m,4",]
|===
|Method |Description

|setBackupOutputStream(OutputStream)
|`OutputStream` to write the backup.

|setRestoreInputStream(InputStream)
|`InputStream` to read the backup to restore.

|setBackupBufferSize(int)
|Size in bytes of the local buffer to use during backup, defaults to 30KB.

|===

[[services-backup-and-restore-nbackup]]
==== Nbackup

The `NBackupManager` interface and its implementation `FBNbackupManager` provides _nbackup_ backup and restore through the service API.
This form of backup and restore is server-side, meaning that all paths are on the Firebird server.
For information about _nbackup_, consult the https://www.firebirdsql.org/file/documentation/html/en/firebirddocs/nbackup/firebird-nbackup.html[Firebird's nbackup tool^] documentation.

In addition to the setters and getters described in the previous section, the following methods are used to specify the backup and restore paths and properties:

[cols="2m,1m,4",options="header",]
|===
|Name |Type |Description

|database
|String
|For a backup operation, it specifies the path or alias of the database to back up.

For a restore operation, it specifies the path to the database into which the backup file will be restored.

|backupFile
|String
|Path to the backup file.
For a backup operation, it specifies the path and the file name of the newly created backup file on the server.
For a restore operation, it specifies the path to the single backup file.
If a database should be restored from a multi-file backup, use the `addBackupFile(String)` method for additional files.

|backupLevel
|int
|The level of backup to perform.
Setting a level of `0` performs a full backup.
A level of `N` with `N > 1` will back up all data pages modified since the last level `N - 1` backup.
Defaults to `0` if `backupGuid` has not been set.

|backupGuid
|String
a|[.since]_Jaybird 4.0.4_ Sets the GUID of a previous backup (requires Firebird 4.0 or higher).
This will back up all data pages modified since the backup identified by the GUID.
The GUID is enclosed in braces (`++{++` and `++}++`).

|noDbTriggers
|boolean
|Disable database triggers for _nbackup_ operations that connect to the database.

|inPlaceRestore
|boolean
a|[.since]_Jaybird 4.0.4_ Enables in-place restore (requires Firebird 4.0 or higher).
This allows incremental restore, for example for a read-only replica, or a hot standby.

|preserveSequence
|boolean
a|[.since]_Jaybird 5_ Enables preserve sequence for restore or fixup (requires Firebird 4.0 or higher).
This preserves the existing GUID and replication sequence of the original database.

|cleanHistory
|boolean
a|[.since]_Jaybird 4.0.7_ Enable the _clean history_ option (requires Firebird 4.0.3 or higher).
One of the properties `keepRows` _or_ `keepDays` must also be set.
When enabled, after performing a backup, old records from the `RDB$BACKUP_HISTORY` will be removed.

|keepDays
|int
a|[.since]_Jaybird 4.0.7_ Number of days to keep backup history when `cleanHistory` is enabled.

|keepRows
|int
a|[.since]_Jaybird 4.0.7_ Number of rows (including the new backup!) to keep backup history when `cleanHistory` is enabled.

|===

In addition to the properties, the following methods are used to configure the paths to backup-files when multi-file restore operations are used.

[cols="3m,4",]
|===
|Method |Description

|addBackupFile(String)
|Add a path to a backup file from a multi-file backup.
In practice, `setBackupFile` does the same as `addBackupFile`.
For backup, only the first file set or added is used.
For restore, the files must be in the correct order to form the chain of the level `0` backup up to the highest level or last GUID-based backup to restore.

|clearBackupFiles()
|Clears the list of backup files.

|backupDatabase()
|Perform backup.

|restoreDatabase()
|Perform restore.

|fixupDatabase()
a|[.since]_Jaybird 5_ Perform the nbackup fixup operation.
A fixup will switch a locked database back to "`normal`" state without merging the delta, so this is a potentially destructive action.
The normal use-case of this option is to unlock a copy of a database file where the source database file was locked with `nbackup -L` or `ALTER DATABASE BEGIN BACKUP`.
Enable `preserveSequence` to preserve the original database GUID and replication sequence.

|===

After specifying all the needed properties, the application developer can use the `backupDatabase()`, `restoreDatabase()` and `fixupDatabase` methods to perform the backup and restore tasks.
These methods will block until the operation is finished.
No output is written to the `logger`.

[source,java]
.Example of nbackup backup and restore process
----
NBackupManager backupManager = new FBNBackupManager();

backupManager.setServerName("localhost");
backupManager.setPortNumber(3050);
backupManager.setUser("SYSDBA");
backupManager.setPassword("masterkey");

// backup level 1 increment against a previously performed level 0
backupManager.setDatabase("/path/to/database.fdb");
backupManager.setBackupFile("/path/to/backup_lvl_1.nbk");
backupManager.setBackupLevel(1);
backupManager.backupDatabase();

// restore level 0 and level 1 in new db restored.fdb
backupManager.clearBackupFiles();
backupManager.setDatabase("/path/to/restored.fdb");
backupManager.addBackupFile("/path/to/backup_lvl_0.nbk");
backupManager.addBackupFile("/path/to/backup_lvl_1.nbk");
backupManager.restoreDatabase();
----

=== User management

[IMPORTANT]
====
Starting with Firebird 3.0, user management through the Services API has been deprecated.
You should use the https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref50/fblangref50-security-user.html[SQL statements for user management] instead.
====

The next service available is the user management.
The routines are defined in the `UserManager` interface and are implemented in the `FBUserManager` class.
Additionally, there is an `User` interface providing getters and setters for properties of a user account on the server and corresponding implementation in the `FBUser` class.footnote:[
The class implementation is a simple bean publishing the properties via getters and setters.
You can replace it with any other implementation of the `User` interface.]
The available properties of the `FBUser` class are:

[cols="2,1,4",options="header",]
|===
|Name |Type |Description

|`userName` 
|`String` 
|Unique name of the user on the Firebird server. Required.
Maximum length is 31 byte.

|`password` 
|`String` 
|Corresponding password. 
Getter return value only if the password had been set

|`firstName` 
|`String` 
|First name of the user. Optional.

|`middleName` 
|`String` 
|Middle name of the user. Optional.

|`lastName` 
|`String` 
|Last name of the user. Optional.

|`userId` 
|`int` 
|ID of the user on Unix. Optional.

|`groupId` 
|`int` 
|ID of the group on Unix. Optional.
|===

The management class, `FBUserManager` has the following methods to manipulate the user accounts on the server:

[cols="3,4",options="header",]
|===
|Method |Description

|`getUsers():Map` 
|Method delivers a map containing usernames as keys and instances of `FBUser` class as values containing all users that are registered on the server.
The instances of `FBUser` class do not contain passwords, the corresponding property is `null`.

|`addUser(User)` 
|Register the user account on the server.

|`updateUser(User)` 
|Update the user account on the server.

|`deleteUser(User)` 
|Delete the user account on the server.
|===

An example of using the `FBUserManager` class:

[source,java]
.Example of FBUserManager class usage
----
UserManager userManager = new FBUserManager();

userManager.setServerName("localhost");
userManager.setPortNumber(3050);
userManager.setUser("SYSDBA");
userManager.setPassword("masterkey");

User user = new FBUser();
user.setUserName("TESTUSER123");
user.setPassword("test123");
user.setFirstName("John");
user.setMiddleName("W.");
user.setLastName("Doe");

userManager.add(user);
----

=== Database maintenance

Database maintenance is something that everybody would prefer to
avoid, and, contrary to the backup/restore and user management
procedures, there is little automation that can be done here. Usually the
maintenance tasks are performed on the server by the database
administrator, but some routines are needed to perform the automated
database upgrade or perform periodic checks of the database validity.

This chapter describes the methods declared in the `MaintenanceManager`
interface and its implementation, the `FBMaintenanceManager` class.

==== Database shutdown and restart

One of the most often used maintenance operations is database shutdown and/or bringing it back online.
When a  database was shutdown, only the user that initiated the shutdown, either SYSDBA or the database owner, can connect to the database and perform other tasks, e.g. metadata modification or database validation and repair.

The database shutdown is performed by `shutdownDatabase(int, int)` method.
The first parameter is the shutdown mode, the second -- the maximum allowed time for operation.

There are three shutdown modes:

[cols="1,2",options="header",]
|===
|Shutdown mode |Description

|`SHUTDOWN_ATTACH` 
|The shutdown process is initiated, and it is not possible to obtain a new connection to the database, but the currently open connections are fully functional.

When, after the maximum allowed time for operation, there are still open connections to the database, the shutdown process is aborted.

|`SHUTDOWN_TRANSACTIONAL` 
|The shutdown process is started, and it is not possible to start new transactions or open new connections to the database.
The transactions that were running at the time of shutdown initiation are fully functional.

When, after the maximum allowed time for operation, there are still running transactions, the shutdown process is aborted.

If no running transactions are found, the currently open connections are allowed to disconnect.

|`SHUTDOWN_FORCE` 
|The shutdown process is started and will be completed before or when the maximum allowed time for operation is reached.
New connections and transactions are not prohibited during the wait.

After the timeout, any running transaction won't be able to commit.

|===

After database shutdown, the owner of the database or SYSDBA can connect to it and perform maintenance tasks, e.g. migration to the new data modelfootnote:[
Until Firebird 2.0 adding a foreign key constraint required exclusive access to the database.],
validation of the database, changing the database file configuration.

To bring the database back online use the `bringDatabaseOnline()` method.

==== Shadow configuration

A database shadow is an in-sync copy of the database that is usually
stored on a different hard disk, possibly on a remote
computerfootnote:[Currently possible only on Unix platforms by using 
NFS shares.], which can be used as a primary database if the main
database server crashes. Shadows can be defined using `CREATE SHADOW`
SQL command and are characterized by a _mode_ parameter:

* in `AUTO` mode, the database continues operating even if the shadow becomes unavailable (disk or file system failure, remote node is not accessible, etc.)
* in `MANUAL` mode all database operations are halted until the problem is fixed.
Usually this means that the DBA has to kill the unavailable shadow and define a new one.

The `MaintenanceManager` provides a `killUnavailableShadows()` method to
kill the unavailable shadows. This is equivalent to the `gfix -kill`
command.

Additionally, if the main database becomes unavailable, the DBA can decide
to switch to the shadow database. In this case the shadow must be
activated before use. To activate the shadow use the
`activateShadowFile()` method. Please note, that in this case the
`database` property of the `MaintenanceManager` must point to the shadow
file which must be located on the local file system of the server to
which the management class is connected.

==== Database validation and repair

The Firebird server does its best to keep the database file in a consistent state.
This is achieved by an algorithm called _careful writes_, which guarantees that the server writes data on disk in such a manner that despite events like a server crash, the database file always remains in a consistent state.
Unfortunately, it is still possible that under certain conditions, e.g. a crash of the file system or hardware failure, the database file becomes corrupted.
Firebird server can detect such cases including

* Orphan pages.
These are database pages that were allocated for subsequent write, but due to a crash were not used.
Such pages have to be marked as unused, so the server can use them again;
* Corrupted pages.
These are database pages that were corrupted/damaged by operating system or hardware failures.

The `MaintenanceManager` class provides a `validateDatabase()` method to perform a simple health check of the database, releasing orphan pages if needed.
It also reports presence of the checksum errors.
The output of the routine is written to the output stream configured in the `logger` property.

The `validateDatabase(int)` method can be used to customize the validation process:

[cols="1m,2",options="header",]
|===
|Validation mode
|Description

|VALIDATE_READ_ONLY
|Perform read-only validation. 
In this case the database file won't be repaired, only the presence of database file errors will be reported.

Can be used for a periodical health-check of the database.

|VALIDATE_FULL
|Do a full check on record and pages structures, releasing unassigned record fragments.

|VALIDATE_IGNORE_CHECKSUM
|Ignore checksums during repair operations.

The checksum error means that the database page was overwritten in a random order and the data stored on it are corrupted.
When this option is specified, the validation process will succeed even if checksum errors are present.

|===

To repair the corrupted database use the `markCorruptRecords()` method which marks the corrupted records as unavailable.
This method is equivalent to `gfix -mend` command.
After this operation database can be backed up and restored to a different place.

[CAUTION]
====
The presence of checksum errors and subsequent use of `markCorruptedRecords()` method will mark all corrupted data as unused space.
You have to perform a careful check after a backup and restore cycle to assess the damage.
====

==== Limbo transactions

Limbo transactions -- or in-limbo transactions -- are transactions that were prepared for commit but were never committed or rolled back;
or in other words, an incomplete two-phase commit.
This can happen, for example, with a database used by JTA-enabled applications from Javafootnote:[
Another reason for limbo transactions are multi-database transactions which can be initiated via the native Firebird API.
However, since Jaybird does not provide methods to initiate them, we do not consider them in this manual.].
A limbo transactions affects the normal database operation, since the records that were modified in that transactions are not available, as Firebird does not know whether the new version will be committed or rolled back and blocks access to them.
Also, limbo transactions prevent garbage collection, since the garbage collector does not know whether it can discard the record versions of the limbo transaction.

Jaybird contains functionality to allow the JTA-enabled transaction coordinator to recover the limbo transactions and either commit them or perform a rollback.
For cases where this is not possible, `MaintenanceManager` provides the following methods to perform this in interactive mode:

[cols="1m,2",options="header",]
|===
|Method |Description

|listLimboTransactions()
|Method lists IDs of all in-limbo transactions to the output stream specified in logger property.

The application has to either parse the output to commit or rollback the transactions in some automated fashion, or it should present the output to the user and let him/her make a decision.
Alternatively, use one of the following two methods

|limboTransactionsAsList()
|Returns a `List<Long>` of the IDs of all in-limbo transactions

|getLimboTransactions()
| Returns an array of `long` with the IDs of all in-limbo transactions

|commitTransaction(long)
|Commit the transaction with the specified ID.

|rollbackTransaction(long)
|Rollback the transaction with the specified ID.

|===

==== Sweeping the database

The in-limbo transactions are not the only kind of transactions that prevent garbage collection.
Another type are transactions are those that were finished by "`rollback`" and the changes made in such transactions were not automatically undone by the internal savepoint mechanism, e.g. when there were a lot of changes made in the transaction (e.g. 10,000 records and more), or for transactions started with "`NO AUTO UNDO`"/`isc_tpb_no_auto_undo`.
Such transactions are marked as "rollback" transactions on the Transaction Inventory Page and this prevents advancing the so-called Oldest Interesting Transaction (OIT), the ID of the oldest transaction which created record versions that are relevant to any of the currently running transactions.
On each access to the records, Firebird has to check all the record versions between the current transaction and the OIT, which leads to performance degradation on large databases.
To solve the issue, Firebird periodically starts a database sweeping process, that traverses all database records, removes the changes made by the rolled back transactions and moves forward the OIT.footnote:[
For more information please read the following article by Ann Harrison, https://web.archive.org/web/20231004130607/https://www.ibphoenix.com/resources/documents/design/doc_21["`Firebird for the Database Expert: Episode 4 - OAT, OIT, & Sweep`"^]]

The sweep process is controlled by a threshold parameter, a difference between the Next Transaction and OIT, by default it is set to 20,000.
While this value is OK for the average database, a DBA can decide to increase or decrease the number to fit the database usage scenario.
Alternatively, a DBA can trigger the sweep process manually, regardless of the current difference between Next Transaction and OIT, for example during a maintenance window or hours with low load on the server.

The `MaintenanceManager` provides following methods to help with database sweeping:

[cols="1m,3",options="header",]
|===
|Method |Description

|setSweepThreshold(int)
|Set the threshold between Next Transaction and OIT that will trigger the automatic sweep process.
Default value is 20,000.

|sweepDatabase()
|Perform the sweep regardless of the current difference between Next Transaction and OIT.

|===

==== Other database properties

There are a few other properties of the database that can be set via `MaintenanceManager`:

[cols="1m,2",options="header",]
|===
|Method |Description

|setDatabaseAccessMode(int)
a|Change the access mode of the database. 
Possible values are:

* `ACCESS_MODE_READ_ONLY` to make database read-only;
* `ACCESS_MODE_READ_WRITE` to allow writes into the database.

Please note, only read-only databases can be placed on read-only media, read-write databases will need to be able to write even if only accessed with read-only transactions.

|setDatabaseDialect(int)
|Change the database SQL dialect.
Allowed values are 1 (deprecated) and 3.

|setDefaultCacheBuffer(int)
|Change the number of database pages to cache.

This setting applies to this specific database, overriding the system-wide configuration.

|setForcedWrites(boolean)
|Change the forced writes setting for the database.

When forced writes are switched off, the database engine does not enforce flushing pending changes to disk, and they are kept in OS cache.
If the same page is changed again later, the write happens in memory, which in many cases increases the performance.
However, in case of OS or hardware crashes, the database might get corrupted.

|setPageFill(int)
a|Set the page fill factor.

Firebird leaves 20% of free space on each database page for future record versions.
It is possible to tell Firebird not to reserve the space.
This makes sense for read-only databases, since more data fit the page, which increases performance.

Allowed values are:

* `PAGE_FILL_FULL` -- do not reserve additional space for future versions;
* `PAGE_FILL_RESERVE` -- reserve the free space for future record versions.

|===

[#services-table-statistics-manager]
=== Table statistics of a connection (experimental)

[.since]_Jaybird 5_

The class `org.firebirdsql.management.FBTableStatisticsManager` can be used to retrieve the table statistics of a connection.

Create an instance with `FBTableStatisticsManager#of(java.sql.Connection)` -- the connection must unwrap to a `FirebirdConnection` -- and retrieve a snapshot of the statistics with `FBTableStatisticsManager#getTableStatistics()`.

The method `getTableStatistics()` returns a `Map<String, TableStatistics>`, where the keys are table names, and the values statistics of tables.

A `TableStatistics` object has the following properties:

* `tableName`
* `readSeqCount`
* `readIdxCount`
* `insertCount`
* `updateCount`
* `deleteCount`
* `backoutCount`
* `purgeCount`
* `expungeCount`

[NOTE]
====
This is an experimental feature.
Its API may change in point releases, or it may be removed or replaced entirely in a future major release.
====

=== Database statistics

And last but not least is the `StatisticsManager` interface and corresponding implementation in the `FBStatisticsManager` class, which allow to obtain statistical information for the database, like page size, values of OIT and Next transactions, database dialect, database page allocation and its distribution.

The following methods provide the functionality equivalent to the _gstat_ command line tool, the output of the commands is written to the output stream specified in the `logger` property.
It is the responsibility of the application to correctly parse the text output if needed.

[cols="1m,2",options="header",]
|===
|Method |Description

|getDatabase{zwsp}Statistics()
|Get complete statistics about the database.

|getDatabase{zwsp}Statistics(int)
a|Get the statistical information for the specified options.

Possible values are (bit mask, can be combined):

* `DATA_TABLE_STATISTICS`
* `SYSTEM_TABLE_STATISTICS`
* `INDEX_STATISTICS`
* `RECORD_VERSION_STATISTICS`

|getHeader{zwsp}Page()
|Get information from the header page (e.g. page size, OIT, OAT and Next transaction values, etc.)

|getTable{zwsp}Statistics({zwsp}String[])
a|Get statistic information for the listed tables.

The statistics will be limited to the listed tables.
In Jaybird 6 and earlier, at least one table is required.

[.since]_Jaybird 7_ Method accepts varargs (`++String...++`).
In Jaybird 7 and later, specifying no tables will list all tables.

|getTable{zwsp}Statistics({zwsp}Collection<String>)
|[.since]_Jaybird 7_ Same as previous, but as a collection of table names.

|getTable{zwsp}Statistics({zwsp}Collection<String>, Collection<String>)
a|[.since]_Jaybird 7_ Get statistic information for the listed tables in the listed schemas.
Accepts a collection of schema names and a collection of table names.

The statistics will be limited to the listed schemas, and the listed tables.
If both collections are empty, all tables in all schemas are reported.
On Firebird 5.0 and older, the collections of schemas will be ignored.

|getDatabase{zwsp}Transaction{zwsp}Info()
a|Get transaction information of a database

The returned `DatabaseTransactionInfo` object has the following properties:

* `oldestTransaction`
* `oldestActiveTransaction`
* `oldestSnapshotTransaction`
* `nextTransaction`
* `activeTransactionCount`

|static getDatabase{zwsp}Transaction{zwsp}Info(Connection)
|Same as previous, but using an existing connection (must unwrap to `FirebirdConnection`)
|===
