[[exceptionhandling]]
== Handling exceptions

Exception handling is probably the most important aspect that
directly affects the stability of the application. Correct handling of
the error cases guarantees correct functioning of the client code as
well as the database server. 

All methods of the interfaces defined in the JDBC specification throw instances of
`java.sql.SQLException` to notify about error conditions that happen
during request processing. The `SQLException` is a checked exception,
which forces Java programmers to either handle it with the try/catch
clause or redeclare it in the method signature.

=== Working with exceptions

Exception handling becomes even more important if we consider that
this topic is either ignored or presented in incorrect form in most
JDBC tutorials. The https://docs.oracle.com/javase/tutorial/jdbc/index.html[official JDBC tutorial from Oracle] 
briefly mentions that exceptions should be handled by using try/catch blocks
only at the end of the course, but neither reasons for doing this nor the
best practices are presented.

There are good reasons to think about exception handling in your
applications before you start coding. First of all, it is very hard to
change the exception handling pattern in existing code. The changes
will affect all layers above the place where the changes in exception
handling are made and the new application must be thoroughly tested
after the change.

Another reason was already mentioned on the beginning of this chapter:
instances of `java.sql.SQLException` are the only way for the RDBMS
server to notify about the error condition that happened during request
processing. By checking the error code which is sent with the exception
application can try to recover from the error.

And last but not least, there is resource management. When an
exception happens in the method, the execution flow of Java code differs
from the normal flow, and only correctly coded application will ensure
that all allocated resources will be released. The resources in our case
are JDBC connections, statements, prepared statements and callable
statements, result sets, etc. All these objects not only take
memory in the Java Virtual Machine of the application, but also
consume memory on the server, which, worst case, can lead to
an unintended Denial-of-Service attack, as the database server can
no longer service requests.

A good exception handling strategy requires you do distinguish three
kinds of error conditions:

* errors that the database access layer can detect and correctly handle; for
example, the application might decide to re-execute the business
transaction if the database server returned a deadlock error;
* errors that database access layer can detect, but is unable to handle;
usually those are all database errors that do not have special handling
routines;
* errors that database access layer cannot detect without additional
code unrelated to the functionality of this layer; basically, all
runtime exceptions fall into this category.

The handling strategy then consists of

* processing the selected error codes for cases described above;
* converting the generic `SQLException` into a generic business error in the
application (this can be throwing some generic exception defined in the
application, but can also be an entry in the application event log and
short message that asks to retry the operation later);
* some emergency tactics, since the error that happened (e.g.
`NullPointerException` or `OutOfMemoryError`) was not considered while the
application was created, thus possibly leaving it in an unknown state;
further operation should be considered dangerous and the corresponding
execution branch has to be halted.

The problem of resource management can be solved if resource allocation and deallocation
happens in the same code block and is protected with a try-with-resources block. 
The code to recover from error conditions should use try/catch
blocks. Example of such error and resource handling code is presented
below.

[source,java]
.Typical resource allocation and error handling patterns
----
String updateString = "update COFFEES " +
    "set SALES = ? where COF_NAME like ?";

try (PreparedStatement updateSales = con.prepareStatement(updateString)) {
    int [] salesForWeek = {175, 150, 60, 155, 90};
    String [] coffees = {"Colombian", "French_Roast",
        "Espresso", "Colombian_Decaf",
        "French_Roast_Decaf"};
        
    int len = coffees.length;
    
    for(int i = 0; i < len; i++) {
    
        updateSales.setInt(1, salesForWeek[i]);
        updateSales.setString(2, coffees[i]);
        
        try {
            updateSales.executeUpdate();
        } catch(SQLException ex) {
            if (ex.getErrorCode() == ...) {
                // do something
            } else {
                throw new BusinessDBException(ex);
            }
        }
    }
}
----

// TODO Example doesn't actually show retry in case of deadlock!

The nested try/catch block shows you an example of handling a deadlock
error if it happens (first scenario according to our classification),
otherwise the exception is converted and passed to the upper layers
(second scenario). As you see, there is no special treatment to the
third scenario.

A possible bug in the JDBC driver could have generated runtime exception
in the `PreparedStatement.executeUpdate()` method, which would lead to
the statement handle leakage if the try-with-resource block had not been used to do the
resource cleanup. As a rule of thumb, always declare and allocate resources
in a try-with-resources block: the resource will be automatically closed/freed 
at the end of the block, even if exceptions occur.

Such coding practice might look weird, because on first sight the
whole purpose of using the `PreparedStatement` is neglected: the statement
is prepared, used only once and then deallocated. However, when this
practice is combined with connection and statement pooling, it
brings enormous advantage to the application code. The code becomes much
more manageable – resource allocations and deallocations happen in the
same method and the software developer does not need to remember the places where
the same prepared statement might be used – a statement pool will either
reuse the statement or it will prepare a new one, if it detects that all
pooled prepared statements are currently in use. As a side effect,
the application will always use the minimum number of statements handles,
which in turn reduces the used resources on the database side.

[WARNING]
====
Jaybird currently provides no statement pooling itself, availability will depend on the
connection pool library used. Consult the documentation of your connection pool
to see if - and how - it provides statement pooling.
====

=== Warnings

Some errors returned by Firebird are treated as warnings.
They are converted into instances of `java.sql.SQLWarning` class in the
JDBC layer. These exceptions are not thrown from the driver methods, but
added to a connection instance. 

NOTE: Currently no warning is added to `Statement` or `ResultSet` objects.

Each next warning is appended to the tail of the warning chain. In order
to read the warning chain, use the code presented below.

[source,java]
.Example how to work with warnings
----
import java.sql.*;
....
SQLWarning warning = connection.getWarnings();
while (warning != null) {
    .... // do something with the warning
    warning = warning.getNextWarning();
}
----

or

[source,java]
.Alternative example how to work with warnings
----
import java.sql.*;
....
for (Throwable throwable : connection.getWarnings() {
    if (throwable instanceof SQLWarning) {
       SQLWarning warning = (SQLWarning) throwable;
       .... // do something with the warning
    }
}
----

This second example will iterate over the first warning, all its causes (if any), and then on
to other warnings (if any), and so on.

In order to clear existing warning, call `Connection.clearWarnings()` method.

=== java.sql.SQLException in Jaybird

*TODO* Information in section is outdated

An `SQLException` is a special exception that is thrown by the JDBC
connectivity component in case of an error. Each instance of this
exception is required to carry the vendor error code (if applicable) and
a SQL state according to the X/Open SQLstate or SQL:2003 specifications. Firebird 
and Jaybird use SQL:2003 SQL state codes.footnoteref:[sqlstate, it is possible sometimes X/Open SQLstates are used]

When multiple SQL errors happened, they are joined into a chain. Usually
the most recent exception is thrown to the application, the exceptions
that happened before can be obtained via `SQLException.getNextException()` method.
Alternatively, `SQLException.iterator()` can be used to walk over all exceptions in
the chain and their causes.

The JDBC specification provides an exception hierarchy that allows an application to
react on the error situations using regular exception handling rather than checking 
the error code. Error codes may still be necessary for handling specific error cases.

The JDBC 4.3 specification defines the following exception hierarchy:footnote:[excluding those
defined for `javax.sql.rowset`]

* `java.sql.SQLException` - root of all JDBC exceptions
** `java.sql.BatchUpdateException` - thrown when batch of the
statements did not execute successfully; contains the result of batch
execution.
** `java.sql.SQLClientInfoException` - thrown when client info properties 
could not be set.
** `java.sql.SQLNonTransientException` - thrown when retrying the same action without fixing the 
underlying cause would fail.
*** `java.sql.SQLDataException` - thrown for data-related errors,
for example conversion errors, too long values. (SQLstate class `22`)
*** `java.sql.SQLFeatureNotSupportedException` - thrown to indicate that an optional 
JDBC feature is not supported by the driver or the data source (Firebird).  (SQLstate class `0A`)
*** `java.sql.SQLIntegrityConstraintViolationException` - thrown for constraint 
violations. (SQLstate class `23`)
*** `java.sql.SQLInvalidAuthorizationSpecException` - thrown for authorization 
failures. (SQLstate class `28`)
*** `java.sql.NonTransientConnectionException` - thrown for connection operations 
that will not succeed on retry without fixing the underlying cause. (SQLstate class `08`)
*** `java.sql.SQLSyntaxErrorException` - thrown for syntax errors. (SQLstate class `42`)
** `java.sql.SQLRecoverableException` - thrown when an action might be retried
by taking recovery actions and restarting the transaction.
** `java.sql.SQLTransientException` - thrown when the action might succeed if it is
retried without further recovery steps.
*** `java.sql.SQLTimeoutException` - thrown when the `queryTimeout` or 
`loginTimeout` has expired.
*** `java.sql.SQLTransactionRollbackException` - thrown when the statement was
automatically rolled back because of deadlock or other transaction serialization failures. (SQLstate class `40`)
*** `java.sql.SQLTransientConnectionException` - thrown for connection operations 
that might succeed on retry without any changes. (SQLstate class `08`)
** `java.sql.SQLWarning` should only be used to signal warnings, it should never be thrown
by a JDBC driver.
*** `java.sql.DataTruncation` - thrown when a data truncation
error happens, can also be used as a warning.

NOTE: Unfortunately Jaybird 3.0 does not yet fully use this exception hierarchy, we are
working to address this with the next versions of Jaybird.

Each of three layers in Jaybird use exceptions most appropriate to the
specific layer. *TODO* List needs revision

* `org.firebirdsql.gds.GDSException` is an exception that directly
corresponding to the error returned by the database engine. Instances of
this class are thrown by the GDS implementations. Upper layers either
convert these exceptions into the ones appropriate to that layer or
catch them if driver can handle the error condition.
* Subclasses of `javax.resource.ResourceException` are thrown by the JCA
layer when an error happens in the JCA-related code. Upper layer
converts this exception into a subclass of `java.sql.SQLException`. If
the `ResourceException` was caused by the `GDSException`, latter is
extracted during conversion preserving the error code. If
`ResourceException` was caused by an error condition not related to an
error returned by the database engine, error code of the `SQLException`
remains 0.
* Subclasses of `javax.transaction.XAException` are thrown when an XA
protocol error happens in JCA layer. Similar to the previous case,
`XAException` can wrap the `GDSException`, which are extracted during
exception conversion to preserve the error code.
* Subclasses of `java.sql.SQLException` are thrown by the JDBC layer.
Jaybird has a few subclasses that might be interesting to the
application:
** `org.firebirdsql.jdbc.FBDriverConsistencyCheckException` – this
exception is thrown when driver detects an internal inconsistent state.
SQL state is `HY000`.
** `org.firebirdsql.jdbc.FBDriverNotCapableException` – this exception
is thrown when an unsupported method is called. SQL state is `0A000`.
** `org.firebirdsql.jdbc.FBSQLParseException` – this exception is thrown
when incorrect escaped syntax is detected. SQL state is `42000`.
** `org.firebirdsql.jdbc.field.TypeConversionException` – this exception
is thrown when the driver is asked to perform a type conversion that is
not defined in the JDBC specification. For a table of allowed type
conversions see <<Data Type Conversion Table>>.

=== SQL states

Jaybird supports the SQLstate values from the SQL:2003 standard,footnoteref:[sqlstate] 
however only few states nicely map into the Firebird error codes.

Applications can use the SQLstate codes in the error handling routines
which should handle errors that are returned from different databases.
But since there is little agreement between RDBMS vendors, this method
can be used only for very coarse error distinction.

// TODO Expand on SQL states

=== Useful Firebird error codes

Contrary to the SQLstates, the Firebird native error codes are
extremely useful to determine the type of an error that happened.

Here you can find a short list of error codes, symbolic names of a
corresponding constant in a `org.firebirdsql.gds.ISCConstants` class,
the error message and short explanation of an error.

*TODO* Needs revising now Jaybird tries to pull the most important error code to the top

==== DDL Errors

DDL errors happen during execution of DDL requests, and two primary error codes
are used in Firebird while executing the DDL operations. There are few
other rare cases not mentioned here, but the corresponding error
messages contain enough information to understand the reason of an
error.

[cols="1,2,3",]
|=======================================================================
|335544351L 
|`isc_no_meta_update` 
a|`"unsuccessful metadata update"`

This error is returned when the requested DDL operation cannot be completed, for
example the application tries to define a primary key that will exceed the
maximum allowed key size.

|335544510L 
|`isc_lock_timeout` 
|In combination with `isc_obj_in_use`
(335544453L), this means that the DDL command tries to modify an object that
is used in some other place, usually in another transaction. The
complete error message will contain the name of the locked object.

|335544569L 
|`isc_dsql_error` 
|If the third error code is either
`isc_dsql_datatype_err` or `isc_dsql_command_err`, then additional error
codes and arguments specify the reason why the operation has failed.
|=======================================================================

==== Lock Errors

Lock errors are reported by Firebird primarily when the application tries to
modify a record which is already modified by a concurrent transaction.
Depending on the transaction parameters such error can be reported
either right after detection or after waiting some defined timeout
hoping that concurrent transaction will either commit or rollback and
eventually release the resource. More information on transaction locking
modes can be found in section <<Using transactions>>.

[cols="1,2,3",]
|=======================================================================
|335544345L 
|`isc_lock_conflict` 
a|`"lock conflict on no wait transaction"`

This error is returned when a "no wait" transaction needs to acquire a lock
but finds another concurrent transaction holding that lock.

Instead of waiting the predefined timeout hoping that concurrent
transaction will either commit or rollback, an error is returned to
notify an application about the situation.

|335544510L 
|`isc_lock_timeout` 
a|`"lock time-out on wait transaction"`

Similar to the `isc_lock_conflict`, but this error is returned when the lock timeout that
was specified for the current transaction expired while waiting for a lock.

Another source of this error are DDL operations that try to obtain a
lock on a database object that is currently used in some other place.

|335544336L 
|`isc_deadlock` 
a|`"deadlock"`

Two transactions experience a deadlock when each of them has a lock on a
resource on which the other is trying to obtain a lock.

|=======================================================================

==== Referential Integrity Errors

Referential integrity constraints ensure that the database remains in a
consistent state after the DML operation and/or whole transaction is
completed. Three primary error codes are returned when the defined
constraints are violated. The error messages are self-explanatory.

[cols="1,2,3",]
|=======================================================================
|335544665L 
|`isc_unique_key_violation`
|`violation of PRIMARY or UNIQUE KEY constraint "{0}" on table "{1}"`

|335544558L 
|`isc_check_constraint`
|`Operation violates CHECK constraint {0} on view or table {1}`

|335544466L 
|`isc_foreign_key`
|`violation of FOREIGN KEY constraint "{0}" on table "{1}"`
|=======================================================================

==== DSQL Errors

This group contains secondary codes for the primary error code
`isc_dsql_error` (`335544569L`), that has a message
`"Dynamic SQL Error"`.

In most situations, Jaybird 3 and higher will put this secondary error code in the
`SQLException` instead of `isc_dsql_error`.

[cols="1,2,3",]
|=======================================================================
|335544573L 
|`isc_dsql_datatype_err` 
a|`"Data type unknown"`

Usually this error is reported during DDL operation when the specified
data type is either unknown or cannot be used in the specified
statement. However it can also happen in DML operation, e.g. when an
`ORDER BY` clause contains unknown collation, or if a parameter is used
in a `SELECT` clause without explicit cast.

|335544570L 
|`isc_dsql_command_err` 
a|`"Invalid command"`

Error happens either during parsing the specified SQL request or by
handling the DDL command.

|=======================================================================

==== Other Errors

This table contains other errors that might be interesting to the
application developer, however they do not fall into any of the previous
categories.

[cols="1,2,3",]
|=======================================================================
|335544321L 
|`isc_arith_except` 
a|`"arithmetic exception, numeric overflow, or string truncation"`

Happens at runtime when an arithmetic exception happens, like division
by zero or the numeric overflow (e.g. number does not fit the 64 bits
limit).

Another source of this error are string operations, like string
concatenation producing a too long string, impossibility to transliterate
characters between character sets, etc.

Future versions of Firebird will provide a secondary code to distinguish
the exact reason of an error.

|335544348L 
|`isc_no_cur_rec` 
a|`"no current record for fetch operation"`

Happens when the application asks Firebird to fetch a record, but no record
is available for fetching.

Java applications should never get this error, since checks in the JDBC
driver should prevent the application from executing a fetch operation on the server
side.

|335544374L 
|`isc_stream_eof` 
a|`"attempt to fetch past the last record in a record stream"`

Application tries to execute fetch operation after all records have 
already been fetched.

Similar to the previous error, Java applications should not get this
error due to the checks that happen before issuing the fetch request to
the server.

|335544517L 
|`isc_except` 
a|`"exception {0}"`

An custom exception has been raised on the server. Java application can
examine the underlying GDSException to extract the exception message.

|335544721L 
|`isc_network_error` 
a|`Unable to complete network request to host "{0}"`

This error is thrown when Jaybird cannot establish a connection
to the database server due to a network issues, e.g. host name is
specified incorrectly, Firebird has not been started on the remote host,
firewall configuration prevents client from establishing the connection,
etc.

|=======================================================================

