[[introduction]]
== Introduction

Jaybird is a JCA/JDBC driver suite to connect to the Firebird database
server.

This driver is based on both the JCA standard for application server
connections to enterprise information systems and the well-known JDBC
standard. The JCA standard specifies an architecture in which an
application server can cooperate with a driver so that the application
server manages transactions, security, and resource pooling, and the
driver supplies only the connection functionality.

Jaybird is a driver that provides both Type 4 (pure Java) and Type 2 (native binding) support.
The type 2 driver includes support for Firebird Embedded.

=== This manual

This manual covers Jaybird {jaybird-version} and may use Java 8 and Firebird 3 specific features, but most examples and information also apply to previous versions of Jaybird, Firebird and Java.

New or removed features are tagged with the version that introduced a feature (eg [.since]_Jaybird 3_) or removed  feature (eg [.until]_Jaybird 3_).
This tagging is only done for features introduced (or removed) in Jaybird 2.2 or later, or in Firebird 3 or later, and for features available in Java/JDBC versions 8/4.2 or later.

This manual may include documentation of features of Jaybird versions later than {jaybird-version} to simplify manual maintenance and versioning.

=== History

When Borland released an open-source version of the InterBase RDBMS, it included sources for a type 3 JDBC driver called InterClient.footnote:[For those interested in software archaeology, you can find the open sourced Interclient sources archived on https://github.com/FirebirdSQL/x-cvs-interclient]
However due to some inherent limitations of the InterBase (and later Firebird) client library, it was decided that the type 3 driver was a dead end. 
Instead, the Firebird team decided to develop a pure Java implementation of the wire protocol. 
This implementation became the basis for Jaybird, a pure Java driver for Firebird relational database.

=== Jaybird Architecture

The Jaybird driver consists of three layers, each of which is
responsible for its part of the functionality.

* The GDS layer represents a Java translation of the Firebird API. It is
represented by a number of interfaces and classes from the 
`org.firebirdsql.gds` package (and sub-packages).
+
This API is implemented by a number of plugins that provide the pure java, native,
local, and embedded implementations of the driver.
* The JCA layer represents the heart of the driver. Here all connection
and transaction management happens. Additionally this layer adapts the
GDS API and proxies the calls to the GDS implementation.
+
The JCA layer is an implementation of the Java Connector Architecture specification.
* The JDBC layer is an implementation of the JDBC specification.

In addition, the Services API allows you to manage the database and the server 
itself. The Manager component represents a JMX compatible implementation
that utilizes the Services API. Currently only calls to create and drop database 
are available in the Manager component, other class provide features for database 
backup/restore, user management, statistics gathering, etc.

[[distribution]]
=== Jaybird Distribution

Jaybird {jaybird-version} supports Firebird {min-support-firebird} and higher.
See <<jaybirdversions>> for detailed information on supported Java and Firebird versions per Jaybird version.

The latest version of Jaybird can be downloaded from https://firebirdsql.org/en/jdbc-driver/[^]

[[distribution-maven]]
==== Maven

Alternatively, you can use maven to automatically download Jaybird and its dependencies.

Jaybird {jaybird-version} is available from Maven central:

Groupid: `org.firebirdsql.jdbc`, +
Artifactid: `jaybird-XXX` (where `XXX` is `jdk17` or `jdk18`). +
Version: `{jaybird-full-version}`

For example:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>jaybird-jdk18</artifactId>
  <version>{jaybird-full-version}</version>
</dependency>
----

The Maven definition of Jaybird depends on antlr-runtime by default.

If your application is deployed to a Java EE application server, you will need to
exclude the `javax.resource:connector-api` dependency, and add it as a provided 
dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>jaybird-jdk18</artifactId>
  <version>{jaybird-full-version}</version>
  <exclusions>
    <exclusion>
      <groupId>javax.resource</groupId>
      <artifactId>connector-api</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>javax.resource</groupId>
  <artifactId>connector-api</artifactId>
  <version>1.5</version>
  <scope>provided</scope>
</dependency>
----

If you want to use Type 2 support (native, local or embedded), you need to 
explicitly include JNA as a dependency, where the version ({jna-version}) is already specified by
the Jaybird dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>net.java.dev.jna</groupId>
  <artifactId>jna</artifactId>
</dependency>
----

We plan to make native and embedded support a separate library in future 
releases, and provide Firebird client libraries as Maven dependencies as well.

=== Quality Assurance

The Jaybird team uses JUnit test cases to assure the quality of the released driver. 
During development unit tests are extensively used. 
Committing a code change to the source control is not allowed until it passes all existing unit tests. 
Each reproducible bug usually gets its own test case. 
This guarantees that a clean check out can be compiled and will not contain any previously discovered and fixed bugs. 
Currently there are more than 3900 test cases covering most of the driver code.

=== Useful resources

==== JDBC

For JDBC documentation, see http://www.oracle.com/technetwork/java/javase/jdbc/index.html[^].

==== Firebird

General information about the Firebird database is available from the Firebird web site (https://www.firebirdsql.org/[^]).

For information about using SQL in Firebird, see the https://www.firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25.html[Firebird 2.5 Language Reference^] and other documents available from the https://www.firebirdsql.org/en/reference-manuals/[Reference Manuals^] section of the Firebird web site.

==== Jaybird Support

Support for Jaybird is available through the following channels:

* The https://groups.yahoo.com/group/Firebird-Java[Firebird-Java group^] and corresponding mailing
list firebird-java@yahoogroups.com
+
You can subscribe to the mailing list by sending an email to firebird-java-subscribe@yahoogroups.com
* On https://www.firebirdsql.org/file/documentation/drivers_documentation/java/faq.html[Jaybird Frequently Asked Questions^].
* On https://github.com/FirebirdSQL/jaybird/wiki/[Jaybird wiki^].
+
This is a place where the community shares information about different aspects of Jaybird usage,
configuration examples for different applications/servers, tips and tricks, FAQ, etc.
* On https://stackoverflow.com/[Stack Overflow^], please tag your questions with 
*jaybird* and *firebird*
+
Please make sure to familiarize yourself with the rules and expectations of Stack Overflow before asking, 
see https://stackoverflow.com/tour[Stack Overflow Tour^] and https://stackoverflow.com/help/asking[Help Center: Asking^]

=== Contributing

There are several ways you can contribute to Jaybird or Firebird in general:

* Participate on the mailing lists (see https://www.firebirdsql.org/en/mailing-lists/[^])
* Report bugs or submit patches on the tracker (see <<intro-reporting-bugs>>)
* Create pull requests on GitHub (https://github.com/FirebirdSQL/jaybird[^])
* Become a developer (for Jaybird contact us on firebird-java, for Firebird in general, use the 
Firebird-devel mailing list)
* Become a paying member or sponsor of the Firebird Foundation (see https://www.firebirdsql.org/en/firebird-foundation/[^])

[[intro-reporting-bugs]]
==== Reporting Bugs

The developers follow the firebird-java@yahoogroups.com list. Join the list and post information 
about suspected bugs. List members may be able to help out to determine if it is an actual bug, 
provide a workaround and get you going again, whereas bug fixes might take awhile.

You can report bugs in the Firebird bug tracker, project http://tracker.firebirdsql.org/browse/JDBC["Java Client (Jaybird)"^]

When reporting bugs, please provide a minimal, but complete reproduction, including databases and 
source code to reproduce the problem. Patches to fix bugs are also appreciated. Make sure the patch is 
against a recent master version of the code. You can also fork the jaybird repository and create pull 
requests.

