[[introduction]]
== Introduction

Jaybird is a JDBC driver to connect to the Firebird database server.

Jaybird is a driver that provides both Type 4 (pure Java) and Type 2 (native binding) support.
The type 2 driver includes support for Firebird Embedded.

.JCA -- Java Connector Architecture
****
Jaybird 4 and earlier are based on both the well-known JDBC standard and the JCA -- Java Connector Architecture -- standard for application server connections to enterprise information systems.
The JCA standard specifies an architecture in which an application server can cooperate with a driver so that the application server manages transactions, security, and resource pooling, and the driver supplies only the connection functionality.

The JCA implementation was removed in Jaybird 5, and Jaybird is now only a JDBC driver.
****

=== This manual

This manual covers Jaybird {jaybird-version} and may use Java 17 and Firebird 4.0 specific features, but most examples and information also apply to previous versions of Jaybird, Firebird and Java.
Features that were removed in Jaybird 3 or earlier are not covered.

New or removed features are tagged with the version that introduced a feature (e.g. [.since]_Jaybird 5_) or removed feature (e.g. [.until]_Jaybird 5_).
This tagging is only done for features introduced (or removed) _after_ Jaybird 4.0.0, or in Firebird 3.0 or later.

This manual may include documentation of features of -- possibly unreleased -- Jaybird versions later than {jaybird-version} to simplify manual maintenance and versioning.

=== History

When Borland released an open-source version of the InterBase RDBMS, it included sources for a type 3 JDBC driver called InterClient.footnote:[For those interested in software archaeology, you can find the open sourced Interclient sources archived on https://github.com/FirebirdSQL/x-cvs-interclient]
However, due to some inherent limitations of the InterBase (and later Firebird) client library, it was decided that the type 3 driver was a dead end.
Instead, the Firebird team decided to develop a pure Java implementation of the wire protocol. 
This implementation became the basis for Jaybird, a pure Java driver for Firebird relational database.

=== Jaybird Architecture

The Jaybird driver consists of three layers, each of which is
responsible for its part of the functionality.

* The GDS layer represents a Java translation of the Firebird API.
It is represented by a number of interfaces and classes from the `org.firebirdsql.gds` package (and sub-packages).
+
This API is implemented by a number of plugins that provide the pure java, native,
local, and embedded implementations of the driver.
* [.until]_Jaybird 5_ The JCA layer represents the heart of the driver.
Here all connection and transaction management happens.
Additionally, this layer adapts the GDS API and proxies the calls to the GDS implementation.
+
The JCA layer is an implementation of the Java Connector Architecture specification.
* [.since]_Jaybird 5_ The XCA layer is a replacement of the JCA layer of previous versions.
* The JDBC layer is an implementation of the JDBC specification.

In addition, the Services API allows you to manage the database and the server itself.
The manager component represents a JMX compatible implementation that utilizes the Services API.
Currently, only calls to create and drop database are available in the Manager component, other classes provide features for database backup/restore, user management, statistics gathering, etc.

[[distribution]]
=== Jaybird Distribution

Jaybird {jaybird-version} supports Firebird {min-support-firebird} and higher.
See <<jaybirdversions>> for detailed information on supported Java and Firebird versions per Jaybird version.

The latest version of Jaybird can be downloaded from https://firebirdsql.org/en/jdbc-driver/[^]

[[distribution-maven]]
==== Maven

Alternatively, you can use maven to automatically download Jaybird and its dependencies.

Jaybird {jaybird-version} is available from Maven central:

Groupid: `org.firebirdsql.jdbc`, +
Artifactid: `jaybird`, +
Version: `{jaybird-template-version}`

For example:

.Main Jaybird artifact
[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>jaybird</artifactId>
  <version>{jaybird-example-version}</version>
</dependency>
----

If you want to use ChaCha64 wire encryption, you need to explicitly include `chacha64-plugin` as a dependency:

.ChaCha64 wire encryption plugin
[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>chacha64-plugin</artifactId>
  <version>{jaybird-example-version}</version>
</dependency>
----

If you want to use Type 2 support (native or embedded), you need to explicitly include `jaybird-native` as a dependency:

.Jaybird native artifact (native and embedded protocol)
[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.firebirdsql.jdbc</groupId>
  <artifactId>jaybird-native</artifactId>
  <version>{jaybird-example-version}</version>
</dependency>
----

The Firebird client library is available as a Maven dependencies, see <<driver-native-maven>>.
In the future, a Maven dependency for Firebird embedded may become available as well.

[#distribution-gradle]
==== Gradle

See also <<distribution-maven>>.

Examples:

.Main Jaybird artifact
[source,groovy,subs="verbatim,attributes"]
----
implementation 'org.firebirdsql.jdbc:jaybird:{jaybird-example-version}'
----

.ChaCha64 wire encryption plugin
[source,groovy,subs="verbatim,attributes"]
----
implementation 'org.firebirdsql.jdbc:chacha64-plugin:{jaybird-example-version}'
----

.Jaybird native artifact (native and embedded protocol)
[source,groovy,subs="verbatim,attributes"]
----
implementation 'org.firebirdsql.jdbc:jaybird-native:{jaybird-example-version}'
----

=== Quality Assurance

The Jaybird team uses JUnit test cases to assure the quality of the released driver. 
During development unit tests are extensively used. 
Committing a code change to the source control is not allowed until it passes all existing unit tests. 
Each reproducible bug usually gets its own test case. 
This guarantees that a clean check out can be compiled and will not contain any previously discovered and fixed bugs.

Currently, there are more than 10,000 test cases covering most of the driver code.
A subset of the tests are automatically run -- through a GitHub Action -- for each push to the repository.

=== Useful resources

==== JDBC

For JDBC documentation, see https://www.oracle.com/java/technologies/javase/javase-tech-database.html[Java SE Technologies - Database^].

For the JDBC specification, see https://jcp.org/en/jsr/detail?id=221[JSR 221: JDBC^TM^ 4.0 API Specification^] (covers JDBC 4.0 - 4.3, e.g. JDBC 4.3 is "`Maintenance Release 3`").

==== Firebird

General information about the Firebird database is available from the Firebird website (https://firebirdsql.org/[^]).

For information about using SQL in Firebird, see the https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref50/firebird-50-language-reference.html[Firebird 5.0 Language Reference^] and other documents available from the https://firebirdsql.org/en/reference-manuals/[Reference Manuals^] section of the Firebird website.

==== Jaybird Support

Support for Jaybird is available through the following channels:

* The https://groups.google.com/g/firebird-java[firebird-java Google Group^] and corresponding mailing list firebird-java@googlegroups.com
+
You can subscribe to the mailing list by sending an email to firebird-java+subscribe@googlegroups.com (this does not require a Google account).
Alternatively, you can join the group at the https://groups.google.com/g/firebird-java[firebird-java Google Group^] (this requires a Google account).
* On https://firebirdsql.org/docs/drivers/java/faq.html[Jaybird Frequently Asked Questions^].
* On https://github.com/FirebirdSQL/jaybird/wiki/[Jaybird wiki^].
* On https://stackoverflow.com/[Stack Overflow^], please tag your questions with
*jaybird* and *firebird*
+
Please make sure to familiarize yourself with the rules and expectations of Stack Overflow before asking, 
see https://stackoverflow.com/tour[Stack Overflow Tour^] and https://stackoverflow.com/help/asking[Help Center: Asking^]

=== Contributing

There are several ways you can contribute to Jaybird or Firebird in general:

* Participate on the https://firebirdsql.org/en/mailing-lists/[mailing lists^]
* Report bugs or submit patches on the tracker (see <<intro-reporting-bugs>>)
* Create pull requests on GitHub (https://github.com/FirebirdSQL/jaybird[^])
* Become a developer (for Jaybird contact us on https://groups.google.com/g/firebird-java[firebird-java^], for Firebird in general, use the https://groups.google.com/g/firebird-devel[firebird-devel Google Group^])
* Become a paying Associate, Partner or sponsor of the Firebird Foundation (see https://firebirdsql.org/en/firebird-foundation/[^])

[[intro-reporting-bugs]]
==== Reporting Bugs

The developers follow the https://groups.google.com/g/firebird-java[firebird-java Google Group^] and mailing list.
Join the list and post information about suspected bugs.
List members may be able to help out to determine if it is an actual bug, provide a workaround and get you going again, whereas bug fixes might take a while.

You can report bugs in the https://github.com/FirebirdSQL/jaybird/issues[Jaybird bug tracker^] on GitHub.

When reporting bugs, please provide a minimal, but complete reproduction, including databases and source code to reproduce the problem.
Patches or pull requests to fix bugs are also appreciated.
Make sure the patch is against a recent master version of the code.
You can also fork the https://github.com/FirebirdSQL/jaybird[jaybird repository^] and create pull requests.

