[[connection]]
== Obtaining a connection

Jaybird is a regular JDBC driver and supports two primary ways to obtain connection: via `java.sql.DriverManager` and via an implementation of the `javax.sql.DataSource` interface.

[[connection-drivermanager]]
=== Obtaining connection java.sql.DriverManager

`java.sql.DriverManager` was the first connection factory in Java. It is based on the concept of the JDBC URL, a string that uniquely identifies the database to connect.
The driver manager then checks which driver(s) -- if any -- can establish a connection.

There is also support to specify additional connection parameters, like username and password.

A JDBC URL consists of three parts:

....
jdbc:firebird://localhost:3050/c:/database/example.fdb
....

* `jdbc` +
JDBC protocol
* `firebird` or `firebirdsql` +
JDBC subprotocol, identifies driver to use, in this case Jaybird
* `//localhost:3050/c:/database/example.fdb` 
+
This is a database specific part, and identifies the database for the driver to connect, in the case of Jaybird that is `//<host>:<port>/<path to database>`

The first part, `jdbc:firebird:` or `jdbc:firebirdsql:`, is required by JDBC and specifies the so-called protocol and subprotocol for the JDBC connection.
In other words, the type of connection that the application wants to obtain, in this example it is a connection to a Firebird database.

An example of obtaining a connection is shown below.

[source,java]
.Simple example to obtain a JDBC connection
----
package hello;

import java.sql.*;

public class HelloServer {

  public static void main(String[] args) throws Exception {
  
    Class.forName("org.firebirdsql.jdbc.FBDriver"); // <1>
    
    Connection connection = DriverManager.getConnection( 
        "jdbc:firebird://localhost:3050/c:/db/employee.fdb",
        "SYSDBA", "masterkey"); // <2>
      
    // do something here
  }
}
----

The first line of this code is important -- it tells Java to load the Jaybird JDBC driver.
As required by the JDBC specification, at this point driver registers itself with `java.sql.DriverManager`.

Since Java 6 (JDBC 4), explicitly loading the driver using `Class.forName("org.firebirdsql.jdbc.FBDriver")` is no longer necessary, except when the driver is not on the system class path.
Examples where it may be necessary to explicitly load the driver are web applications that include the driver in the deployment.
There, the driver is not on the system class path, so it will need to be loaded explicitly.

We will leave out usages of `Class.forName` in further examples, they will work because of automatic driver loading.

.Registering the JDBC driver
[NOTE]
====
There are several ways to register JDBC driver:

1. `DriverManager` loads the drivers from the system class path. This happens automatically.

2. The application explicitly loads the driver's class.
This is only necessary if the automatic loading (see previous item) is not available.
This can be necessary because the driver `jar` is loaded dynamically, through a different classloader, etc).
+
The JDBC specification requires that during class initialization the driver registers itself with `DriverManager`.
+
....
Class.forName("org.firebirdsql.jdbc.FBDriver");
....
3. The JDBC driver name is listed in the `jdbc.drivers` system property.
Multiple drivers can be separated using a colon (`:`).
+
You can specify the value of this property during JVM startup:
+
....
java\
  -Djdbc.drivers=foo.Driver:org.firebirdsql.jdbc.FBDriver\
  -classpath jaybird-full-{jaybird-example-version}.jar;C:/myproject/classes\
  my.company.SomeJavaExample
....
====

The second statement of the example tells the `java.sql.DriverManager` to open a database connection to the Firebird server running on localhost, and the path to the database is `c:/database/employee.fdb`.

The connection specification consists of the host name of the database server, optionally you can specify a port (by default port 3050 is used).
The host name can be specified using either its DNS name (for example `fb-server.mycompany.com` or just `fb-server`), or its IP address (for example `192.168.0.5`, or `[1080::8:800:200C:417A]` for an IPv6 address).

After the server name and port, the alias or path to the database is specified.
We suggest to specify a database alias instead of the absolute database path.
For more information about using aliases, see the documentation of Firebird server.

The format of the path depends on the platform of the Firebird server. 

On Windows, the path must include the drive letter and path, for example `c:/database/employee.fdb`, which points to the employee database that can be found in the `database` directory of drive `C:`. 
Java (and Firebird) supports either `/` or `\` (escaped as `\\`) as path separator on the Windows platform. 
On Unix and Linux platform, you can use only `/` as the path separator.

On Unix platforms the path must include the root, as the path is otherwise interpreted relative to a server-dependent folder.
Having to include the root has the effect that a database in `/var/firebird/employee.fdb` needs to use a double `//` after the host name (and port) in the connection string: `jdbc:firebird://localhost//var/firebird/employee.fdb`.

It is possible to specify a relative path, but as this depends on the server configuration, this may be confusing or easily lead to errors.
We suggest not to use relative paths, and instead use an alias.

[[connection-drivermanager-props]]
==== Specifying extended properties

What if we want to specify additional connection parameters, for example a client encoding? 
The JDBC API provides a method to specify additional connection properties:

[source,java]
.Obtaining JDBC connection with additional connection properties
----
package hello;

import java.sql.*;
import java.util.*;

public class HelloServerWithEncoding {

  public static void main(String[] args) throws Exception {
    Properties props = new Properties();
    
    props.setProperty("user", "SYSDBA");
    props.setProperty("password", "masterkey");
    props.setProperty("encoding", "UTF8");
    
    try (Connection connection = DriverManager.getConnection(
            "jdbc:firebird://localhost:3050/C:/db/employee.fdb",
            props)) {
      
        // do something here
    
    }
  }
}
----

The `user` and `password` properties are defined in JDBC. All other property names, like `encoding` here, are driver-specific.

Additional properties, for example the SQL role for the connection can be added to the `props` object.
The list of properties available in Jaybird can be found in <<Extended connection properties>>.

It is not always possible to use the above described method.
Jaybird also provides a possibility to specify extended properties in the JDBC URL.

.Extended JDBC URL format
....
jdbc:firebird://host[:port]/<path to db>?<properties>
<properties> ::= <property>[{& | ;}<properties>]
<property>   ::= <name>[=<value>]
....

The example below shows the specification for extended JDBC properties in the URL.

In this case extended properties are passed together with the URL using the HTTP-like parameter passing scheme: first comes the main part of the URL, then `"?"`, then name-value pairs separated with `&` or `;`.
This example is equivalent to the previous example.

NOTE: Jaybird only supports URL encoding in Jaybird 4 and higher.

[source,java]
.Specifying extended properties in the JDBC URL
----
import java.sql.*;

...

Connection connection = DriverManager.getConnection(
    "jdbc:firebird://localhost:3050/C:/db/employee.fdb?encoding=UTF8",
    "SYSDBA",
    "masterkey");
----

[[connection-drivermanager-props-urlencoding]]
===== URL encoding in query part of JDBC URL

[.since]_Jaybird 4_

Jaybird 4 and higher support UTF-8 URL encoded values (and keys) in the query part of the JDBC URL.

As a result of this change, the following previously unsupported characters can be used in a connection property value when escaped:

* `;` escaped as `%3B`
* `&` escaped as `%26`

In addition, the following characters must also be escaped:

* `{plus}` in the query part now means _space_ (0x20), so occurrences of `{plus}` (_plus_) need to be escaped as `%2B`;
make sure to do this for _base64_ encoded values of `dbCryptConfig` (or use the _base64url_ encoding instead)
* `%` in the query part now introduces an escape, so occurrences of `%` (_percent_) need to be escaped as `%25`

URL encoding can also be used to encode any unicode character in the query string.
Jaybird will always use UTF-8 for decoding.

Invalid URL encoded values will throw a `SQLNonTransientConnectionException`.

The support for URL encoding only applies to the JDBC URL part after the first `?`.
URL encoding should not be applied for connection properties set through `java.util.Properties` or on a `javax.sql.DataSource`.

[[connection-datasource]]
==== Obtaining a connection via javax.sql.DataSource

The interface `javax.sql.DataSource` defines a simple API for a factory of `java.sql.Connection` objects.
Data sources can be created and configured using code or bean introspection, looked up from JNDI, or injected by CDI or Spring.

Jaybird itself provides one `javax.sql.DataSource` implementation, `org.firebirdsql.ds.FBSimpleDataSource`, which is a plain factory of connections, without connection pooling.

A simple example of creating a data source and obtaining a connection via a `DataSource` object is shown below.

[source,java]
.Obtaining a JDBC connection from a DataSource
----
package hello;

import java.sql.*;
import org.firebirdsql.ds.*;

public class HelloServerDataSource {

  public static void main(String[] args) throws Exception {
    var ds = new FBSimpleDataSource();
    ds.setUser("SYSDBA");
    ds.setPassword("masterkey");
    // in a single property
    ds.setDatabaseName("//localhost:3050/C:/database/employee.fdb");
    // or split out over serverName, portNumber and databaseName
    ds.setServerName("localhost");
    ds.setPortNumber(3050);
    ds.setDatabaseName("C:/database/employee.fdb");

    try (Connection connection = ds.getConnection()) {
      // do something here...
    }
  }
}
----

[[connection-datasource-njdi]]
===== Using JNDI to look up a javax.sql.DataSource

The JDBC 2.0 specification introduced a mechanism to obtain database connections without requiring the application to know any specifics of the underlying JDBC driver.
The application is only required to know the logical name to find an instance of the `javax.sql.DataSource` interface using Java Naming and Directory Interface (JNDI).
This was a common way to obtain connections in web and application servers before the introduction of CDI.

This code assumes that you have correctly configured the JNDI properties.
For more information about configuring JNDI please refer to the documentation provided with your web or application server.

[source,java]
.Typical way to obtain JDBC connection via JNDI
----
package hello;

import java.sql.*;
import javax.sql.*;
import javax.naming.*;

public class HelloServerJNDI {

  public static void main(String[] args) throws Exception {
    var ctx = new InitialContext();
    DataSource ds = (DataSource) ctx.lookup("jdbc/SomeDB");

    try (Connection connection = ds.getConnection()) {
      // do something here... 
    }
  }
}
----

Usually, the binding between the `DataSource` object and its JNDI name happens in the configuration of your web or application server.
However, under some circumstances (e.g. you are developing your own JNDI-enabled application server/framework), you may have to do this yourself.
You can use this code snippet for this purpose:

[source,java]
.Programmatic way to instantiate javax.sql.DataSource implementation
----
import javax.naming.*;
import org.firebirdsql.ds.*;
...
var ds = new FBSimpleDataSource();

ds.setDatabaseName("//localhost:3050/C:/database/employee.fdb");
ds.setUser("SYSDBA");
ds.setPassword("masterkey");

var ctx = new InitialContext();

ctx.bind("jdbc/SomeDB", ds);
----

The `DataSource` implementation supports all connection properties available to the `DriverManager` interface.

[NOTE]
====
Manually binding to JNDI like shown above is uncommon.
If you find yourself copying this code, rethink what you're doing.
====

[[driver-types]]
=== Driver types

As mentioned in the section <<Jaybird Architecture>>, Jaybird supports multiple implementations of the GDS API.
The default Jaybird distribution contains two main categories of the implementations: the pure Java implementation of the Firebird wire protocol, and a JNA proxy that can use a Firebird `fbclient` library.

The next sections provide a description of these types and their configuration with the corresponding JDBC URLs that should be used to obtain the connection of desired type.
The type of the JDBC driver for the `javax.sql.DataSource` is configured via a corresponding property.

[[driver-pure-java]]
==== PURE_JAVA type

The `PURE_JAVA` type (JDBC Type 4) uses a pure Java implementation of the Firebird wire protocol.
This type is recommended for connecting to a remote database server using TCP/IP sockets.
No installation is required except adding the JDBC driver to the class path.
This type of driver provides the best performance when connecting to a remote server.

To obtain a connection using the `PURE_JAVA` driver type you have to use a JDBC URL as shown in <<Obtaining connection java.sql.DriverManager>>.

The following JDBC URL syntax is supported (_serverName_ became optional in Jaybird 5)

[listing,subs=+quotes]
----
<pure-java-url> ::=
  jdbc:firebird[sql]:[java:]<database-coordinates>

<database-coordinates> ::=
    //[_serverName_[:__portNumber__]]/_databaseName_
  | <legacy-url>

<legacy-url> ::=
  [_serverName_[/_portNumber_]:]_databaseName_
----

If _serverName_ is not specified, it defaults to `localhost`. +
If _portNumber_ is not specified, it defaults to `3050`.

In theory, even `<database-coordinates>` and _databaseName_ are optional, but this requires specifying the database name using connection property `databaseName`, which is possible, but not recommended.

When using `javax.sql.DataSource` implementation, you can specify either `"PURE_JAVA"` or `"TYPE4"` driver type, however this type is used by default.

Some URL examples

.Pure Java URL examples
[listing]
----
// Connect to db alias employee on localhost, port 3050
jdbc:firebird://localhost/employee
jdbc:firebird://localhost:3050/employee
jdbc:firebird:///employee

// Same using the legacy URL format
jdbc:firebird:localhost:employee
jdbc:firebird:localhost/3050:employee
jdbc:firebird:employee
----

[NOTE]
====
The legacy URL format is the historic URL format used by Firebird itself.
We recommend not using this format, as it can be ambiguous.

For example, say you have a server called `java`, then `jdbc:firebird:java:employee` will attempt to open the `employee` db alias on `localhost`, not on `java`.
With `jdbc:firebird://java/employee`, this ambiguity does not exist.
====

[[driver-native]]
==== NATIVE and LOCAL types

[.since]_Jaybird 6_ Native connections require the `jaybird-native` artifact on the classpath.

The `NATIVE` and `LOCAL` types (JDBC Type 2) use a JNA proxy to access the Firebird client library and requires installation of the Firebird client.
The `NATIVE` driver type is used to access the remote database server, the `LOCAL` type (Windows only) accesses the database server running on the same host by means of IPC (Inter-Process Communication).
Performance of `NATIVE` driver is approximately 10% lower compared to the `PURE_JAVA` driver, but `LOCAL` type has up to 30% higher performance compared to the `PURE_JAVA` driver when connecting the server on the same host.
This is mostly due to the fact that TCP/IP stack is not involved in this mode.

To create a connection using the `NATIVE` JDBC driver to connect to a remote server you have to use the following JDBC URL with the native subprotocol.

The following JDBC URL syntax is supported:

[listing,subs=+quotes]
----
<native-url> ::=
  jdbc:firebird[sql]:native:<database-coordinates>

<database-coordinates> ::=
    //[_serverName_[:__portNumber__]]/_databaseName_
  | <fbclient-url>

<fbclient-url>
    inet://_serverName_[:__portNumber__]/_databaseName_
  | inet4://_serverName_[:__portNumber__]/_databaseName_
  | inet6://_serverName_[:__portNumber__]/_databaseName_
  | wnet://[_serverName_[:__portNumber__]/]_databaseName_
  | xnet://_databaseName_
  | [_serverName_[/_portNumber_]:]_databaseName_
----

[.since]_Jaybird 5_ Since Jaybird 5, all URLs supported by fbclient can be used.
The supported URLs depend on the fbclient version and the OS (e.g. XNET and WNET are Windows only, and WNET support will be removed in Firebird 5).

When connecting to a local database server using the `LOCAL` driver, you should use following:

....
jdbc:firebird:local:<absolute path to database>
....

In addition to Jaybird, this requires a native Firebird client library, and JNA {jna-version} needs to be on the classpath.

[NOTE]
.LOCAL protocol removed in Jaybird 5
====
[.since]_Jaybird 5_ The LOCAL protocol was removed in Jaybird 5, and is now simply an alias for NATIVE.
To ensure local access, use a connection string using XNET (Windows only!):

....
jdbc:firebird:native:xnet://<path to database>
....

This requires a Firebird 3.0 or later `fbclient.dll`.

Support for this type of URL was introduced in Jaybird 5, so this syntax cannot be used in earlier versions.

As XNET is Windows only, on other platforms, consider using an <<driver-embedded,EMBEDDED>> connection instead.
====

.Native URL examples
[listing]
----
// Connect to db alias employee on localhost, port 3050
jdbc:firebird:native://localhost/employee
jdbc:firebird:native://localhost:3050/employee
jdbc:firebird:native:///employee

jdbc:firebird:native:inet://localhost/employee
// Require IPv4
jdbc:firebird:native:inet4://localhost/employee
// Require IPv6
jdbc:firebird:native:inet6://localhost/employee
// Using WNET
jdbc:firebird:native:wnet://localhost/employee
// Using XNET
jdbc:firebird:native:xnet://employee

// Same using the legacy URL format
jdbc:firebird:native:localhost:employee
jdbc:firebird:native:localhost/3050:employee
// May use XNET, INET or embedded access
jdbc:firebird:native:employee
----

[[driver-native-maven]]
===== Maven dependency for native client

When using Jaybird 3 and later, you can use a library to provide the Firebird client library for the `native` and `local` protocol.
For Windows and Linux, you can add the `org.firebirdsql.jdbc:fbclient` dependency on your classpath.
This dependency does not support the `embedded` protocol.

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>fbclient</artifactId>
    <version>{jaybird-fbclient-version}</artifactId>
</dependency>
----

You can also download the library (see https://github.com/mrotteveel/jaybird-fbclient#download[mrotteveel/jaybird-fbclient] for download link) and add it your classpath.

See next sections for other solutions.

[[driver-native-windows]]
===== Windows

For Jaybird 3 and later, we recommend using the solution documented in <<driver-native-maven>>.

On Windows, you need to make sure that `fbclient.dll` is located on the `PATH` environment variable.
Alternatively you can specify the directory containing this DLL in the `jna.library.path` system property.

For example, if you put a copy of `fbclient.dll` in the current directory you have to use the following command to start Java:

....
java -cp <relevant claspath> -Djna.library.path=. com.mycompany.MyClass
....

If your Java installation is 32-bit, you need a 32-bit `fbclient.dll`, for 64-bit Java, a 64-bit `fbclient.dll`.

[[driver-native-linux]]
===== Linux

For Jaybird 3 and later, we recommend using the solution documented in <<driver-native-maven>>.

On Linux, you need to make sure that `libfbclient.so` is available through the `LD_PATH` environment variable.

Usually shared libraries are stored in the `/usr/lib/` directory;
however you will need root permissions to install the library there.
Some distributions will only have, for example, `libfbclient.so.2.5`.
In that case you may need to add a symlink from `libfbclient.so` to the client on your system.

Alternatively, you can specify the directory containing the library in the `jna.library.path` Java system property.
See the Windows example above for more details.

[[driver-native-limitations]]
===== Limitations

Older versions of the Firebird client library -- as far as we are aware, Firebird 2.1 or older -- may not be thread-safe when connecting to a local database server using IPC.
By default, Jaybird does not provide synchronization, but it can be enabled with the system property `org.firebirdsql.jna.syncWrapNativeLibrary` set to true.
However, this synchronization is local to the classloader that has loaded the Jaybird classes.

To guarantee correct synchronization, the Jaybird driver must be loaded by the top-most classloader.
For example, when using the Type 2 JDBC driver with a web or application server, you have to add the Jaybird classes to the main classpath (for example, to the `lib/` directory of your web or application server), but *not* to the web or Java EE/Jakarta EE application, e.g. the `WEB-INF/lib` directory.

[[driver-embedded]]
==== EMBEDDED type

[.since]_Jaybird 6_ Embedded connections require the `jaybird-native` artifact on the classpath.

The Embedded server JDBC driver is a Type 2 JDBC driver that, rather than using the Firebird client library, loads the Firebird embedded server library instead.
This is the highest performance type of JDBC driver for accessing local databases, as the Java code accesses the database file directly.

The following JDBC URL syntax is supported:

[listing,subs=+quotes]
----
<embedded-url> ::=
  jdbc:firebird[sql]:embedded:_dbname-or-alias_
----

In practice, the URL accepts the same `<fbclient-url>` values as described for `NATIVE`.
That is, the embedded server acts as client library (i.e. you get the same Type 2 behavior as you would get with using "native").

This driver tries to load `fbembed.dll/libfbembed.so` (the name used in Firebird 2.5 and earlier) and `fbclient.dll/libfbclient.so`.

See also the <<NATIVE and LOCAL types>> section.

When using Firebird 3.0 and higher embedded, you will need to make sure the necessary plugins like `engineNN.dll/libengineNN.so` (_NN_ is 12 for Firebird 3.0, 13 for Firebird 4.0 and Firebird 5.0) are accessible to the client library, consult the Firebird 3.0 documentation for more information.
For an example, see the article https://www.lawinegevaar.nl/firebird/jaybird_embedded_example.html[Jaybird with Firebird embedded example^].

// TODO Extend documentation

[[driver-embedded-limitations]]
===== Limitations

Older versions of the Firebird embedded server for Linux are not thread safe;
as far as we know this concerns Firebird 2.1 or older.
Jaybird can provide the needed synchronization in Java code, as described for <<driver-native-limitations,NATIVE type>>.
This implies the same restrictions on the classloader that will load the Jaybird classes.

By default, the Firebird embedded library opens databases in exclusive mode.
This means that this particular database is accessible only to one Java virtual machine.
This can be changed by the `ServerMode` setting in `firebird.conf`.

[[driver-ooremote]]
==== OOREMOTE type

The `OOREMOTE` type is a JDBC Type 4 specifically for use with OpenOffice.org and LibreOffice.
It addresses some differences in interpretation of the JDBC specification, and provides alternative metadata in certain cases to allow OpenOffice.org and LibreOffice to function correctly.

[NOTE]
====
This only describes connecting to Firebird using Jaybird from OpenOffice.org or LibreOffice, it is not about the Firebird embedded use that has been introduced in recent LibreOffice versions.
====

To obtain a connection you have to use following URL:

....
jdbc:firebirdsql:oo://host[:port]/<path to database>
jdbc:firebird:oo://host[:port]/<path to database>
....

All other notes for <<driver-pure-java>> apply.

[NOTE]
.OOREMOTE deprecated in Jaybird 5, to be removed in Jaybird 6
====
[.since]_Jaybird 5_ The OOREMOTE protocol implementation is deprecated and will be removed in Jaybird 6.
To connect to Firebird, use LibreOffice Base with connection option "`Firebird External`".
====

[[connection-pooling]]
=== Connection Pooling

Each time a connection is opened via `DriverManager`, a new physical connection to server is opened.
It is closed when the connection is closed.
To avoid the overhead of creating connections, you can use a connection pool implementation to maintain a cache of open physical connections that can be reused between user sessions.

Since Jaybird 3, Jaybird no longer provides a connection pool.
If you need a `javax.sql.DataSource` implementation that provides a connection pool, either use the connection pool support of your application server, or consider using https://brettwooldridge.github.io/HikariCP/[HikariCP^], https://commons.apache.org/proper/commons-dbcp/[DBCP^], or https://www.mchange.com/projects/c3p0/[c3p0^].

[[connection-pooling-hikaricp]]
==== HikariCP example

This example shows how to configure https://brettwooldridge.github.io/HikariCP/[HikariCP^] to connect to Firebird.

[source,java]
----
package example;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.firebirdsql.ds.FBSimpleDataSource;

import java.sql.Connection;
import java.sql.SQLException;

public class HikariConnectExample {

  public static void main(String[] args) {
    HikariDataSource hikariDataSource = initDataSource();

    try (Connection connection = hikariDataSource.getConnection()) {
      // use connection
    } catch (SQLException e) {
      System.getLogger("HikariConnectExample")
          .log(System.Logger.Level.ERROR, "Could not connect", e);
    }

    hikariDataSource.close();
  }

  private static HikariDataSource initDataSource() {
    var firebirdDataSource = new FBSimpleDataSource();
    firebirdDataSource.setServerName("localhost");
    firebirdDataSource.setDatabaseName("employee");
    firebirdDataSource.setUser("sysdba");
    firebirdDataSource.setPassword("masterkey");
    firebirdDataSource.setCharSet("utf-8");

    var config = new HikariConfig();
    config.setDataSource(firebirdDataSource);
    return new HikariDataSource(config);
  }
}
----

HikariCP provides multiple ways to configure the connection.
Some examples:

.Indirect use of `FBSimpleDataSource`
[source,java]
----
private static HikariDataSource initDataSourceAlternative1() {
  var config = new HikariConfig();
  config.setDataSourceClassName("org.firebirdsql.ds.FBSimpleDataSource");
  config.setUsername("sysdba");
  config.setPassword("masterkey");
  config.addDataSourceProperty("serverName", "localhost");
  config.addDataSourceProperty("databaseName", "employee");
  config.addDataSourceProperty("charSet", "utf-8");
  return new HikariDataSource(config);
}
----

.Using the Jaybird JDBC driver instead of a data source
[source,java]
----
private static HikariDataSource initDataSourceAlternative2() {
  var config = new HikariConfig();
  config.setDriverClassName("org.firebirdsql.jdbc.FBDriver");
  config.setJdbcUrl("jdbc:firebird://localhost/employee");
  config.setUsername("sysdba");
  config.setPassword("masterkey");
  config.addDataSourceProperty("charSet", "utf-8");
  return new HikariDataSource(config);
}
----

[[data-source-implementation]]
=== The javax.sql.DataSource implementation

Connection pool implementations, whether provided by a Java EE/Jakarta EE application server or a third-party library, are exposed as an implementation of the `javax.sql.DataSource` interface.

The most important method exposed by this interface is the `getConnection()` method, which will return a connection based on the configuration of the data source.
For a 'basic' (non-pooling) data source this will create a new, physical, connection.
For a connection pool, this will create a logical connection that wraps a physical connection from the pool.

[NOTE]
====
The 'user' of a connection should not care whether the connection is pooled or not, the connection should behave the same from the perspective of the user, and the user should use the connection in the same way.
This should allow for swapping between a non-pooling and pooling data source in an application without any changes to the code using the data source.
====

When the application is done with the connection, it should call `close()` on the connection. 
A connection from a non-pooling data source will be closed.
For a logical connection from a connection pool, `close()` will invalidate the logical connection (which will make it behave like a closed connection), and return the underlying physical connection to the connection pool, where it will be either kept for re-use, or maybe closed.

[TIP]
====
Use a connection for the shortest scope, and time, necessary for correct behaviour.
Get a connection, and close it as soon as you're done.
When using a connection pool, this has the added benefit that just a few connections can serve the needs of the application.
====

[[connection-pool-data-source-implementation]]
=== The javax.sql.ConnectionPoolDataSource implementation

The `javax.sql.ConnectionPoolDataSource` interface represents a factory that creates `PooledConnection` objects for use by a connection pool.
For example, application servers support the use of a `ConnectionPoolDataSource` to populate their connection pool.

A `PooledConnection` instance represents a physical connection to a database and is a source of logical connections that a connection pool can hand out to the application.
Closing this logical connection returns the physical connection back into the pool.

[WARNING]
====
Contrary to its name, a `ConnectionPoolDataSource` is not a connection pool!
It is a factory for physical connections that can be used by a connection pool.
====

Jaybird provides `org.firebirdsql.ds.FBConnectionPoolDataSource` as an implementation of the `javax.sql.ConnectionPoolDataSource` interface.

// TODO Add more info

[[xa-data-source-implementation]]
=== The javax.sql.XADataSource implementation

The JDBC 2.0 specification introduced the `javax.sql.XADataSource` interface that should be used to access connections that can participate in distributed transactions with JTA-compatible transaction coordinator.
This gives applications possibility to use two-phase commit to synchronize multiple resource managers.

Just like `javax.sql.ConnectionPoolDataSource`, applications normally don't access an `XADataSource` implementation directly, instead it is used as a factory of connections for an XA-enabled data source. To the application this is usually exposed as a `javax.sql.DataSource`.

Jaybird provides `org.firebirdsql.ds.FBXADataSource` as an implementation of the `javax.sql.XADataSource` interface.
