[[ref-logging]]
=== Logging

Jaybird logs a variety of information during its work.

For logging, jaybird uses the following log levels:

|===
|Jaybird log level |Description

|_trace_
|low-level debug information

|_debug_
|debug information

|_info_
|informational messages

|_warn_
|warnings

|_error_
|errors

|_fatal_
|severe/fatal errors (though in general, level _error_ will be used instead of _fatal_)
|===

[[ref-logging-jul]]
==== java.util.logging

Jaybird uses `java.util.logging` by default.

Jaybird applies the following mapping for its log levels:

|===
|Jaybird log level |_jul_ log level

| `Logger.trace`
| `Level.FINER`

| `Logger.debug`
| `Level.FINE`

| `Logger.info`
| `Level.INFO`

| `Logger.warn`
| `Level.WARNING`

| `Logger.error`
| `Level.SEVERE`

| `Logger.fatal`
| `Level.SEVERE`
|===

[[ref-logging-disable]]
==== Disable logging

To disable logging, specify system property `org.firebirdsql.jdbc.disableLogging` with value `true`.

[[ref-logging-console]]
==== Console logging

Jaybird can write its logging to the `System.out` for _info_ and lower and `System.err` for _warn_ and above.
Levels _debug_ and _trace_ are disabled in the implementation.

To enable logging console, you can set system property `org.firebirdsql.jdbc.forceConsoleLogger` to `true`.

[[ref-logging-custom]]
==== Custom logging implementation

You can provide your own logging implementation if you don't want to use `java.util.logging` or console logging.

To provide a custom logging implementation, you need to implement interface `org.firebirdsql.logging.Logger`.
This implementation must be public and must have a public constructor with a single String argument for the logger name.
Set system property `org.firebirdsql.jdbc.loggerImplementation` with the fully-qualified name of your implementation.

The `org.firebirdsql.logging.Logger` interface should be considered volatile and might change in minor releases (but not point/bugfix releases).

For example:

[source,java]
----
package org.example.jaybird.logging;

public class CustomLogger implements org.firebirdsql.logging.Logger {
    public CustomLogger(String name) {
        // create the logger    
    }
    // implementation of org.firebirdsql.logging.Logger interface
}
----

On the Java command line, specify:

 -Dorg.firebirdsql.jdbc.loggerImplementation=org.example.jaybird.logging.CustomLogger
