[[transactions]]
== Using transactions

Transactions are used to group SQL statements into a single block that satisfies so-called ACID properties: atomicity, consistency, isolation and durability.
In other words, all statements executed within a transaction either succeed and their results will be permanently stored in the database, or the effect of the statement execution will be undone.

=== JDBC transactions

Firebird supports multiple concurrent transactions over the same database connection.
This allows applications that work via the native Firebird API to save the number of network connections, which in turn saves the resources on the serverfootnote:[
Additionally, before the InterBase was open-sourced, this allowed application developers to create multi-threaded application without need to purchase additional user licenses.].

This model however cannot be applied to each database engine in the world and the designers of the JDBC API have chosen a model where each database connection has one and only one active transaction associated with it.
Also, unlike the Firebird model, where transactions require explicit start, the JDBC specification requires the driver to start transaction automatically as soon as a transactional context is needed.

The following code shows a very simple example of using transactions in JDBC where a hypothetical intruder that increases salary of each employee twice and uses explicit transaction control in JDBC.
They also try to hide their identity and if the operations succeed, they commit the transaction, otherwise the roll the changes back.

[source,java]
.Example of explicit transaction control
----
Connection connection = ...

connection.setAutoCommit(false); // <1>

try (Statement stmt = connection.createStament()) {
  stmt.executeUpdate("UPDATE employee " + 
      " SET salary = salary * 2"); // <2>
        
  // ... do some more changes to database
  // to hide the identity of the person
  // that messed up the salary information
  // by deleting the audit trails logs, etc.
    
  stmt.executeUpdate("DELETE FROM audit_trails");
    
  connection.commit(); // <3>
} catch(SQLException ex) {
  connection.rollback(); // <4>
}
----

To use transactions, the application first switches the auto-commit mode off (see below for more information), then creates a `java.sql.Statement` object, and executes an `UPDATE` statement.
Please note, that there is no explicit transaction start, a new transaction will be started right before executing the statement (step 2).

If we work with a database where not only referential integrity is preserved, but also reasonable security rules are encoded in the triggers, it will raise an error preventing cleaning the audit trails information.
In this case the intruder chooses to undo all the changes they made, so that nobody notices anything.
But if no security rules are implemented, they commit the transaction.

[TIP]
====
Firebird PSQL has an `IN AUTONOMOUS TRANSACTION` block that can be used to prevent such abuse and prevent audit-records from being wiped out by a transaction rollback.
Alternatively, you can use an external table to store the audit log.
====

When a connection uses explicit transaction control, each transaction must be finished by calling the `commit()` or `rollback()` methods of the `Connection` object before the connection is closed.
If a transaction was not finished, but the `close` method is called, the active transaction is rolled back automatically.
This also happens when you did not commit or roll back the transaction, and did not close the connection explicitly and that `Connection` object became eligible for garbage collection.
[.until]_Jaybird 5_ In this case, the class finalizer implicitly invokes the `close()` method, which in turn rolls the transaction back.

[WARNING]
====
Given the non-deterministic delay of garbage collection, make sure to explicitly end the transaction and close the connection.
Do not rely on the garbage collector for this.

[.since]_Jaybird 5_ A number of finalizers have been removed in Jaybird 5, so transaction rollback through garbage collection has become even less deterministic (though it is likely still to occur when the connection is forcibly closed).
====

=== Auto-commit mode

Each newly created connection by default has the auto-commit property enabled.
In other words, the duration of the transaction is limited by the duration of statement execution, or more formally -- the transaction is ended when the statement is completed.
The point when statement execution is considered complete, is defined in the specification as:

.Rules when the statement is completed in auto-commit mode
[quote,JDBC 4.3 Specification]
____
A `ResultSet` object is explicitly closed when

* The `close` method on the `ResultSet` is executed, thereby releasing any external resources
* The `Statement` or `Connection` object that produced the `ResultSet` is explictly [sic] closed

A `ResultSet` object is implicitly closed when

* The associated `Statement` object is re-executed
* The `ResultSet` is created with a Holdability of `CLOSE_CURSORS_AT_COMMIT` and an implicit or explicit commit occurs

'''
Note – Some JDBC driver implementations may also implicitly `close` the `ResultSet` when the `ResultSet` type is `TYPE_FORWARD_ONLY` and the `next` method of `ResultSet` returns `false`.

'''
____

[.until]_Jaybird 6_ In Jaybird 5 and earlier, in auto-commit mode, a `TYPE_FORWARD_ONLY` result set was implicitly closed when `next()` returned false.
This was to conform to the requirements of JDBC 3.0, but since this was relaxed in JDBC 4.0 (see quote above), this behaviour was changed in Jaybird 6.

[.since]_Jaybird 6_ In auto-commit mode, a result set will now remain open until explicitly closed using `ResultSet.close()`, when any statement is executed, when the auto-commit mode is disabled, or by the close of the `Statement` or `Connection`.

If there is an ongoing transaction and the value of the auto-commit property is changed, the current transaction is committed.

Note, when a connection is obtained via a `javax.sql.DataSource` object and container managed transactions are used (for example, the application is executing inside an EJB container), it is an error to call `setAutoCommit` method.

Special care should be taken when using multiple statements in auto-commit mode.
The JDBC 2.0 specification did not fully define the rules for the statement completion as it did not define the behavior of multiple `ResultSet` objects created using the same connection object in auto-commit mode.

Since Firebird does not allow the result set to remain open after the transaction ends, Jaybird 1.5.x and below cached the complete result set in memory when `SELECT` statements were executed and the transaction was committed.
This had an adverse effect on allocated memory when the result set is big, especially when it contains BLOB fields.
The JDBC 3.0 specification addressed this unclear situation (see above) and Jaybird 2.1 was improved to correctly handle them.
It also allowed to reduce the memory footprint -- the driver no longer caches non-scrollable and non-holdable result sets in memory.

However, some Java applications that do not conform the current JDBC specification might no longer work with Jaybird 2.1 and above unless additional steps are taken.

The piece of code below works perfectly with explicit transaction control.
However, it won't work correctly with auto-commit with a driver -- like Jaybird -- that complies with the JDBC 3.0 specification, when the `selectStmt` and `updateStmt` object are created by the same connection object (step 1).
When the UPDATE is executed in step 3, the result set produced by the SELECT statement must be closed before the execution.
When the Java application tries to fetch the next record by calling the `rs.next()` method, it will receive an `SQLException` with a message _"The result set is closed"_.

The only correct solution to this situation is to fix the application by either using explicit transaction control, or by using two connection objects, one for SELECT statement and one for UPDATE statement.

[source,java]
.Non-compliant usage of nested statements in auto-commit mode
----
try (Statement selectStmt = connection.createStatement(); // <1>
     Statement updateStmt = connection.createStatement();
     ResultSet rs = selectStmt.executeQuery(
         "SELECT * FROM myTable")) {
  while(rs.next()) { // <2>
    int id = rs.getInt(1);
    String name = rs.getString(2);

    updateStmt.executeUpdate("UPDATE anotherTable SET " +
        " name = '" + name + "' WHERE id = " + id); // <3>
  }
}
----

Unfortunately, not all applications can be changed either because there is no source code available or, simply, because any change in the code requires complete release testing of the software. 
To address this, Jaybird 2.1 introduced the connection parameter `defaultHoldable` which makes result sets holdable by default. 
The holdable result sets will be fully cached in memory, but won't be closed automatically when transaction ends.footnote:[
Other cases, e.g. closing the statement object or the connection object will still ensure that the result set object is closed. 
If you need result sets that can be "detached" from the statement object that created them, please check the `javax.sql.RowSet` implementations.] 
This property also affects the default holdability of result sets when auto-commit is disabled.

See <<ref-defaultholdable>> for more information.

=== Read-only Transactions

A transaction can be declared read-only to reduce the possibility of lock conflicts.
In general, this makes little sense for Firebird, because of its multi-generational architecture, where readers do not block writers and vice versa.
However, in some cases it can be useful.

It is not allowed to connect with a read-write transaction to a database located on a read-only media, for example, a CD-ROM.
The reason is that, to guarantee consistency of the read-write transactions, Firebird has to increase the transaction identifier when transaction ends, and to store the new value on the so-called Transaction Inventory Page even if no changes were made in that transaction.
This requirement can be relaxed if transaction is declared read-only and the engine ensures that no data can be modified.

Another reason is that long-running read-write transactions inhibit the process of collecting garbage, i.e. a process of identifying previous versions of the database records that are no longer needed and releasing the occupied space for the new versions.
Without garbage collection the database size will grow very fast and the speed of the database operations will decrease, because the database engine will have to check all available record versions to determine the appropriate one.

Therefore, if you are sure that application won't modify the database in the transaction, use the `setReadOnly` method of the
`java.sql.Connection` object to tell the server that the transaction is read-only.

[[transactions-isolation-levels]]
=== Transaction Isolation Levels

The ANSI/ISO SQL standard defines four such levels, each next one weaker than the previous.
These isolation levels are also used in the JDBC specification:

[cols="2,3",options="header",]
.JDBC transaction isolation levels and their characteristics
|===
|JDBC isolation level
|Description

m|TRANSACTION_SERIALIZABLE
|Transactions with this isolation level prohibit phantom reads, the situation when one transaction reads all rows satisfying the WHERE condition, another transaction inserts a row satisfying that condition, and first transaction re-executes the statement.

m|TRANSACTION_REPEATABLE_READ
|This isolation level prevents non-repeatable reads, a situation when a row is read in one transaction, then modified in another transaction, and later re-read in the first transaction.
In this case different values had been read within the same transaction.

m|TRANSACTION_READ_COMMITTED
|Transactions with this isolation level can see only committed records.
However, it does not prevent so-called non-repeatable reads and phantom reads.

m|TRANSACTION_READ_UNCOMMITTED
|The weakest isolation level, or better to say level with no isolation.
Such transactions can see the not yet committed changes to the data in the database from the concurrently running transactions.

|===

Firebird, however, defines other isolation levels: `read_committed`, `concurrency` and `consistency`.
Only the `read_committed` isolation level can be mapped to the same level defined by the ANSI/ISO SQL standard.
Dirty reads are prevented, non-repeatable reads as well as phantom reads can occur.

The `concurrency` isolation level is stronger than repeatable read isolation defined in ANSI/SQL standard and satisfies the requirements of a serializable isolation level, however, unlike RDBMSes with locking concurrency control, it guarantees better performance.

And finally Firebird provides a `consistency` isolation level which in combination with table reservation feature guarantees the deadlock-free execution of transactions.
A transaction will be prevented from starting if there is already another one with the overlapping sets of the reserved tables.
This isolation level guarantees truly serial history of transaction execution.

To satisfy the JDBC specification Jaybird provides a following default mapping of the JDBC transaction isolation levels into Firebird isolation levels:

* TRANSACTION_READ_COMMITTED is mapped to `read_committed` isolation level in Firebird -- any changes made inside a transaction are not visible outside a transaction until the transaction is committed.
A transaction in read-committed mode sees all committed changes made by other transactions even if that happened after start of the current transaction.
* TRANSACTION_REPEATABLE_READ is mapped to `concurrency` isolation level in Firebird -- any changes made inside this transaction are not visible outside a transaction until the transaction is committed.
A transaction in repeatable-read sees only those changes that were committed before the transaction started.
Any committed change in another transaction that happened after the start of this transaction is not visible in this transaction.
* TRANSACTION_SERIALIZABLE is mapped into `consistency` isolation level in Firebird -- any modification to a table happens in serial way: all transactions wait until the current modification is done.
This mode can be considered as a traditional pessimistic locking scheme, but the lock is placed on the whole table.
See section "<<transactions-table-reservation>>" for more information.

The default mapping is specified in the Jaybird code and can be overridden via the connection properties.

* via the `tpbMapping` property that specifies the name of the `ResourceBundle` with the new mapping of the isolation level;
* via the direct specification of the JDBC transaction isolation level.
The following code contains an example of such operation, the values in the mapping are described in section "<<transactions-tpb>>".
* via the data source configuration.

[source,java]
.Overriding the default isolation level mapping
----
Properties props = new Properties();
props.setProperty("user", "SYSDBA");
props.setProperty("password", "masterkey");
props.setProperty("TRANSACTION_READ_COMMITTED",
    "read_committed,no_rec_version,write,nowait");
    
Connection connection = DriverManager.getConnection(
    "jdbc:firebirdsql://localhost:3050/c:/example.fdb",
    props);
----

The property accepts the "`short`" names as shown, or the "`long`" names with the `isc_dpb_` prefix, as defined in `org.firebirdsql.jaybird.fb.constants.TpbItems` (Jaybird 5 and higher) or `org.firebirdsql.gds.ISCConstants` (older versions).
For readability, we recommend using the "`short`" names.

The overridden mapping is used for all transactions started within the database connection.
If the default mapping is overridden via the data source configuration, it will be used for all connections created by the data source.

[[transactions-savepoints]]
=== Savepoints

Savepoints provide finer-grained control over transactions by providing intermediate steps within a larger transaction.
Once a savepoint has been set, a transaction can be rollback to that point without affecting preceding work.

To set a savepoint, use the following code:

[source,java]
.Example of using savepoints
----
Connection connection = ...;
connection.setAutoCommit(false);

try (Statement stmt = connection.createStatement()) {
  stmt.executeUpdate(
      "INSERT INTO myTable(id, name) VALUES (1, 'John')");

  Savepoint savePoint1 =
      connection.setSavepoint("savepoint_1");

  stmt.executeUpdate(
      "UPDATE myTable SET name = 'Ann' WHERE id = 1");
  // ...

  connection.rollback(savePoint1);

  // at this point changes done by second update are undone
}
----

Note, rolling back to the savepoint automatically releases and invalidates any savepoints that were created after the released savepoint.

If the savepoint is no longer needed, you can use the `Connection.releaseSavepoint` method to release system resources.
After releasing a savepoint it is no longer possible to roll back the current transaction to that savepoint.
Attempts to call the `rollback(Savepoint)` method will result in an `SQLException`.
Savepoints that have been created within a transaction are automatically released when that transaction is committed or rolled back.

[[transactions-tpb]]
=== Transaction Parameter Buffer

The behavior of Firebird transactions is internally controlled by the _Transaction Parameter Buffer_ (TPB), which specifies different transaction properties:

* the transaction isolation level;
* the transaction's read-only or read-write mode;
* the lock conflict resolution mode -- wait or no wait;
* the lock wait timeout;
* and, finally, the table reservations -- their names and reservation modes.

The TPB is automatically generated depending on the transaction isolation level specified for the `java.sql.Connection` object.
Additionally, if the connection is set to read-only mode, this is reflected in the TPB by appropriate constant.

Usually there is no need to manipulate the TPB directly.
However, the lock resolution mode as well as table reservations cannot be specified by using the standard JDBC interfaces.
For the cases where this is needed, Jaybird provides an extension of the JDBC standard.

[source,java]
.Example of specifying custom TPB
----
FirebirdConnection fbConnection =
    connection.unwrap(FirebirdConnection.class);
    
TransactionParameterBuffer tpb = 
    fbConnection.createTransactionParameterBuffer();
    
tpb.addArgument(TpbItems.isc_tpb_read_committed);
tpb.addArgument(TpbItems.isc_tpb_rec_version);
tpb.addArgument(TpbItems.isc_tpb_write);
tpb.addArgument(TpbItems.isc_tpb_wait);
tpb.addArgument(TpbItems.isc_tpb_lock_timeout, 15);

fbConnection.setTransactionParameters(tpb);
----

The above presents an example of populating the TPB with custom parameters.

The constants used in the examples in this chapter were introduced in Jaybird 5.
Earlier versions have constants of the same name defined in `org.firebirdsql.gds.ISCConstants`, and similarly named constants in `org.firebirdsql.gds.TransactionParameterBuffer` (i.e. without `isc_tpb_` prefix and fully capitalized).
Those older constants will be removed in Jaybird 6 in favour of `org.firebirdsql.jaybird.fb.constants.TpbItems`.

==== Isolation level

Firebird supports three isolation levels: `read_committed`, `concurrency` and `consistency` which are represented by appropriate constants in the `TpbItems` class.
The isolation level specifies the way the database engine processes the record versions on read operations.
The `concurrency` isolation level is also often called `SNAPSHOT` and the `consistency` isolation level -- `SNAPSHOT TABLE STABILITY`.

In `consistency` and `concurrency` modes, the Firebird database engine loads the different versions of the same record from disk and checks the "`timestamps`" of each version and compares it with the "`timestamp`" of the current transaction.
The record version with the highest timestamp that is however lower or equal to the timestamp of the current transaction is returned to the application.
This effectively returns the version of the record that was committed before the current transaction started, and guarantees that neither non-repeatable reads nor phantom reads can ever occur.

In `read_committed` mode, the Firebird database engine accesses the record version with the highest timestamp for which the corresponding transaction is marked as committed.
This prevents the engine from reading the record versions which were modified in concurrent transactions that are not yet committed or were rolled back for whatever reason.
However, such mode allows non-repeatable reads as well as phantom reads if a concurrent transaction that modified records or inserted new ones has been committed.

The `read_committed` isolation mode requires another constant that specifies the behavior of the transaction when it sees a record version with a timestamp that belongs to a currently running transaction which is not yet committed.

Most applications require the `TpbItems.isc_tpb_rec_version` mode, or `READ COMMITTED RECORD VERSION`, which is shown in the code above.
In this mode database engine fetches the latest committed version as described before.

The `TpbItems.isc_tpb_no_rec_version` constant tells the database engine to report a lock conflict when an uncommitted record version is seen while fetching data from the database, also known as `READ COMMITTED NO RECORD VERSION`.
The outcome of the operation is then controlled by the lock resolution mode (see section <<transactions-lock-resolution>>).

The `TpbItems.isc_tpb_read_consistency` uses the `READ COMMITTED READ CONSISTENCY` mode introduced in Firebird 4.0.

.Firebird 4.0 and higher default to always use `isc_tpb_read_consistency`
[WARNING]
====
With default settings, Firebird 4.0 and higher will ignore `isc_tpb_rec_version` and `isc_tpb_no_rec_version`, and behave as if `isc_tpb_read_consistency` was specified.
This is controlled through the `ReadConsistency` setting in `firebird.conf` or -- per database -- in `databases.conf`.
====

[[transactions-read-only]]
==== Read-only transactions

The read-only or read-write transaction mode is controlled by two constants:

* `TpbItems.isc_tpb_read` and
* `TpbItems.isc_tpb_write`

When the read-write mode (constant `isc_tpb_write`) is specified, the database engine stores the "`timestamp`" of the new transaction in the database even when no modification will be made in the transaction.
The "`timestamp`" affects the garbage collection process, since the database engine cannot release records that were modified in transactions with higher "`timestamps`" even when these record versions are no longer needed (in other words, when there are already newer versions of the records).
Thus, long-running read-write transaction inhibits the garbage collection even when no modifications are done in it.

Therefore, it is recommended to set the read-only mode for the transaction when it is used for read operations.

[NOTE]
====
[.since]_Firebird 4.0_ With the `READ COMMITTED CONSISTENCY` mode introduced in Firebird 4.0, even read-only transactions will inhibit garbage collection.
====

[[transactions-lock-resolution]]
==== Lock resolution mode

Relational database systems that use pessimistic locking for concurrency control lock the records regardless of the operation type, read or write.
When an application tries to read a record from the database, the database engine tries to obtain a "read lock" to that record.
If the operation succeeds and the application later tries to update the record, the lock is upgraded to a "`write lock`".
And finally, if the resource is already locked for write, a concurrent transactions cannot lock it for reading, since the system cannot allow the transaction to make a decision based on data that might be rolled back later.
This approach significantly decreases concurrency.
However, databases systems that employ a record versioning mechanism do not have such restrictions because each transaction "`sees`" its own version of the record.
The only possible conflict happens when two concurrent transactions try to obtain a "`write lock`" for the same database record.

Firebird belongs to the latter, and on `read_committed` and `concurrency` isolation levels it behaves appropriately -- there are no
lock conflicts between readers and writers, and only writers competing for the same resource raise a lock conflict.
However, on the `consistency` isolation level Firebird emulates the behavior of systems with pessimistic locking -- read operations will conflict with write operations.
Even more, the locks are obtained for whole tables (see "<<transactions-table-reservation>>" for details).

The following table summarizes the above for Firebird 2.0.
It shows that read-committed or repeatable read transactions conflict only when they simultaneously update the same rows.
In contrast, a `consistency` transaction conflicts with any transaction running in read-write mode, e.g. as soon as a `consistency` transaction gets write access to a table, other read-write transactions are not allowed to make changes in that table.

[cols="34%,18%,18%,15%,15%",]
.Lock conflicts within one table depending on the isolation level
|====
|{nbsp}
|Read-committed, Concurrency read-write
|Read-committed, Concurrency read-only
|Consistency, read-write
|Consistency, read-only

|Read-committed, Concurrency read-write
|some updates may conflict
|{nbsp}
|conflict
|conflict

|Read-committed, Concurrency read-only
|{nbsp}
|{nbsp}
|{nbsp}
|{nbsp}

|Consistency read-write
|conflict
|{nbsp}
|conflict
|conflict

|Consistency read-only
|conflict
|{nbsp}
|conflict
|{nbsp}

|====

[[transactions-table-reservation]]
=== Table Reservation

Table reservation allows you to specify the database tables and their corresponding access modes at the beginning of the transaction.
When the transaction is started, the engine tries to obtain the requested locks for the specified tables and proceeds only when all of them were successfully obtained.
Such behavior allows to create a deadlock-free execution historyfootnote:[
This approach follows the two-phase locking protocol, where all locks are acquired on the beginning of the transaction and are released only when transaction is finished.].

The table reservation is specified via a TPB and includes the table to lock, the lock mode (read or write) and lock type (shared, protected and exclusive).

[source,java]
.Example of using table reservation facility in Firebird
----
FirebirdConnection connection = ...
TransactionParameterBuffer tpb =
    connection.createTransactionParameterBuffer(); // <1>

tpb.addArgument(TpbItems.isc_tpb_consistency); // <2>
tpb.addArgument(TpbItems.isc_tpb_write);
tpb.addArgument(TpbItems.isc_tpb_nowait);

tpb.addArgument(TpbItems.isc_tpb_lock_write,
    "TEST_LOCK");
tpb.addArgument(TpbItems.isc_tpb_protected);

connection.setTransactionParameters(tpb); // <3>

// next transaction will lock TEST_LOCK table for writing
// in protected mode
----

This shows an example of reserving the `TEST_LOCK` table for writing in a protected mode.
The code does the following:

<1> Create a new instance of `TransactionParameterBuffer` class.
<2> Populate the TPB.
The first three statements were described in "<<transactions-tpb>>".
The fourth call specifies that the application wants to obtain a lock on the table `TEST_LOCK` for writing.
The fifth call specifies the type of the lock to obtain, in our case the protected lock.
<3> Set the new TPB to be used for the next transaction.

The lock mode to the table specified in the TPB can be either

* `TpbItems.isc_tpb_lock_read` for read-only access to the table;
* or `TpbItems.isc_tpb_lock_write` for read-write access to the table.

The lock type can be either

* `TpbItems.isc_tpb_shared` for shared access to the table;
* or, `TpbItems.isc_tpb_protected` for protected access to the table;

The `TpbItems.isc_tpb_exclusive` mode was introduced in later versions of Firebird, however it behaves like `TpbItems.isc_tpb_protected` mode for all read-write transactions.

The lock conflict table depends on the isolation level of the transactions and has the following properties:

* `isc_tpb_lock_write` mode always conflicts with another `isc_tpb_lock_write` mode regardless of the lock type and transaction isolation mode;
* `isc_tpb_lock_write` always conflicts with another `isc_tpb_lock_read` mode if both transactions have `consistency` isolation, but has no conflict with shared-read locks if the other transaction has either `concurrency` or `read_committed` isolation level;
* `isc_tpb_lock_read` mode never conflicts with `isc_tpb_lock_read` mode.

[#transactions-mgmt-stmts]
=== Transaction management statements

The Firebird syntax also defines a number of transaction management statements.
In this section we discuss the `COMMIT [WORK]`, `ROLLBACK [WORK]` and `SET TRANSACTION` statements, which have a hard transaction boundary (either ending or starting a transaction).

In general, you should not execute these methods with Jaybird (or any other JDBC driver).
The JDBC specification formally discourages use of statements or functionality which is accessible through the JDBC API:

[quote,java.sql.Connection,JDBC API documentation]
____
*Note:* When configuring a `Connection`, JDBC applications should use the appropriate `Connection` method such as `setAutoCommit` or `setTransactionIsolation`.
Applications should not invoke SQL commands directly to change the connection's configuration when there is a JDBC method available.
____

In Jaybird 5 and older, the `COMMIT` and `ROLLBACK` statements can -- sometimes -- be executed, but they bring the connection in an inconsistent state, which will prevent further use of the connection, and execution of the `SET TRANSACTION` statement will always fail as the statement is executed with an active transaction.

Since Jaybird 6, these statements are rejected by default, but support can be enabled with the <<ref-allowtxstmts,connection property `allowTxStmts`>>.

Allowing execution of these statements can sometimes be helpful, for example for executing scripts, or simplifying access to more advanced features of transaction configuration like <<transactions-table-reservation>>.
