name: publish-to-github-pages
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'FirebirdSQL/jaybird-manual'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326
      - name: Build with Gradle
        run: ./gradlew makePages
      - name: Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages-artifact
          path: build/pages
          compression-level: 9
          retention-days: 1
  publish-pages:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Get pages artifact
        uses: actions/download-artifact@v4
        with:
          name: pages-artifact
          path: pages
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: pages