[[systemproperties]]
[appendix]
== System properties

Jaybird provides a number of system properties to control global behaviour of Jaybird.

[[systemproperties-logging]]
=== Logging

To configure logging, the following system properties are available. 
See <<ref-logging>> for details.

`org.firebirdsql.jdbc.forceConsoleLogger`::
Set to true to force logging to console (`System.out` for info, `System.err` for warn, error and fatal) instead of default `java.util.logging`
`org.firebirdsql.jdbc.disableLogging`::
Set to true to disable logging
`org.firebirdsql.jdbc.loggerImplementation`::
Fully-qualified name of `org.firebirdsql.logging.Logger` implementation to use for logging

These properties need to be set before Jaybird is loaded and used.

[[systemproperties-processinfo]]
=== Process information

For Firebird 2.1 and higher, Jaybird can provide Firebird with process information.
This information can be specified in connection properties, or globally using the following system properties.

`org.firebirdsql.jdbc.processName`::
Process name to send to Firebird
`org.firebirdsql.jdbc.pid`::
PID to send to Firebird (must be a valid integer)

The property values are read for each connect, so the value can be changed at any time.

[[systemproperties-charset]]
=== Character set defaults

The following system properties control character set behaviour for connections.

`org.firebirdsql.jdbc.defaultConnectionEncoding`::
Firebird character set name to use as connection character set when no explicit connection character set is configured (defaults to `NONE` when not set)
`org.firebirdsql.jdbc.requireConnectionEncoding`:: [.since]_Jaybird 3.0.2_ 
Set to true to disallow connections without an explicit connection character set.
This property will have no effect if `org.firebirdsql.jdbc.defaultConnectionEncoding` has been set.

The property values are read for each connect, so the value can be changed at any time.

[[systemproperties-wire-buffers]]
=== Wire protocol buffer sizes

[.since]_Jaybird 6_

The following system properties control the sizes of a number of buffers used by Jaybird's wire protocol implementation.

`org.firebirdsql.wire.deflateBufferSize`::
Buffer size in bytes for deflate (compression).
Has a minimum size of 512 and a default value of 8192.
`org.firebirdsql.wire.inflateBufferSize`::
Buffer size in bytes for inflate (decompression).
Has a minimum size of 512 and a default value of 8192.
`org.firebirdsql.wire.decryptBufferSize`::
Buffer size in bytes for decryption.
Has a minimum size of 512 and a default value 8192.
+
[NOTE]
====
As the decryption input buffer determines the size of the decryption output buffer, the actual allocation is up to twice the specified value.
====
`org.firebirdsql.wire.inputBufferSize`::
Buffer size in bytes for reading data from the socket.
Has a minimum size of 1024 and a default value of 16384.
+
[CAUTION]
====
This property should not be confused with the socket buffer size (configurable with the `socketBufferSize` _connection property_).
Setting this value higher than `socketBufferSize` is unlikely to have any benefits.
====
`org.firebirdsql.wire.outputBufferSize`::
Buffer size in bytes for writing data.
Has a minimum size of 1024 and a default value of 32768.
+
[CAUTION]
====
This property should not be confused with the socket buffer size (configurable with the `socketBufferSize` _connection property_).
Contrary to the input buffer size, setting it higher than `socketBufferSize` might have performance benefits.
====

These properties need to be set before Jaybird is loaded and used.

[NOTE]
====
The minimum sizes and default values should be considered an implementation detail and might change in a future major version.

The "`deflate`" and "`inflate`" buffers are only used when wire compression is enabled.
The "`decrypt`" buffer is only applied when wire encryption is used (the default with Firebird 3.0 and higher).
====

The order of buffers for input is as follows:

[subs="normal"]
----
Jaybird <= [inflate <=] [decrypt <=] input <= socket
----

The order of buffers for output is as follows:

[subs="normal"]
----
Jaybird => output [=> deflate] => socket
----

[[systemproperties-other]]
=== Other properties

The following system properties control other global behaviour of Jaybird.

`org.firebirdsql.jna.syncWrapNativeLibrary`::
Set to true to add a synchronization proxy around the native client library.
`org.firebirdsql.datatypeCoderCacheSize`:: [.since]_Jaybird 4_ 
Integer value for the number of encoding specific data type coders cached (default and minimum is 1). 
Setting to a higher value may improve performance, most common use case is connection character set `NONE` with a database that uses more than one character set for its columns. 
Jaybird will log a warning (_"Cleared encoding specific datatype coder cache [..]"_) when the cache size was exceeded.
`org.firebirdsql.nativeResourceShutdownDisabled`:: [.since]_Jaybird 4_ 
Set to true to disable automatic shutdown and unload of native libraries and other native resources.
Normally you should only use this if the automatic shutdown misbehaves and causes application errors. 
If you need to set this to true, we'd appreciate it if you post a message to the https://groups.google.com/g/firebird-java[firebird-java Google Group^] with details on why you needed to enable this, so we can improve or fix this feature.

These properties need to be set before Jaybird is loaded and used.
Technically, `org.firebirdsql.jna.syncWrapNativeLibrary` is dynamic, but a native library will usually be loaded once.

[[systemproperties-java]]
=== Useful Java system properties

The following Java system properties are relevant for Jaybird.

`jdk.net.useFastTcpLoopback`:: [.since]_Firebird 3.0.2_ [.since]_Jave 8 update 60_ [.since]_Windows 8 / Windows Server 2012_
Set to true on Windows to enable "`TCP Loopback Fast Path`" (`SIO_LOOPBACK_FAST_PATH` socket option).
"`TCP Loopback Fast Path`" can improve performance for localhost connections. +
Java only has an 'all-or-nothing' support for the "`TCP Loopback Fast Path`", so Jaybird cannot enable this for you: you must specify this property on JVM startup.
This has the benefit that this works for all Jaybird versions, as long as you use Java 8 update 60 or higher (and Firebird 3.0.2 or higher).
+
[WARNING]
====
Microsoft has deprecated the `SIO_LOOPBACK_FAST_PATH` and recommends not to use it.
====
